### ISSUE TITLE
Sometimes doesn't link to audio

### ISSUE THREAD

**Issue by bphd** [wwmm/easyeffects#1005]
1 time out of 3, when PE starts (at boot or manually), he's not linked to audio, so no audio outputs. My workaround is to restart the app (kill and reinvoke), and if I got luck this restart will link everything nicely, and I will have sound
Sometimes you can, too, try to relink things manually by playing with default audio or links in PAGC, but it's messy and doesn't always work. Restart is more reliable as it's simple and always work after some tries

I don't know if any logs will be relevant here as it's not properly an error but more that sometimes PE ignores audio I/O, sometimes not, it not seems like an error. But tell me if you need something

The objective is that all the time PE starts well configured, linked to audio, and basically do his job, consistently, maybe by memorizing his precedent configuration (who he already seems to try to), or something, but consistent, not random

**Comment by wwmm** [comment]
>I don't know if any logs will be relevant here as it's not properly an error but more that sometimes PE ignores audio I/O, sometimes not, it not seems like an error. But tell me if you need something

You could try to run in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. Just remember to kill any previous instance first `pulseeffects -q`. But unless the problem happens exactly at the time you are running in debug mode It won't be useful.

>maybe by memorizing his precedent configuration (who he already seems to try to)

It depends on what kind of configuration you are thinking of. We save many settings but the default behavior when it comes to default input/output device is to rely on the sound server.

I wonder if in the recently released EasyEffecs 6.0.1 we will still have this kind of problem.

**Comment by bphd** [comment]
I think I probed the problem a little bit better. In PAGC all is linked nicely and Firefox sends audio samples to PE. It's just that sometimes PE "crashes" not physically, his GUI stays totally manipulable, but the audio spectrum graphic that he displays freeze at a certain frame (the last song played) and that's all, it doesn't output anything. And that OFTEN happens, like 10 times a day, I'm so used to restart it that I almost have a shortcut for `killall pulseeffects; pulseeffects & exit`

**Comment by wwmm** [comment]
What is this `PAGC` exactly? I never used it. But it is strange that the debug mode is creating new stream entries. But like I said in the other issue it would be better to focus on solving this problems once you can try EasyEffects. Because of the many differences we may be just wasting time debug PulseEffects.

**Comment by Msouza91** [comment]
On that note, who packages this for fedora? It is still on pulseeffects 5.04. I'm asking because I have similar issues, but kicked up a notch, because if I'm playing audio and then I pause it for something, it looses connection to the audio output and I have to run a similar script to OP, bound it to a key comb beacause it happens multiple times a day; it doesn't change the default output consistently, when I connect my USB-C DAC dongle I have to change it manually and it also borks the master volume control through media keys, I have to open the pannel to control volume per app if the application doesn't have a slider, like telegram or whatsapp notifications that get too loud by default.

**Comment by wwmm** [comment]
>On that note, who packages this for fedora?

If I am not mistaken it is @Vascom. But last time I checked Fedora did not have gtkmm4 packaged yet. And without it building EasyEffects is impossible.

**Comment by Vascom** [comment]
https://bugzilla.redhat.com/show_bug.cgi?id=1980111

**Comment by LifeWatcher123** [comment]
I can confirm this issue on EasyEffects. I might be totally wrong, but on my setup it happens when I run EasyEffects and Carla at the same time. I'm open to instructions on how to help.

**Comment by wwmm** [comment]
>on my setup it happens when I run EasyEffects and Carla at the same time. 

The issue we had on some setups about missing channel links was fixed. If you have to run Carla to see it happening it may be some kind of conflict between them while managing the links. Both try to do that. In these cases a good thing to do is taking a look at the output of `pw-dot` to see which links are broken. The file generated by pw-dot can be viwed with `xdot`.

**Comment by LifeWatcher123** [comment]
I was testing earlier by rebooting several times without opening Carla, but
it seems it’s unrelated. I’ll try tomorrow if I can reproduce it on a
data-cleaned reinstall of the Flatpak version, but I’ll check `pw-dot’
beforehand just in case.

**Comment by wwmm** [comment]
With the improvements in EasyEffects `6.2.6` released today I think this kind of bug may have been fixed. If not it is probably better to open an new issue anyway considering how many things have changed after all this time.
