### ISSUE TITLE
presets dropdown rendered half outside the current monitor

### ISSUE THREAD

**Issue by HarHarLinks** [wwmm/easyeffects#1012]
I'm using Version         : 6.0.1-1 on arch with sway Version         : 1:1.6.1-1 as wm with multiple monitors.

with EE maximized to the whole desktop, clicking the presets button in the top left corner opens the dropdown, but since it renders outside the window itself on the left side a good chunk isn't visible. this is an issue both when using my leftmost monitor as well as another that isn't perfectly aligned.

imo showing your menus outside of your window is not a good idea.

**Comment by wwmm** [comment]
>imo showing your menus outside of your window is not a good idea.

It definitely isn't. And I am not asking gtk4 to do that. I will do some tests later on gnome but I bet it is not going to happen there. I have the feeling that gtk4 and sway are having some compatibility problems.

**Comment by wwmm** [comment]
As I as expecting it does not happen on gnome
![Screenshot from 2021-07-11 11-00-34](https://user-images.githubusercontent.com/16225172/125198282-ad175c00-e237-11eb-9432-b161e5f9285b.png)

The blocklist menu on the bottom right corner is also fine
![Screenshot from 2021-07-11 11-00-43](https://user-images.githubusercontent.com/16225172/125198293-c02a2c00-e237-11eb-9c77-e3219c4c9902.png)

The source of this issue is either in gtk4 or in sway.

**Comment by HarHarLinks** [comment]
perhaps it's `(easyeffects:65741): Gdk-WARNING **: 16:47:56.697: Compositor doesn't support moving popups, relying on remapping`
thanks for your feedback. log sounds like sway to me?

**Comment by wwmm** [comment]
>hanks for your feedback. log sounds like sway to me?

Yes. Unless that gtk4 warning is somehow misleading it seems that sway does not support what gtk4 would like to use. The question is if the `remapping` should be enough to handle the situation or not. So there is still the possibility that both gtk4 and sway need fixing.

**Comment by wwmm** [comment]
In any case it is not something that can be properly fixed in EasyEffects.
