### ISSUE TITLE
[Feature Request] Toggle CSD Window Buttons

### ISSUE THREAD

**Issue by rensenware** [wwmm/easyeffects#1016]
For those that use standalone window managers without titlebars or window buttons, the presence of client side decoration window buttons can break visual consistency and make the application feel out of place. It would be nice if there was a toggle in the settings for specifically the minimize, maximize, and close buttons on the application.

**Comment by wwmm** [comment]
>It would be nice if there was a toggle in the settings for specifically the minimize, maximize, and close buttons on the application.

I think it can be done. But shouldn't this be already part of the gtk integration on other systems? Or this kind of thing exists only for KDE and not for the other desktops?

**Comment by rensenware** [comment]
If it does, I'm not aware of it. I've haven't been able to find anything on toggling CSD.

**Comment by rensenware** [comment]
I was wrong, there is a flag you can set in ~/.config/gtk-4.0/settings.ini to disable it. Add the line `gtk-decoration-layout = ""` to disable the buttons.

**Comment by wwmm** [comment]
Ok. Good to know. If you want you can edit our wiki FAQ to help users interested in the same thing.

**Comment by duncanyoyo1** [comment]
I'd like to say that setting that flag does not work, at least for me. It results in some weird graphical glitches when the app isn't maximized, as well as not showing the title bar until I toggle it manually. 
![Screenshot_20210712_012855](https://user-images.githubusercontent.com/24286951/125235512-93662b00-e2b0-11eb-8879-159863540c32.png)

**Comment by wwmm** [comment]
It is bad indeed. But the proper place to fix this is in whatever is doing the integration of gtk apps in other environments. As gtk4 is relatively new it may take sometime until such integrations are updated.

I wonder if this is something gtk4 should be doing on its own or if the graphical toolkit used by your desktop is the one that should be handling this.

**Comment by duncanyoyo1** [comment]
GTK4 isn't supported in really any DE but Gnome at this point. At least not well.

I'd also like to note, that proper GTK4 support basically requires Wayland for my DE and I can't use Wayland because of my graphics card. Maybe some day, but not today.

**Comment by wwmm** [comment]
>I am running KDE 5.22.3 which should have some support for GTK4 apps but it seems mostly geared towards Wayland and not X11, as well as being mostly fixes to the Breeze theme itself, and not anything to do with the compositor or how it handles the windows.

That is unfortunate. In my experience gtk4 is working fine in GNOME both in X11 and in Wayland.

>I'm not sure why the change from GTK3 to GTK4. If it's just because of Gnome I'd ask you to reconsider. There are many other DEs out there than Gnome.

I did not do it because of GNOME. GTK4 has widgets that do not even exist in gtk3 and that are very convenient to use. It is way better to handle lists in gtk4. Think of our move from gtk3 to gtk4 in the same sense as to why QT applications and KDE moved from QT4 to QT5. It is just natural to want to take advantage of the new features provided by the new toolkit. As someone that used KDE for many years before moving to GNOME I understand how you feel. I used to hate client side decorations. But at the same time it is not reasonable that a gtk app delays the move to a new toolkit that will be better for it because the toolkit integration in some desktops is not properly implemented yet.

**Comment by duncanyoyo1** [comment]
I understand wanting to use the newest toolkit, but it just seems a bit early for proper support yet. 

It took years before GTK3 was well supported.

It's just unfortunate everyone who doesn't use Gnome isn't a consideration.

**Comment by wwmm** [comment]
I get it. But on the other side we would not have EasyEffects today if the port to gtk4 had been delayed. The reason is that from the beginning I knew the move from GStreamer to native PipeWire filters would require tons of work and interface reimplementation. Same thing for the move from gtk3 to gtk4. So if I am going to make deep changes in the way the application interface is implemented it is better to do both things together. Otherwise I would risk having to undo previous work beause of differences between GStreamer and PipeWire filters. If I did not moved to gtk4 now we also would not have Gstreamer replaced by PipeWire filters because I would just wait till the day gtk4 could be used. And all the bugs fixed by using PipeWire filters would not have been fixed. It was not an easy call to make but it had to be done at some point.

**Comment by duncanyoyo1** [comment]
Maybe I should open another issue because it seems like since the move to the PipeWire filters, I can't get decent audio with EE.

Using any filters at all results in errors like, 
```
 pipewire[2311]: (pe_soe_limiter-224) client too slow! rate:2048/192000 pos:361185792 status:awake
 pipewire[2311]: (pe_sie_equalizer-228) client too slow! rate:2048/192000 pos:310935552 status:awake
 pipewire[2311]: (pe_soe_spectrum-279) client too slow! rate:2048/192000 pos:341199360 status:triggered
 pipewire[2311]: loop 0x55d7b19b7a50: failed to read timer fd 18: Resource temporarily unavailable

```

Which is causing a lot of stutter/popping. I don't recall having these issues previously, before the rename.

**Comment by wwmm** [comment]
It is better to open a new issue for this. When you do it try to get easyeffects logs. First you kill its current instance `easyeffects -q` and then you restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. Maybe something useful will be shown. Those `client too slow!` PipeWire messages are not always enlightening. I asked about them once in PipeWire's page and I did not get a clear answer about how to fix them.

**Comment by wwmm** [comment]
So far the feedback I have received is that the new implementation based on PipeWire filters is a lot better than the previous one. But maybe your hardware has something different that is triggering some kind of bug.

**Comment by duncanyoyo1** [comment]
Thanks for the help and the civil discussion, I'll get some logs and create a new issue.

**Comment by TRPB** [comment]
I'd just like to add that `gtk-decoration-layout=""` isn't working for me (sway/wayfire).

I'm not too bothered about the title bar buttons but what is frustrating is the lack of a border around the window, this means that the highlight I have around the focused window is missing entirely and I can't tell if EasyEffects has focus or not.

**Comment by MorsMortium** [comment]
https://codeberg.org/MorsMortium/GTK4-NoCSD
<img width="766" height="628" alt="Image" src="https://github.com/user-attachments/assets/adb6f8c8-24c5-4edb-b764-ddf73c0a8bc4" />
