### ISSUE TITLE
Creating way too many io ports

### ISSUE THREAD

**Issue by ShayBox** [wwmm/easyeffects#1018]
![image](https://user-images.githubusercontent.com/9505196/125222619-59892a80-e298-11eb-8aa9-950546e95ded.png)

**Comment by wwmm** [comment]
There is an issue but not the one that this image is suggesting. It is not that we are creating too many io ports for a singe filter. almost all of our filters have 2 input and 2 output ports. If I remember well only 2 filters have 4 input ports. What is really happening is that at this moment all `pw_filter`(plugins) created by EasyEffects are kept connected to PipeWire all the time. What your image is showing is actually a combination of all plugins ports.

The current approach is not nice but doing differently is not trivial. The problem is that connecting and disconnecting filters on the fly is way more tricky than I was expecting. In my first attempt to do that so many bugs were introduced that EasyEffects was essentially useless. 

All that being said I still think that plugins hosts should not blindly show everything that is available to the user. Even if I manage to get the on the fly connection/disconnection working if the user decides to enable everything the result will exactly as shown by your image your image. Which program is the one sowing these ports? It definitely should be more selective when showing them.

**Comment by wwmm** [comment]
>The current approach is not nice

When I say that I mean not nice to plugins hosts. A `pw_filter` that is just connected does nothing. No cpu usage and the memory consumption is probably negligible. Only once its ports are connected to another element that is active that filter will do something. So for the vast majority of EasyEffects users the current approach is totally fine. The only issue here is polluting the view of hosts that are blindly showing every single plugin connected to PipeWire.

**Comment by Digitalone1** [comment]
> Which program is the one showing these ports? It definitely should be more selective when showing them.

It should be Carla or one of Cadence application (Catia/Claudia)

**Comment by ShayBox** [comment]
It's `pw-jack catia`

**Comment by Digitalone1** [comment]
Changes in master branch should mitigate this issue. Let's discuss in #1062.

@wwmm This can be closed.

**Comment by wwmm** [comment]
Ok
