### ISSUE TITLE
Echo cancellation overly high-passes the audio

### ISSUE THREAD

**Issue by Volvagia356** [wwmm/easyeffects#1034]
When using the speexdsp based echo cancellation filter, it appears to overly high-pass the audio, completely losing any bass and making everything sound tinny.

When searching around, I found [this email](http://lists.xiph.org/pipermail/speex-dev/2009-December/007566.html) in the speex mailing list where someone else has a similar issue, and they mentioned that it's solved by telling the Speex echo cancellation module the correct sampling rate.

According to the [Speex echo cancellation documentation](https://www.speex.org/docs/api/speex-api-reference/group__SpeexEchoState.html), I would assume this is set using `speex_echo_ctl` with the `SPEEX_ECHO_SET_SAMPLING_RATE` parameter. The default seems to be 8000Hz.

**Comment by wwmm** [comment]
So that is the reason why it is removing low frequencies... As I do not have much experience with echo cancellation I thought it was the way this filter worked. I will update the code. And as its `speex_echo_state_init` function does not have sampling rate as argument I assumed it did not need that information.

I will update the code now.

**Comment by wwmm** [comment]
I updated the master branch now with the call to `speex_echo_ctl`. If you are using Arch Linux please test the new code thought the AUR package.

Another thing I am not sure about is how stereo should be handled with this library. For now I have 2 instance. One for each channel. But maybe this is not what I should be doing.

**Comment by Volvagia356** [comment]
Tried it out via the AUR, and it does fix the high-pass issue. Thanks!
