### ISSUE TITLE
Where should audio be playing?

### ISSUE THREAD

**Issue by Latrolage** [wwmm/easyeffects#1049]
EasyEffects creates, "EasyEffects Source" as a speaker and "EasyEffects Sink" as a microphone. 

Where should audio from the system be going?

My default microphone and speaker are the physicals ones (as normal like before easyeffects were installed) is this right? But changing to the EasyEffects Sink or Source seems to do the same thing.

I changed the application to grab from physical speakers and the easyeffects sink/source and they both did the same thing (i checked with autogain at max to check for differences)

My desktop environment is KDE plasma and i am on pipewire

What should my things be playing to and what should be the default speaker and stuff, i'm getting really confused

**Comment by wwmm** [comment]
>EasyEffects creates, "EasyEffects Source" as a speaker and "EasyEffects Sink" as a microphone.

Which program is showing them this way? In Pavucontrol `EasyEffects Source` is shown only as a input device and `EasyEffects Sin` is shown only in the output device section.

>My default microphone and speaker are the physicals ones (as normal like before easyeffects were installed) is this right? But changing to the EasyEffects Sink or Source seems to do the same thing.

Yes. Ideally you want to keep your hardware devices as default. If you enable `Process All Outputs` in our menu applications like Spotify, mpv, vlc, etc will be automatically moved to our virtual device. A similar thing can be done do apps that record audio if you check the other setting in our menu.

>What should my things be playing to and what should be the default speaker and stuff, i'm getting really confused

In order to apply effects for their output (mpv, vlc, browser on youtube, etc) they have to play to `EasyEffects Sink`. If you want effects for mic the app has to record from our virtual source.

**Comment by Latrolage** [comment]
> Which program is showing them this way? In Pavucontrol `EasyEffects Source` is shown only as a input device and `EasyEffects Sink` is shown only in the output device section.

Yes that's what's shown in KDE plasma's audio widget and pavucontrol, but only when the EasyEffects window is open. Once it's closed, it goes away. Yes the "Run in background" setting IS enabled, not sure if this is intended.

Also does this mean that if a program plays straight to speakers or gets input from physical mic it will bypass all of EasyEffect's effects?

Also about the "Process all inputs" and "Process all outputs" buttons, what happens if for example the application has a setting to specifically grab input or output to a device, for example Element 
![image](https://user-images.githubusercontent.com/67372293/127598351-1431c26b-cdd1-4ab3-ada1-750414781f81.png)
Or if in the KDE plasma audio widget I press the "play all audio via this device" button
![image](https://user-images.githubusercontent.com/67372293/127598433-cc04f765-6d24-4b7f-8721-a5ffdd32e9e7.png)

**Comment by wwmm** [comment]
>Once it's closed, it goes away. Yes the "Run in background" setting IS enabled, but the Sink and Source just disappear once the EasyEffects window is closed, not sure if this is intended.

I have to remember to rename the setting `Run in Background` to something else. In order to keep the effects running when the window is closed you have to start EasyEffects as `easyeffects --gapplication-service`. When start it by clicking on our icon in your desktop launcher this should happen automatically. At least it does on gnome. Because that is the default behavior when launching throught the desktop icon some people asked to have an option to disable this. When `Run in Background` is set to off it does this. I have to find a better name...

>If a program plays straight to speakers or gets input from physical mic it will bypass EasyEffect's effects?

Yes. In order to apply effects the application output/input has to be redirected. There is no other way.

>Also about the "Process all inputs" and "Process all outputs" buttons, what happens if for example the application has a setting to specifically grab input or output to a device, for example Element

EasyEffects will force it to be moved to our virtual device so we can apply effects to it. Otherwise you will have to use the switch besides the app name in our tab with `players` list.

>Or if in the KDE plasma audio widget I press the "play all audio via this device" button

As I do not use KDE I am not sure. If what this does is moving audio streams to the selected device our custom audio routing will be broken for the reasons I explained before. If it is just setting the default device things should be fine.

**Comment by wwmm** [comment]
>EasyEffects will force it to be moved to our virtual device so we can apply effects to it.

If the application allows that. Unfortunately some developers have been misusing Pulseaudio API and denying that.

**Comment by wwmm** [comment]
>If a program plays straight to speakers or gets input from physical mic it will bypass EasyEffect's effects?

If you want all apps to have effects with the exception of one or two you can add these apps to the blocklist. This way you can keep `Process All ***` options enabled so all the other apps are automatically redirected.

**Comment by Latrolage** [comment]
ok, when changing the shortcut to launch with `easyeffects --gapplication-service` it does run in the background, but the GUI does not open unless i run `easyeffects` without the `--gapplication-service` part, which means that I have to either
1. have 2 shortcuts
or 
2. run `easyeffects` through terminal whenever I want to use GUI settings

Is there currently anyway to open the GUI and have it continue in the background with one shortcut?

**Comment by wwmm** [comment]
>the GUI does not open unless i run easyeffects without the --gapplication-service part

That is right. After launching in service mode you run the executable without that option to open the window.

>run easyeffects through terminal whenever I want to use GUI settings

That should not be necessary. Something wrong must be happening in KDE. Clicking on our icon in your application launch should be enough to put the app in service mode if it is not like this already as well as showing the window.

In our settings menu there is an option called `Start Service at Login`. Is it working in KDE? when this setting is enabled EasyEffects should autostart already in service mode.

**Comment by Latrolage** [comment]
Yeah it's in the startup menu and starts at startup, I just hadn't logged out and back in yet.
