### ISSUE TITLE
[Feature Request] Close to background option

### ISSUE THREAD

**Issue by Netherquark** [wwmm/easyeffects#1053]
On Linux, you can close apps and they still keep running and are available to quickly open from the title bar like this:
![image](https://user-images.githubusercontent.com/65618735/127532823-2ccae4f1-3d6d-4898-a7cd-6b186a616cf8.png)

I was wondering if you could offer that as an option with EasyEffects. I have a potato laptop (Acer One 14 with AMD A6-7310) and it struggles to open Task View in Ubuntu. This makes it super hard to open EasyEffects every time i want to make a small change to the profile. Just as a creature comfort. I know I could probably set up a macro or something to open easyeffects, which is one of the great things about Linux, but I feel this would be a much better option in the long term. Just an idea. Apart from that, I find this project to be incredible, and miles ahead in terms of intutiveness compared to anything else like EqualiserAPO. Kudos on the good work. Also, thanks in advance.

**Comment by Netherquark** [comment]
never mind then

**Comment by Slapbox** [comment]
@wwmm what does **Start Service at Login** do? I expected that to basically achieve this end.

**Comment by wwmm** [comment]
I have to choose a better name for this option because the one used right now is misleading. In order to keep the app running in the background after closing its window you have to start it as `easyeffects --gapplication-service` as I explained before. This should happen by default when start it by clicking on our desktop icon in you app launcher. At least on GNOME this works.

For some reason some users do not like this default behavior and wanted an option to make the app to be actually finished once its window was closed even if starting it through the desktop launcher. That is what `Start Service at Login` does. If you disable it the app is totally finished even if it was started it with `--gapplication-service`. I have to find a better name for it. I am not sure what yet.

**Comment by wwmm** [comment]
Ops... I read one thing but understood another...

**Comment by wwmm** [comment]
`Start Service at Login` creates an autostart file inside `~/.config/autostart/`. In your next login EasyEffects should autostart already in service mode. At least on Gnome this works.

**Comment by Slapbox** [comment]
Ahhh no dice here with Kubuntu 21.04.

I do have a `pulseeffects-service.desktop` in that directory from when I was using PulseAudio, although I don't know if that actually ran at startup either. Other applications with `.desktop` files in that directory do start up as expected though.

**Comment by vchernin** [comment]
> Ahhh no dice here with Kubuntu 21.04.

Are you by any chance using the Flatpak? That currently requires a workaround for `Start Service at Login`.
