### ISSUE TITLE
EasyEffects not loading in discover

### ISSUE THREAD

**Issue by ElliottDyson** [wwmm/easyeffects#1099]
Hello, I've been wanting to upgrade to easyeffects due to pipewire compatability for a while now (and I do not have enough technical knowledge to build from source), I was wondering if the link in the discover package manager could be fixed at all, or if there is another package manager or automated install that I can use to get easyeffects installed?

Many thanks,
Elliott Dyson
![image](https://user-images.githubusercontent.com/83019499/129413917-e7a7677e-1e6f-41b8-9ef0-43978488c1aa.png)

**Comment by vchernin** [comment]
Could you elaborate on what the "link" in discover is? I am not quite sure what you mean.

**Comment by ElliottDyson** [comment]
> Could you elaborate on what the "link" in discover is? I am not quite sure what you mean.
> 
> The most supported way is currently to use the Arch package. There is also a work in progress Flatpak and Fedora COPR repo.

Yeah, I replied in the GitHub for the flatpak version, since I couldn't get that one to work I thought I'd try this method instead. It makes sense that it isn't showing up properly now, I'm using manjaro. Sorry about that

**Comment by vchernin** [comment]
> Yeah, I replied in the GitHub for the flatpak version, since I couldn't get that one to work I thought I'd try this method instead. It makes sense that it isn't showing up properly now, I'm using manjaro. Sorry about that

Ah yeah, [now I remember you from the other thread](https://github.com/flathub/flathub/pull/2429#issuecomment-894643310).

I'm still not exactly sure what the issue is here. Is there something in that screenshot I should pay attention to?

The Flatpak should display properly in Discover once you've installed (ignoring the screenshots, they are broken with Flathub test builds, nothing to do with EasyEffects). Once the Flatpak is released onto Flathub it should appear in Discover even if you haven't installed it (assuming you have the Flathub repo locally).

Both the Flatpak and Arch package _should_ work on arch/manjaro (but I haven't tested manjaro). Are you still on the raspberry pi?

I think manjaro and arch Discover should behave similarly? I will test out Discover in my arch kde VM.

**Comment by ElliottDyson** [comment]
> > Yeah, I replied in the GitHub for the flatpak version, since I couldn't get that one to work I thought I'd try this method instead. It makes sense that it isn't showing up properly now, I'm using manjaro. Sorry about that
> 
> Ah yeah, [now I remember you from the other thread](https://github.com/flathub/flathub/pull/2429#issuecomment-894643310).
> 
> I'm still not exactly sure what the issue is here. Is there something in that screenshot I should pay attention to?
> 
> The Flatpak test build should display properly in Discover once you've installed it (ignoring the screenshots, they are broken with Flathub test builds, nothing to do with EasyEffects). Once the Flatpak is released onto Flathub it should appear in Discover even if you haven't installed it (assuming you have the Flathub repo locally).
> 
> Both the Flatpak and Arch package _should_ work on arch/manjaro (but I haven't tested manjaro). Are you still on the raspberry pi?
> 
> I think manjaro and arch Discover should behave similarly? I will test out Discover in my arch kde VM.

Yep, still on the raspberry pi.

What I mean by not loading, is that other applications say "install" or "install from flatpak" for example, whereas EasyEffects just shows "Loading..." and then doesn't change from that, as seen in my screenshot. Could it be that it isn't entered into the repositories entirely correctly so discover is struggling to find the arm edition of it? As I said, not really too technically minded in Linux, I just thought I'd bring it up since fixing it might help others than just myself, especially since install from source is so involved.

**Comment by vchernin** [comment]
> What I mean by not loading, is that other applications say "install" or "install from flatpak" for example, whereas EasyEffects just shows "Loading..." and then doesn't change from that, as seen in my screenshot. Could it be that it isn't entered into the repositories entirely correctly so discover is struggling to find the arm edition of it? As I said, not really too technically minded in Linux, I just thought I'd bring it up since fixing it might help others than just myself, especially since install from source is so involved.

This sounds like there's Discover bug, and nothing we can fix in Flatpak or in EasyEffects.

Especially since it's partially loaded, there's no reason why it shouldn't be able to finish. Software should error out instead of leaving users with ambigouty.

That said, perhaps this is caused if have an older Flathub easyeffects test build on your system?
Could you try to remove easyeffects Flatpak from your system with
`flatpak remove com.github.wwmm.easyeffects`
(Remove anything if prompted, if it says it couldn't find anything easyeffects flatpak wasn't installed).

If the issue still occurs though (and you can consistently reproduce it) please do report it [to KDE](https://bugs.kde.org/). 

Speaking of command line..

On Manjaro could you try
`sudo pacman -S easyeffects` to get the Arch package? I think manjaro has other GUI package mangers (Pamac?).
I don't think Arch packages show up in Discover on Arch (or GNOME Software for that matter), so the same might be true for Manjaro.

**Comment by ElliottDyson** [comment]
> > What I mean by not loading, is that other applications say "install" or "install from flatpak" for example, whereas EasyEffects just shows "Loading..." and then doesn't change from that, as seen in my screenshot. Could it be that it isn't entered into the repositories entirely correctly so discover is struggling to find the arm edition of it? As I said, not really too technically minded in Linux, I just thought I'd bring it up since fixing it might help others than just myself, especially since install from source is so involved.
> 
> This sounds like there's a Discover bug, and nothing we can fix in Flatpak or in EasyEffects.
> 
> Especially since it's partially loaded, there's no reason why it shouldn't be able to finish. Software should error out instead of leaving users with ambiguity.
> 
> That said, perhaps this is caused if you have an older Flathub easyeffects test build on your system?
> Could you try to remove easyeffects Flatpak from your system with
> `flatpak remove com.github.wwmm.easyeffects`
> (Remove anything if prompted, if it says it couldn't find anything easyeffects flatpak wasn't installed).
> 
> If the issue still occurs though (and you can consistently reproduce it) please do report it [to KDE](https://bugs.kde.org/). 
> 
> If you still want the Arch EasyEffects package though...
> 
> On Manjaro could you try
> `sudo pacman -S easyeffects` to get the Arch package? I think manjaro also has other GUI package mangers instead of Discover (Pamac?).
> I don't think Arch packages show up in Discover on Arch (or GNOME Software for that matter), so the same might be true for Manjaro.

Didn't realise I can get the arch package that easily on a different distro such as Manjaro, I'll give it a go tomorrow. Thank you! As for it not working due to left over packages, that couldn't be possible, it's been completely formatted since the last install, good suggestion though

**Comment by wwmm** [comment]
>Didn't realise I can get the arch package that easily on a different distro such as Manjaro

It used to be that easy on Antergos because it used the same repositories as Arch Linux. I think Manjaro has its own repository. In that case someone would have to be making EasyEffects packages for it. What should not be hard if Manjaro is not taking too long to update its repositories when compared to Arch.

IF all goes wrong you could try to install from Arch AUR package https://aur.archlinux.org/packages/easyeffects-git/. The disadvantage is that it builds from our development branch. So there is the usual risk of getting something that is still more unstable than we would like.

**Comment by vchernin** [comment]
> It used to be that easy on Antergos because it used the same repositories as Arch Linux. I think Manjaro has its own repository. In that case someone would have to be making EasyEffects packages for it. What should not be hard if Manjaro is not taking too long to update its repositories when compared to Arch.

I do think Manjaro has it's own repos, but IIRC they are primarly just a delayed fork of Arch's (maybe with some changes here and there). So I'd assume eventually Arch's easyeffects package will make it there. I tried to find confirmation of this, but it doens't look [like easyeffects is in Manjaro's repos yet](https://discover.manjaro.org/packages/). So I'm not sure really.

Also, I am not even sure if anyone has even compiled the Arch package for aarch64 yet :( [There wasn't anything on Arch Linux ARM](https://archlinuxarm.org/packages).

> If all goes wrong you could try to install from Arch AUR package https://aur.archlinux.org/packages/easyeffects-git/. The disadvantage is that it builds from our development branch.

Couldn't you also just build the easyeffects Arch package (not from AUR).
For @ElliottDyson:
```
git clone https://github.com/archlinux/svntogit-community --branch packages/easyeffects --single-branch
cd svntogit-community/trunk
makepkg -si
# agree to whatever dependencies wanted
```

If that doesn't work you could also try the Flatpak again, I think it should work on Manjaro ARM? (Remember you need to explictly also install and use PipeWire).

**Comment by wwmm** [comment]
>Couldn't you also just build the easyeffects Arch package

I forgot about that. It is something to consider too.

**Comment by AlexFolland** [comment]
I'm also a Manjaro user, and I recommend using the "unstable" branch.  It sounds bad, but it's just the branch that is in closest parity with Arch repositories, and I've found it actually has the fewest issues over my last year, gradually switching from stable, to testing, and finally to unstable.  "Unstable" has allowed me to get the latest fixes that work together with each other, which is especially important for emerging software like PipeWire.

**Comment by vchernin** [comment]
I wonder how much benefit there is of using Manjaro unstable over Arch stable. Especially now that there is `archinstall`.

But this is another topic though :)
