### ISSUE TITLE
Equalizer sliders shift as number of digits changes

### ISSUE THREAD

**Issue by Tooniis** [wwmm/easyeffects#1114]
As the number of digits below the slider change, the other sliders shift sideways:

https://user-images.githubusercontent.com/36982494/130414038-a1ba5b55-3656-4f93-ad1c-f5275d8b238d.mp4

Maybe it could be fixed with some padding?

**Comment by Digitalone1** [comment]
This is a GTK4 issue. As I remember, this was not happening in PulseEffects with GTK3.

The problem is GTK does not give any chance to modify the label near the slider. So even with padding, it will shift.

A workaround could be setting the slider to not show the value and inserting a new label binded with band gain. But it's too much work to do, considering that it should be done also for input/output horizontal sliders that have to value too near to the bar and some margin should be set, but GTK4 does not give this option.
