### ISSUE TITLE
I received this message while updating my flatpaks

### ISSUE THREAD

**Issue by isa-pp** [wwmm/easyeffects#1116]
`The GNOME 3.38 runtime is no longer supported as of August 19, 2021. Please ask your application developer to migrate to a supported platform.
Aplicativos que usam este runtime:
   com.github.wwmm.pulseeffects`
Thought I should warn you here

**Comment by wwmm** [comment]
@vchernin is this something that can be easily fixed?

**Comment by vchernin** [comment]
I quickly tried doing it [here](https://github.com/flathub/com.github.wwmm.pulseeffects/pull/56), lets see what happens.

I'll close this issue here, thanks for notifying.

I do recall seeing discussion that the EOL date might be pushed back, but we might as well update to the latest runtime anyway.

**Comment by vchernin** [comment]
Oh wait, I can't close issues here, I forgot what repo I was in :D

**Comment by wwmm** [comment]
>Oh wait, I can't close issues here, I forgot what repo I was in :D

Hahaha! Ok. As you are already updating the package to the new runtime I will close this issue.

**Comment by vchernin** [comment]
@isa-pp you should be able to `flatpak update` in 3-5 hours and the issue will be gone, [the fix was merged](url).
