### ISSUE TITLE
OBS icon is not shown in the app list

### ISSUE THREAD

**Issue by wwmm** [wwmm/easyeffects#1143]
@Digitalone1  I am trying to use OBS today and I noticed we have no icon for it while the app provides an icon in its package. So far I see two problems

- The icon is installed. But for some reason the PipeWire property I usually use for this does not have the icon name. But GNOME can load it with no problems. I am not sure how yet.
- Hiding the icon just because the icon theme does not have it. In the logs I see `effects_base_ui: obs icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.`

After what I am seeing with OBS assuming that icon themes must have the icon for us to show it is not a good idea. We should be able to show OBS icon outside of Flatpak even if the icon theme does not have it because the OBS package is installing the icon. Unless something out of the ordinary has to be done to load this icon. Then it may not be worth the effort. But I still think that we should be able to show icons inside `/usr/share/icons/hicolor/256x256/apps/` or similar paths. It is strange they do not seem to be working.

**Comment by wwmm** [comment]
Same thing happens to Chromium. I think that icons inside `hicolor/*/apps` must need some kind of special handling...

**Comment by Digitalone1** [comment]
So icon theme is looking only for icons in its folder, not others installed under hicolor or pixmaps.

I didn't want to use this icon theme method, but unfortunately there's no way to detect if an icon is really shown. Glib is full of different methods, some useless, but there's no function to solve this issue, so once you give the widget an icon name, there no way to know if it's shown correctly or the broken icon appears.

I hoped the icon theme object would search also in hicolor and pixmap, but it's limited only to the specified theme.

That said, the last chance we have it's to try to add hicolor and pixmap path as resource to icon theme object and hope it will detect other icons, otherwise we have to return to the original method: let's show always the icon, give it the name, if the icon is installed, the user sees it, otherwise the broken icon appears (and papirus/kora would be the only option for flatpak to not see the broken icon).

Try to add another resource like done here:

https://github.com/wwmm/easyeffects/blob/c70d1feab0a88d133e6ee6916bb7be9abb8d9782/src/application_ui.cpp#L124

As stated in the [specification](https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html#directory_layout), the folders would be 

```
/usr/share/pixmaps
/usr/share/icons/hicolor
```

If it's not working, try also [this](https://developer-old.gnome.org/gtkmm/stable/classGtk_1_1IconTheme.html#a06fbe6e5556cc1fc36c73394c4694ae8).

**Comment by wwmm** [comment]
>That said, the last chance we have it's to try to add hicolor and pixmap path as resource to icon theme object and hope it will detect other icons, otherwise we have to return to the original method: let's show always the icon, give it the name, if the icon is installed, the user sees it, otherwise the broken icon appears (and papirus/kora would be the only option for flatpak to not see the broken icon).

I thought about something like that.  This weekend I will try to take a look at this.

**Comment by Digitalone1** [comment]
<div class="memproto">

void Gtk::IconTheme::set_resource_path | ( | const std::vector< std::string > & | path | ) |  
-- | -- | -- | -- | -- | --

</div><div class="memdoc">

<p>Sets the resource paths that will be looked at when looking for icons, similar to search paths. </p>
<p>The resources are considered as part of the hicolor icon theme and 
must be located in subdirectories that are defined in the hicolor icon 
theme, such as <code>@a path/16x16/actions/run.png</code> or <code>@a path/scalable/actions/run.svg</code>.</p>
<p>Icons that are directly placed in the resource path instead of a 
subdirectory are also considered as ultimate fallback, but they are 
treated like unthemed icons.</p></div>

___

I don't understand this part clearly. The icon theme can retrieve icons in `hicolor` folder as ultimate fallback, but if they are set in one of the subfolder, they can't be retrieved. That's weird. So we should specify any possible subfolder inside hicolor.

Maybe it's better to use [add_search_path](https://developer-old.gnome.org/gtkmm/stable/classGtk_1_1IconTheme.html#a06fbe6e5556cc1fc36c73394c4694ae8), but I'm afrai this works the same as above, it will look only in the directory and not the subfolder.

___

<div class="memproto">

void Gtk::IconTheme::set_search_path | ( | const std::vector< std::string > & | path | ) |  
-- | -- | -- | -- | -- | --



</div><div class="memdoc">

<p>Sets the search path for the icon theme object. </p>
<p>When looking for an icon theme, GTK will search for a subdirectory of one or more of the directories in <em>path</em>
 with the same name as the icon theme containing an index.theme file. 
(Themes from multiple of the path elements are combined to allow themes 
to be extended by adding icons in the user’s home directory.)</p>
<p>In addition if an icon found isn’t found either in the current icon 
theme or the default icon theme, and an image file with the right name 
is found directly in one of the elements of <em>path</em>, then that 
image will be used for the icon name. (This is legacy feature, and new 
icons should be put into the fallback icon theme, which is called 
hicolor, rather than directly on the icon path.)</p></div>

**Comment by Digitalone1** [comment]
I'm afraid we should rollback at the original method and suggest the user to install a complete icon theme. Otherwise the broken icon can't be avoided and Glib doesn't provide a reliable method to detect and hide it.

**Comment by wwmm** [comment]
>I don't understand this part clearly.

I am also confused. But I agree that it does not look like it does recursive searches.

>I'm afraid we should rollback at the original method and suggest the user to install a complete icon theme.

I agree. If in the end we will have to add custom paths anyway we could instead improve the old method to handle some corner cases in a better way. I had to do something like that for the Firefox icon to be shown in the old method https://github.com/wwmm/easyeffects/blob/c70d1feab0a88d133e6ee6916bb7be9abb8d9782/src/effects_base_ui.cpp#L1437. OBS may be needing something similar.

**Comment by Digitalone1** [comment]
When I have time I'd like to test and print on the log the search paths given by `get_search_path()`, just to know where this object is looking the icons.

At last resort, we could try to add the missing paths iterating with filesystem functions inside hicolor and pixmaps folders.

**Comment by Digitalone1** [comment]
These are the paths printed by the function

```
~/.local/share/icons
~/.icons
/usr/local/share/icons
/usr/share/icons
/usr/local/share/pixmaps
/usr/share/pixmaps
```

There's no hicolor folder, but I notice that setting Adwaita I can see celluloid and mpv icons which are located at 

```
usr/share/icons/hicolor/scalable/apps/mpv.svg`
usr/share/icons/hicolor/scalable/apps/io.github.celluloid_player.Celluloid.svg
```

So the icon object can look under that folder, but I see also that obs-studio from upstream Arch repository has the icon placed under the same location.

```
usr/share/icons/hicolor/256x256/apps/com.obsproject.Studio.png
```

@wwmm can you please report here the app name set in the NodeInfo structure?

**Comment by wwmm** [comment]
>can you please report here the app name set in the NodeInfo structure?

I did a test now and the output of `PW_KEY_APP_ICON_NAME` that is saved in our node info property `app_icon_name` has the value `obs`. What obviously isn't the name of icon file. I wonder who is at  fault here. If it is PipeWire or OBS. But it seems more likely that OBS isn't setting the icon name and PipeWire is defaulting to the app name.

In any case it isn't enough to run `app_icon->set_from_icon_name("com.obsproject.Studio");` to show the icon. So the path is still a problem =/

**Comment by wwmm** [comment]
For reference this is the `pw-cli info` output for OBS
```
	id: 120
	permissions: rwxm
	type: PipeWire:Interface:Node/3
*	input ports: 2/64
*	output ports: 2/0
*	state: "suspended"
*	properties:
*		client.api = "pipewire-pulse"
*		pulse.server.type = "unix"
*		application.name = "OBS"
*		application.icon-name = "obs"
*		media.role = "Production"
*		application.process.id = "6754"
*		application.process.user = "wallace"
*		application.process.host = "wwmm"
*		application.process.binary = "obs"
*		application.language = "en_US.UTF-8"
*		window.x11.display = ":0"
*		application.process.machine-id = "b3d293e2d17b4948b715903eea76b85f"
*		media.name = "Mic/Aux"
*		node.rate = "1/44100"
*		node.target = "easyeffects_source"
*		stream.is-live = "true"
*		node.name = "OBS"
*		node.autoconnect = "true"
*		media.class = "Stream/Input/Audio"
*		adapt.follower.node = ""
*		object.register = "false"
*		factory.id = "6"
*		audio.adapt.follower = ""
*		factory.mode = "merge"
*		library.name = "audioconvert/libspa-audioconvert"
*		client.id = "123"
*		object.id = "120"
*		node.latency = "1102/44100"
*		pulse.attr.maxlength = "4194304"
*		pulse.attr.fragsize = "8816"
*	params: (8)
*	  3 (Spa:Enum:ParamId:EnumFormat) r-
*	  1 (Spa:Enum:ParamId:PropInfo) r-
*	  2 (Spa:Enum:ParamId:Props) rw
*	  4 (Spa:Enum:ParamId:Format) rw
*	  10 (Spa:Enum:ParamId:EnumPortConfig) r-
*	  11 (Spa:Enum:ParamId:PortConfig) rw
*	  15 (Spa:Enum:ParamId:Latency) -w
*	  16 (Spa:Enum:ParamId:ProcessLatency) rw
```

**Comment by wwmm** [comment]
And to my surprise setting `icon_theme->add_search_path("/usr/share/icons/hicolor/256x256/apps/");` was not enough to make it work...

**Comment by wwmm** [comment]
It works. I forgot to comment out one of the `app_icon->set_from_icon_name` in the code that checks if the theme has the icon. Let me see if there are other combinations that also fixes the problem.

**Comment by Digitalone1** [comment]
> In any case it isn't enough to run `app_icon->set_from_icon_name("com.obsproject.Studio");` to show the icon. So the path is still a problem =/

So the problem here is the Image widget, not the icon them object. Indeed the icon theme is saving us not showing the broken image in this case.

**Comment by Digitalone1** [comment]
> It works. I forgot to comment out one of the `app_icon->set_from_icon_name` in the code that checks if the theme has the icon. Let me see if there are other combinations that also fixes the problem.

Okay, good to know. So we have to do a specific workaround for obs.

**Comment by wwmm** [comment]
Using the old code it is enough to do the following to have the OBS icon showing
```
if (holder->info.app_icon_name == "obs") {
        app_icon->set_from_icon_name("com.obsproject.Studio");
}
```

No need to add custom icon paths. The problem was just the wrong icon name being passed by OBS to PipeWire
![Screenshot from 2021-09-13 11-55-37](https://user-images.githubusercontent.com/16225172/133107035-f435bcc5-7bbb-42a7-9777-abca15864d78.png)

**Comment by wwmm** [comment]
The question now is if we integrate this in the current code that is checking if the icon theme has the icon or if we stop trying to rely on the icon theme for that. I am not sure.

**Comment by wwmm** [comment]
I think that Chromium has a similar problem. Just like Firefox and OBS it needs custom handling =/

**Comment by Digitalone1** [comment]
Tomorrow I can work on it and find a solution. 

Why Chromium? I never had problem with it. Did you try also Google Chrome?

**Comment by wwmm** [comment]
>Why Chromium? 

Sometimes I see the broken icon for it too when giving classes on MS Teams. Let me to some tests.

**Comment by wwmm** [comment]
The current code prints the warning message for Chromium and hides the icon 
```
effects_base_ui: chromium-browser icon name not installed in the Adwaita icon theme in use. The application icon has been hidden.
```

**Comment by wwmm** [comment]
I am not using custom icon themes. I have Adwaita installed. What most GNOME users will have. That is why I think that relying on the icon theme object is not looking a good default solution.

**Comment by wwmm** [comment]
In any case I remember that icon not working in the past. Chromium probably needs to have the proper icon name set manually like OBS.

**Comment by Digitalone1** [comment]
> I am not using custom icon themes. I have Adwaita installed. What most GNOME users will have. That is why I think that relying on the icon theme object is not looking a good default solution.

Why? The problem is Pipewire giving the wrong name, not the icon theme object to check if the name is available as icon.

**Comment by wwmm** [comment]
>The problem is Pipewire giving the wrong name, not the icon theme object to check if the name is available as icon.

Oh! I see. So the check would work with the right icon name. I did not test with OBS. It makes sense. THen setting the right name should be enough. Ok.

**Comment by Digitalone1** [comment]
Tomorrow I'm working on it and find a solution. I think we need a map to get the right icon for the given app name.
