### ISSUE TITLE
Suggestion: More complete command-line options

### ISSUE THREAD

**Issue by mikenrafter** [wwmm/easyeffects#1146]
Having the ability to change settings using a command-line API of sorts would be extremely useful.  
I use a window-manager, and because of this I'd have the ability to easily map hotkeys to various actions within easyeffects.

One example, would be if I thought my auto-gain too quiet, then I could press a few keys, and it'd turn up 1.0dB. Problem solved.

Aside from that, this program's basically feature-complete.

**Comment by wwmm** [comment]
Take a look at https://github.com/wwmm/easyeffects/discussions/916. There are ways to set our keys from scripts or command line. It is way more flexible than command line options. And a better match to the huge amount of options we currently have.

**Comment by mikenrafter** [comment]
Yes, that will do. Though, gsettings aren't exactly all that intuitive. Having an API, or at least overlay to the gsettings definitely would make things nicer.

**Comment by wwmm** [comment]
>Though, gsettings aren't exactly all that intuitive. Having an API, or at least overlay to the gsettings definitely would make things nicer.

While I agree that gsettings API is not straightforward in some places trying to expose all of our settings through command line options would require a huge amount of work. As well as a maintenance burden because whenever a key is added, removed or changed in a plugin things will have to be updated accordingly on the command line side. I doubt it will ever happen.

**Comment by mikenrafter** [comment]
Alright, I see. Perhaps I could concoct and maintain something script-ish that'd act as an API-intermediary to gsettings. I'll update this issue if/when I get around to devving this.
