### ISSUE TITLE
weird micro deactivation

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#1175]
theres a weird bug that i cant reproduce when any program is recording the processed signal, when im listening music in audacious and pause/Playing a video in firefox the easyeffects processing is disabled for a very short time (each time i pause and resume the video)

**Comment by MalexTP** [comment]
debug mode doesnt show anything, dont know what causes it

**Comment by wwmm** [comment]
It may be related to the dynamic latency changes done by PipeWire. Kill the current instance `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects`. There should be many lines in the output.

**Comment by MalexTP** [comment]
> `G_MESSAGES_DEBUG=easyeffects easyeffects`

yess, i didnt noticed about that debug was throwing "pipewire latency" each time i paused and resumed it
https://bin.cyberdrop.me/#r4yfoFcqa6m6cQuteZc2Iw

so it isnt a bug? i think its only being updated after a change

**Comment by MalexTP** [comment]
i changed my irs file to a default 44.1khz file and it still happens, so resampling isnt the problem(?

**Comment by wwmm** [comment]
>i changed my irs file to a default 44.1khz file and it still happens, so resampling isnt the problem(?

Probably not. Specially because the resampling you are seeing is just the one done to the impulse file. It won't cause what you are listening to. Based on your logs PipeWire is going from low latency to high latency
```
soe: output_level: new PipeWire blocksize: 2048
soe: output_level: new PipeWire blocksize: 8192
```
When going from high to low some loss of data happens when we reinitialize our filter with the new audio buffer size. The question is where is the problem when going from low to high. If you disable all the filters there is still a problem? If yes the issue may be on the virtual sink we ask PipeWire to create for us. EasyEffects just passthrough data when no filters are added to our filter litst

**Comment by bhack** [comment]
I suppose that we are quite in the same case as https://github.com/wwmm/easyeffects/issues/1213

**Comment by bhack** [comment]
We could have a potential solution to test at #1023 (comment)

**Comment by bhack** [comment]
Can we close this?

**Comment by wwmm** [comment]
At least for LV2 plugins the problem should be fixed.
