### ISSUE TITLE
Incompatibility with Soundux

### ISSUE THREAD

**Issue by fischer-felix** [wwmm/easyeffects#1197]
### EasyEffects Version

6.1.3

### What package are you using?

Arch Official (easyeffects)

### Distribution

Manjaro 21.1.5

### Describe the bug

When having EasyEffects active and trying to use soundux https://github.com/Soundux/Soundux It does not play on the recording side

### Expected Behavior

audio plays

**Comment by wwmm** [comment]
I installed soundux but I did not really understand what this app is supposed to do. Nothing was shown in its output applications menu even with some audio applications active. So I decided to take a look at its source code. It seems to me that like easyeffects it tries to redirect applications to its virtual devices. In that case soundux and easyeffects will conflict. You can't have more than one audio manager trying to redirect applications input/output. It would be like trying to run PulseEffects and EasyEffects at the same time. They will conflict because they are trying to do the same thing.

**Comment by Digitalone1** [comment]
Maybe we should also add Soundux in our blocklist.

**Comment by wwmm** [comment]
>Maybe we should also add Soundux in our blocklist.

Maybe. But if it is really an audio manager like easyeffects it won't help. They will still conflict with each other and there is nothing that can be done about this.

**Comment by fischer-felix** [comment]
It's not an audio Manager, but a soundboard, the soundux guys said it should work with pipewire, but haven't gotten around to testing it further

**Comment by wwmm** [comment]
>but a soundboard

And what does a soundboard do? If it has to redirect applications input or output to a virtual device like EasyEffects does they will conflict.

**Comment by wwmm** [comment]
>You can play sounds from a selection to recording applications like discord, zoom, etc.,

In order to do that Soundux will have to redirect these applications input to its virtual source or its virtual sink monitors. IF you enable effects for microphone in EasyEffects they will conflict. If have no need for microphone effects in easyEffects disable in our setting menu the option `Process All Inputs` and make sure that in the `Players tab` of our `Input` section all apps have their effects switch disabled. You can try to add them to the input effects blocklist too. It should have the same effect.
