### ISSUE TITLE
Delay auto startup

### ISSUE THREAD

**Issue by Wunderharke** [wwmm/easyeffects#1234]
I'm not sure if that is the right place to ask but I found no documentation on.desktop files.
I am using Fedora 35 with KDE and EasyEffects via Flatpak.
I modified my soundcard with HDAJacksRetask which results in a delayed startup of my driver.

EasyEffects seems to struggle with this as it doesn't connect automatically with the soundcard anymore which is probably because it's starting fist. After closing all EasyEffects instanced and restarting EasyEffects everything works as expected.

Is there any way to delay the start of EasyEffects until the sound output has been enabled?

**Comment by vchernin** [comment]
Since you're on Kde you can delay autostart by modifying the exec like in the autostart file. Modify the exec line of `~/.config/autostart/com.github.wwmm.easyeffects` and add a few seconds of `sleep` as described [here](https://www.linuxuprising.com/2020/11/how-to-launch-startup-applications-with.html) (only the kde instructions).
So change the contents of `Exec` line to `bash -c "sleep <xx> && <original_command>"`

**Comment by Wunderharke** [comment]
Ah thanks for your quick help! I will just test what is a good delay.

**Comment by vchernin** [comment]
One thing I realized is EasyEffects might try to overwrite your modified file with the default one. If that is a problem revoke EasyEffects' permission to modify that file with `flatpak permission-reset com.github.wwmm.easyeffects`
