### ISSUE TITLE
Audio become stutter when play 2 audio source together

### ISSUE THREAD

**Issue by vuongtuha** [wwmm/easyeffects#1292]
### EasyEffects Version

6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 21.10

### Describe the bug

Your application is perfect with audio quality and latency. I think my prob is from config system that I dont know how to change.
If I play Spotify (native app) audio still run normal. If I play video youtube on Chrome/VLC every sound still be ok. But if I try to play this 2 source at the same time, both of audio become crack and stutter.
I tried to find where is buffer but as I know Ubuntu cant fully remove PulseAudio and replace by Pipewire. I'm running PulseAudio (on PipeWire 0.3.40). My system is not super power but I see Easyeffect only use 2% cpu at peak time. I change nice of Easyeffect to -19 but prob still there.
Sry that I dont know enough word about audiophile. Hope anyone can guide me get the rid of this annoying. Tysm!

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>But if I try to play this 2 source at the same time, both of audio become crack and stutter.

Does this happens for a short period of time or does it stay this way while both audio players are active? If it is only for a short period you could try as a workaround to force PipeWire to use a fixed latency instead of dynamically changing it https://github.com/wwmm/easyeffects/issues/1290#issuecomment-992976224

**Comment by vuongtuha** [comment]
Is clock.force.quantum regard as buffer size in Pulseeffect? My problem solve by 
`pw-metadata -n settings 0 clock.force-quantum 4096`
I can't imagine that's too simple =)) Thank u!

**Comment by wwmm** [comment]
>Is clock.force.quantum regard as buffer size in Pulseeffect?

Yes the command you used is forcing PipeWire to use a fixed buffer size (and as a result a fixed latency too) instead of dynamically changing it. Things will be better in our next release for most of our plugins. The convolver plugin will probably be the only one still needing this workaround once the next release is ready. 

>My problem solve by pw-metadata -n settings 0 clock.force-quantum 8192

Have in mind that PipeWire's latency may be a little high when the quantum is set to `8192`. If possible try to use a smaller value or force a constant quantum only when you really need. As I said before depending on which plugins you use this workaround won't be needed in the next EasyEffects release.
