### ISSUE TITLE
Some Icons on GUI not visible Ubuntu 20.04.3

### ISSUE THREAD

**Issue by HirogaKatageri** [wwmm/easyeffects#1294]
### EasyEffects Version

EasyEffect 6.1.5

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 20.04.3 LTS

### Describe the bug

![image](https://user-images.githubusercontent.com/8166484/146154763-a59177b3-12ea-4494-b968-03dcc5fb88c2.png)

Some of the Icons in GUI are having errors. I've installed this via Flatpak.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
You have PipeWire 0.3.40 installed
This is newer or the same as PipeWire 0.3.31 required to run EasyEffects
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate
libEGL warning: DRI3: Screen seems not DRI3 capable
libEGL warning: DRI2: failed to authenticate

(easyeffects:2): easyeffects-WARNING **: 16:56:33.160: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 16:56:33.160: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 16:56:33.160: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 16:56:33.160: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 16:56:33.491: lv2_wrapper: Could not find the plugin: http://drobilla.net/plugins/mda/Loudness

(easyeffects:2): easyeffects-WARNING **: 16:56:33.491: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: loudness

(easyeffects:2): easyeffects-WARNING **: 16:56:33.491: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: output

(easyeffects:2): easyeffects-WARNING **: 16:56:33.491: lv2_wrapper: http://drobilla.net/plugins/mda/Loudness port symbol not found: link

(easyeffects:2): easyeffects-WARNING **: 16:56:34.124: portal: background request failed:Background request canceled

```
</details>

**Comment by wwmm** [comment]
Here we go again @Digitalone1 @vchernin :smile:. That is on the last stable release that has workaround for icon problems in place. @HirogaKatageri are you able to see which icon themes do you have installed?

**Comment by HirogaKatageri** [comment]
Oh crap is it my fault? :laughing: I kinda customized my stuff. I didn't know icon themes could have an effect. I was searching the previous issues for broken icons and stuff I may have missed it.

Here's my current:
Adwaita               breeze_cursors  default    gnome      HighContrast   locolor     ubuntu-mono-dark   Yaru
breeze                breeze-dark     DMZ-Black  handhelds  Humanity       LoginIcons  ubuntu-mono-light
Breeze-Adapta-Cursor  Breeze_Snow     DMZ-White  hicolor    Humanity-Dark  redglass    whiteglass

**Comment by vchernin** [comment]
Are you using default gnome on Ubuntu 20.04? Or since you've customized the themes I guess it's not really default anymore.

Do you have xdg-desktop-portal-gtk installed? That is necessary to ensure these theme settings are passed correctly.  

Indeed the next update should be better at avoiding these icon theme issues.

**Comment by wwmm** [comment]
>Indeed the next update should be better at avoiding these icon theme issues.

Some of these issues. I did not embed in our executable common icons like the ones for speakers and microphones. I assumed that any icon theme would have these kind of icons nowadays.

**Comment by wwmm** [comment]
The Breeze icon theme should have at least the icons for speakers and microphones. Something may be broken or missing somewhere in your installation.

**Comment by HirogaKatageri** [comment]
> Are you using default gnome on Ubuntu 20.04? Or since you've customized the themes I guess it's not really default anymore.
> 
> Did you customize both gtk and icon themes or just icon themes?
> 
> Do you have xdg-desktop-portal-gtk installed? That is necessary to ensure these theme settings are passed correctly.
> 
> Indeed the next update should be better at avoiding these icon theme issues.

Yep I've got it installed, I only customized the Icon Themes, via Gnome Tweaks

**Comment by vchernin** [comment]
Well EasyEffects Flatpak should be able to use your icon theme from your host. 

Do other GTK apps have problems? Can you try `pulseeffects` from apt to rule out a Flatpak problem (I believe some icons are similar).

**Comment by HirogaKatageri** [comment]
> Well EasyEffects Flatpak should be able to use your icon theme from your host.
> 
> Do other GTK apps have problems? Can you try `pulseeffects` from apt to rule out a Flatpak problem (I believe some icons are similar).

Pulseeffect is okay, I tested out the icon theme Kora, I just saw it in one of the old threads and it's working fine with that one.

**Comment by vchernin** [comment]
So since trying Kora everything works? Or just pulseeffects from apt?

**Comment by HirogaKatageri** [comment]
Sorry, I mean Kora works with Easy Effects.
Pulse Effects works with any icon theme.

**Comment by vchernin** [comment]
It's probably your non-Kora icon theme that didn't support GTK4 or something then.

**Comment by HirogaKatageri** [comment]
Okay~ Apparently my custom icons should have been in /usr/share/icons it's working fine... Sorry about that.

**Comment by wwmm** [comment]
No problems :-)

**Comment by kon14** [comment]
For anyone stumbling upon this trying to figure out why their user installed icon themes won't work, it's probably cause you're placing them in `~/.icons`, instead of `~/.local/share/icons` which is the appropriate path for them to be installed in according to the [freedesktop spec](https://specifications.freedesktop.org/icon-theme-spec/latest/ar01s03.html), with `~/icons` only being available for backwards compatibility.

Flatpak automatically exposes your host installed icon themes (from `~/.local/share/icons`, `usr/share/icons` and `/usr/local/share/icons`) under `/run/host/user-share/icons` inside the sandbox, but won't do for `~/.icons` as the directory is effectively deprecated.
EasyEffects picks up icon themes from `/run/host/user-share/icons` just fine, thus every theme installed in either one of these 3 paths on the host should work ootb.

When it comes to exposing directories yourself, you could expose `~/.icons` yourself using an override, but EasyEffects won't pick it up whether you're running it inside or outside Flatpak and that's probably due to the path being deprecated.
You can't manually force map from `~/.icons` to any of the `/usr` or `/run` icon paths either as these are [blacklisted by Flatpak](https://docs.flatpak.org/en/latest/sandbox-permissions.html#filesystem-access) due to said paths already existing in the runtimes etc, though I don't see why you'd wanna do that.

So _**tl;dr**_, if you really don't wish to install your themes system-wide or can't do that due to using an immutable base image distro (eg Fedora Silverblue), just put your icon themes in `~/.local/share/icons` and you'll be set.
