### ISSUE TITLE
GLib-GIO-ERROR no start

### ISSUE THREAD

**Issue by 2A4U** [wwmm/easyeffects#1303]
### EasyEffects Version

git

### What package are you using?

Other (specify below)

### Distribution

git

### Describe the bug

Easyeffects won't start due to Glib-GIO-ERROR.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
(easyeffects:6547): GLib-GIO-ERROR **: 22:35:49.448: Settings schema 'com.github.wwmm.easyeffects' does not contain a key named 'autohide-popovers'
Trace/breakpoint trap
```
</details>

**Comment by wwmm** [comment]
Assuming you are running directly from a build folder where you have compiled easyeffects you have to run `glib-compile-schemas data/schemas/` and exporting  `GSETTINGS_SCHEMA_DIR` with the correct path.

**Comment by 2A4U** [comment]
It was installed to system (/usr) with xbuild.

`glib-compile-schemas data/schemas/` was run.

easyeffects schemas was installed to '/usr/share/glib-2.0/schemas'.

The following does not work:

`export GSETTINGS_SCHEMA_DIR='/usr/share/glib-2.0/schemas/' ; easyeffects`
`export GSETTINGS_SCHEMA_DIR='/usr/share/glib-2.0' ; easyeffects`

`GSETTINGS_SCHEMA_DIR='/usr/share/glib-2.0' easyeffects`
`GSETTINGS_SCHEMA_DIR='/usr/share/glib-2.0/schemas/' easyeffects`

**Comment by wwmm** [comment]
>easyeffects schemas was installed to '/usr/share/glib-2.0/schemas'.

In that case you have to give the system path as argument `glib-compile-schemas /usr/share/glib-2.0/schemas`. But usually the package management system does that automatically. Maybe that `xbuild` you are using does not do that.

**Comment by 2A4U** [comment]
[xbuild](https://gitlab.freedesktop.org/2A4U/xbuild) can run commands before 'configure' with a '*.prep' file:
`echo 'glib-compile-schemas /usr/share/glib-2.0/schemas' > ~/xuser/module_prep/easyeffects.prep`

The issue still persists. This is a regression because earlier in the git history `glib-compile-schemas data/schemas` worked with xbuild.

If you want, I can try to find the commit the regression was first introduced.

**Comment by wwmm** [comment]
>This is a regression

That is very unlikely. The Meson scripts handling our gsettings schemas have been the same since when we still targeted Pulseaudio. And besides the people using our development branch through Flatpak builds I and other people are also testing our master branch through an Arch Linux pkgbuild. If the new configuration keys were not being compiled everyone would be seeing this crash.

>earlier in the git history glib-compile-schemas data/schemas worked with xbuild.

Probably because there was no new key being added and for some reason you had them generated by something inside `/usr/share/glib-2.0/schemas/`. But with your current scripts that is not being updated with the new keys now. There is only one situation where it makes sense to run `glib-compile-schemas data/schemas`. It is when you do not install and run directly from the build folder inside the source code folder. When you install in your system the schemas go to another path `/usr/share/glib-2.0/schemas/` and in this case the commadn has to be `glib-compile-schemas /usr/share/glib-2.0/schemas/`.

Is xbuild calling `glib-compile-schemas /usr/share/glib-2.0/schemas/` before files are installed? It has to be after copying the schema files to `/usr/share/glib-2.0/schemas/`.

**Comment by wwmm** [comment]
>and for some reason you had them generated at some point by something inside /usr/share/glib-2.0/schemas/

The reason why this is possible is that for performacne reasons gsettings puts all applications schemas inside a single `gschemas.compiled` binary file that is generated when `glib-compile-schemas /usr/share/glib-2.0/schemas/`. Another application installation script could have called this command . This could explain why things have been working on your computer until now.

**Comment by 2A4U** [comment]
'\*.prep' files execute before configure. '\*.post' files execute after install.

Issue solved with:
```
echo 'glib-compile-schemas /usr/share/glib-2.0/schemas' > ~/xuser/module_postinstall/easyeffects.post
reboot
```

In that case the updated real-linux (Linux from Scratch) build instructions should look like on [this page](https://github.com/wwmm/easyeffects/wiki/Installation-from-Source):
```
meson _build --prefix=/usr
sudo ninja -C _build install
glib-compile-schemas /usr/share/glib-2.0/schemas/
reboot
```

Thanks for your time.
