### ISSUE TITLE
Keeping PulseEffects information in Wiki?

### ISSUE THREAD

**Issue by vchernin** [wwmm/easyeffects#1308]
Looking through the wiki I realized there is still plenty of information concerning PE. I imagine a new user who has no real idea what either app does could end up confused. 

For example https://github.com/wwmm/easyeffects/wiki/FAQ switches back and forth between PE and EE, and might make sense for us, but would be confusing for someone new I imagine.

I wanted to improve this but I wasn’t sure what the best approach is.

- Should PE specific info be kept in the wiki at all? Eg instructions to install PE packages.
- Should PE specific info be moved to its own section of the wiki? And the rest of the wiki is only EE information? 
  - Some PE information is probably still applicable to EE, but it should be verified and PE->EE should not be blindly renamed. After it’s checked that info could be re-added into the EE part of the wiki. 
- Do we still want a wiki when there is improved in app documentation? I think we do, but can we integrate the app docs into the wiki?

**Comment by wwmm** [comment]
>Should PE specific info be moved to its own section of the wiki?

I think that this is the proper thing to do. 

>Do we still want a wiki when there is improved in app documentation? I think we do, but can we integrate the app docs into the wiki?

Yes. The documentation is more about the plugins controls. Other things like community presets are better in the wiki. 

I do not know if we can integrate the manual contents in the wiki. Unless there is a way to make the wiki read xml files from the repository.

**Comment by vchernin** [comment]
Another related idea: how about linking to the Plugin manual page in the individual Plugins pages? In addition to having the manual button in the hamburger menu. 

So in Pitch it could link to the Pitch Plugin manual page, perhaps instead of saying "Using RubberBand" since RubberBand is mentioned in the manual anyways.

**Comment by Digitalone1** [comment]
> So in Pitch it could link to the Pitch Plugin manual page, perhaps instead of saying "Using RubberBand" since RubberBand is mentioned in the manual anyways.

Not all users take a look at the manual and the credit in the UI was added mainly to inform the user that a specific library is needed to make the plugin work, since lots of times people came here asking why some plugins were working and others not, demanding afterwards for a list of packages to install for the relative plugins.

There's already one in the Github homepage, but not everyone read it and it could be misleading because the packages in the distro repository could have a different name. We thought placing a label in the footer of the plugin interface was the best thing to do to let the user know that something is missing on their side.  

Besides not all packages install the entire dependencies. [Arch](https://archlinux.org/packages/community/x86_64/easyeffects/) one for example has mda and zam optional. Anyway a link to the manual could be added in another part of the plugin UI.

**Comment by vchernin** [comment]
I moved the PulseEffects-specific information to it's own page.

I see there are tools to convert [markdown to docbook](https://github.com/msmid/markdown2docbook) (yelp supports).

Also instead of xml you could write the current mallard docs with [ducktype](http://projectmallard.org/about/learn/ducktype). It looks a lot easier to type than xml.

**Comment by wwmm** [comment]
>So in theory, all manual contents could be converted into markdown, stored with the wiki contents in one spot, and then converted to html every release for yelp to use. Does that sound beneficial?

Now that they have already been written I do not see much advantage. The xml format is annoying but it is not something we edit often.

**Comment by vchernin** [comment]
> Now that they have already been written I do not see much advantage. The xml format is annoying but it is not something we edit often.

I agree, I guess it is something only worth considering if already reworking the manual.

I suppose the main thing then in this bug is finding a spot to put the plugin's manual link in the plugin ui?

**Comment by Digitalone1** [comment]
The credit is placed in the right side of the footer. The link could go on the left side.

**Comment by vchernin** [comment]
the main issue (wiki) was fixed
