### ISSUE TITLE
Process all inputs: move only streams recording from selected mic

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/easyeffects#1335]
### EasyEffects Version

6.2.1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Hi, currently there is an option to process all inputs, which could be nice since I want to process my mic for all applications, but it is not usable as is.
The problem is that, when this option is enabled, EasyEffects moves ALL recording streams to the EasyEffects Source.
This also includes streams recording from monitor sources, so one can't capture desktop audio anymore when this option is enabled.
Also in case of having multiple mics this is problematic, since recording multiple of them is not possible anymore, since EasyEffects moves all recording streams to the EE Source, which only processes one mic.

### Additional Information

To solve this, as an idea,
instead of (pseudo code):

```
foreach (inputstream in inputstreams) {
    // move stream to record from EasyEffects source
}
```

something like this could be done:

```
foreach (inputstream in inputstreams) {
    if (inputstream is recording from selected mic in EasyEffects settings) {
        // move stream to record from EasyEffects source
    }
}
```

**Comment by wwmm** [comment]
The "solution" to this problem already exists. Add the streams for which no effects should be applied to the blocklist. That being said there are some applications like OBS #807 for which the blocklist doesn't work. And unfortunately there isn't a way to handle super corner cases like that.

**Comment by wwmm** [comment]
>something like this could be done:

In thery seems simple but that approach also has undesirable side effects. The default configuration is using the system default microphone. It is totally possible that the user has 2 applications recording from the default mic but he wants effects only for one of them. IF we just move to our virtual device anything recording from the default mic just because that is the mic EasyEffects is using there will also be problems.

The current blocklist approach is far from perfect. But I doubt a perfect solution will ever be available considering what is discussed at #807. In general audio applications do not make good use of the tags supported by the audio servers. If they did a more advanced filtering procedure could be implemented.

**Comment by Bleuzen** [comment]
> The "solution" to this problem already exists. Add the streams for which no effects should be applied to the blocklist.

This is not a solution here. I mentioned multiple mics / inputs (also instruments which I don't want to run through EE).
As an example: I want to record in Audacity. Instruments / secondary mics without processing, but main mic with processing. Adding Audacity to the blocklist just won't apply any processing at all, so this isn't doing it. I want processing for Audacity, but only when it tries to record from my main mic, leaving other input streams recording for example instruments as is.



> That being said there are some applications like OBS #807 for which the blocklist doesn't work.

I noticed that. If EE would automatically enable processing only for streams that try to record from the chosen input this would fix it.

![image](https://user-images.githubusercontent.com/12885163/149622116-f127aa84-893f-4ddd-b4de-0ee584941fe9.png)

Change logic to not move all recording streams to the EE Source, but only the ones that try to record from the input set here this problem would disappear. No blocklist needed.


> In theory it seems simple but that approach also has undesirable side effects. The default configuration is using the system default microphone. It is totally possible that the user has 2 applications recording from the default mic but he wants effects only for one of them.

See no problem here. In this case, users just shouldn't use the "process all inputs" option:
![image](https://user-images.githubusercontent.com/12885163/149622284-542b4ed0-42a9-40f5-855a-507bfff61885.png)

It is even disabled by default.
Just to make that clear: For this issue I'm talking about the logic that only should apply if that "process all inputs" option is enabled. Nothing should change if that option is disabled.



> The current blocklist approach is far from perfect.

Yeah it is totally useless for the setup I'm talking about.

> But I doubt a perfect solution will ever be available

I do understand this. Everyone has different setups and needs. But I think that with my suggestion (only process recording streams trying to record from the selected input) it should fix it for most users. Recording from monitoring devices (like desktop audio) should work again. Handling multiple input devices should start working.
Not perfect for anyone, but a nice improvement.


---

Also one thing I thought about, just as an alternative:

Maybe this could be decoupled from the "process all inputs" option. A new option could be added, something like "only care about the selected input device" or "filter recording streams for only the ones recording from the selected input" (should find better naming for it).
If this is enabled, EE could even filter the list of applications here:
![image](https://user-images.githubusercontent.com/12885163/149622648-d2cb504e-870e-45ab-bb94-ecb5d62c7e51.png)

to only show the ones that are recording from the selected input:
![image](https://user-images.githubusercontent.com/12885163/149622704-caa0a644-0150-423d-9f96-f57612eda87a.png)

so that, if that new option is enabled, the application list is filtered and looks like this:
![image](https://user-images.githubusercontent.com/12885163/149622817-e1e1c6cd-5853-428d-b051-c38875dbe498.png)

Would even suggest that this option is enabled by default because usually you only want to add effects to your input device, not change the input device entirely.

If the apps list would be filtered, the switch would, for the shown applications, actually only toggle effects processing on/off.
But if the apps list show all recording streams (current behaviour), the on/off switch now doesn't toggle effects on/off, but also moves recording streams entirely unrelated to the input a user wants to process to the EE source, which is only the input device selected in EE settings.
For example one has a recording stream for Audacity running, wanting to record an instrument. EE is setup to process the mic input. Now if Audacity starts recording, it will be listed in the apps page in EE with a toggle for effects on/off. If it is off, it will record the instrument, as setup in Audacity. If a user turns the effects switch in EE on... they expect to only enable effects processing... but no, it will lead to Audacity recording something entirely different (EE would switch Audacity from recording the instrument to recording the mic). This is irritating behaviour.
The new option I suggested would fix that and I think it would be good to enable it by default for more predictable behaviour / user friendliness.

**Comment by wwmm** [comment]
Ok, let me see if PipeWire is already giving us the information about to which device the stream is connect to.

**Comment by wwmm** [comment]
I was almost sure this would be a straightforward thing to do but I am not seeing in the output of `pw-cli info id`, where `id` is the audio stream id number, to which node it is connected to. I think it will be necessary to iterate over all link objects to find the streams links. It seems they are the only ones with the information about where the stream output is going.

It is still doable. No as fast as I thought it would be but still doable.

**Comment by wwmm** [comment]
> I think it will be necessary to iterate over all link objects to find the streams links

I am looking at this again and one problem that is going to be a little annoying to handle is that the the signal PipeWire emits with new links information comes some time after the one about the nodes creation (and this is the one where I have to decide if I move the stream or not). I will have to be careful about how to synchronize things...

**Comment by Bleuzen** [comment]
Would it help to ask pipewires developer in case there is or will be a better solution or do you think it is fine to work with as is?

**Comment by wwmm** [comment]
>Would it help to ask pipewires developer in case there is or will be a better solution or do you think it is fine to work with as is?

I am not sure it makes sense to make changes in PipeWire because of this. It just happens that nodes and links are different and independent objects. It may not make sense in the server to wait for links before emitting signals about nodes creation, destruction or changes because you can have nodes without links. As soon as a stream or filter is created it has no link at all. But is still important to know they exist.

We will have to live with this and find some way to handle this situation. I am not sure how yet.

**Comment by wwmm** [comment]
>This also includes streams recording from monitor sources, so one can't capture desktop audio anymore when this option is enabled.

I wonder if the workaround discussed at #1541 could be extended to improve things here. I did not find a solution to the limitations I talked about before. But now I know there is a way to detect when a stream is recording from sink monitors I wonder if instead of applying it just to OBS it would not be better to create a configuration option that would allow effects to be disable to any stream that records from sink monitors.

**Comment by Digitalone1** [comment]
> > This also includes streams recording from monitor sources, so one can't capture desktop audio anymore when this option is enabled.
> 
> I wonder if the workaround discussed at #1541 could be extended to improve things here. I did not find a good solution to the limitations I talked about before. But now I know there is a way to detect when a stream is recording from sink monitors I wonder if instead of applying it just to OBS it would not be better to create a configuration option that would allow effects to be disabled to all stream recording from sink monitors.

It's better to add the config option, so we don't have to make a specific code for OBS.

I hope that it would also work for pavucontrol, so we could use it to exclude pavucontrol localization.

**Comment by wwmm** [comment]
>I think we can have a workaround for this case if we look at the stream node.target property and ignore the ones that have it set. Not all streams will have it. But the ones that are created with a source device specified should have it.

So much time has passed that `node.target` has become deprecated and now `target.object` has to be used. I have updated our master branch with the partial workaround I talked about before.  If EE is already running by the time the stream starts it will check if the custom target.object set by the user matches the mic being used by EE.

There are some limitations. If the user sets a custom mic in EE settings when the stream is already running this check is not done again. So streams that where ignored before won't magically come back without restart the stream or EE.

I guess this is as good as it can get... Let's close this issue...

**Comment by ghost** [comment]
@wwmm so is it possible not to have 2 usless tabs "output" and "input" that do absolutely nothing and have a normal fucking tab where you can work with raw virtual mics/devices?

i want to apply effects onto output of a certain microphone (i redirect 100 streams into a single virtual mic, "my-virtualmic Audio/Source/Virtual sink") created via pipewire, but only things I got is 2 tabs (I assume output applies output onto output of applications?) and input applies effects onto stuff that comes in APPS (aka input sound from apps to certain app)? How does it exactly work, it makes no sense not having ability to work directly with virtual mics considering this is the only app that works with pipewire currently.

**Comment by wwmm** [comment]
> @wwmm so is it possible not to have 2 usless tabs "output" and "input" that do absolutely nothing and have a normal fucking tab where you can work with raw virtual mics/devices?
> 
> i want to apply effects onto output of a certain microphone (i redirect 100 streams into a single virtual mic, "my-virtualmic Audio/Source/Virtual sink") created via pipewire, but only things I got is 2 tabs (I assume output applies output onto output of applications?) and input applies effects onto stuff that comes in APPS (aka input sound from apps to certain app)? How does it exactly work, it makes no sense not having ability to work directly with virtual mics considering this is the only app that works with pipewire currently.

I usually just ignore aggressive comments that come out of nowhere but here we go...

You are definitely confusing easyeffects with a general purpose digital audio workstation. That is not the target here... The microphone pipeline will only be active when a recorder is recording from our virtual source. 

The workflow is setting your microphone as easyeffects source. What will happen automatically if your mic is the default system source. If not you will have to use manual selection in easyeffects pipewire tab. After that launch an audio recorder that records from our virtual mic.

**Comment by ghost** [comment]
> I usually just ignore aggressive comments that come out of nowhere but here we go...

Trust me the comment was not supposed to sound as aggressive one, my questioned was raised mainly due to the "monopoly" of easy effects over any other inexistent solution for pipewire (considering carla and others do not work with pipewire and won't be working)...

> You are definitely confusing easyeffects with a general purpose digital audio workstation.

I wish I were, I see no difference between extending the current solution into useful one (considering its using pipewire and you are probably hardcoding something, not even sure why not to extend to supporting virtual sinks from the start)...

> The microphone pipeline will only be active when a recorder is recording from our virtual source.

Obviously I understand that, yeah and I do have that. But its active even if there's no apps "enabled" and no stuff is recording this sink's output.
<img width="596" height="199" alt="Image" src="https://github.com/user-attachments/assets/908245f5-4e07-4a5d-a317-2f336a445d31" />


> The workflow is setting your microphone as easyeffects source. What will happen automatically if your mic is the default system source. If not you will have to use manual selection in easyeffects pipewire tab. After that launch an audio recorder that records from our virtual mic.


So you are telling me that the only way to get stuff done is sourcing directly from the mic named "Easy effects mic"? xD? That just sounds dumb to me I can't lie. Now imagine if certain softwares are going to expect different bitrates and other parameters on the microphone line or filter out easyeffect's virtual sink name? Are you going to ask people just to recompile stuff?

Once again its not aggressive comments I am just trying to be as straightforward as possible. I remember coming across this report last year, then 5 months ago and always ended up just removing the app because "the only app that supports pipewire only supports "auto fetch app names" and no virtual sinks".


I doubt your app has capatbilities of qwgraph and others, that can filter out processes by pid and autoattach/reattach effects, let's say I got 3 mpv players that running simultaneously, and I have a script that goes through the processes auto attaching them based on certain properties of the process, it works well, they all redirect sound to the microphone, which (I LATER could've set as input device and apply effects onto it in your solution) can do the job. Your solution must not support such things since you claim it  as a plain solution, so why not let us have the third tab (since you wanna keep it as simple as possible) and just treat virtual sinks as outputs?

<img width="550" height="316" alt="Image" src="https://github.com/user-attachments/assets/41e5d97f-4a54-4d99-b6e1-0be7da8137b7" />

You can suck data out of the capturing interfaces of individual devices and there will be no difference between current implementation and the future possible tab.

**Comment by wwmm** [comment]
Everything you are requesting are things I would expect from a general purpose digital audio workstation. But that is not what easyeffects  is. The target here is redirecting audio streams to our virtual devices and after applying effects sending the resulting audio data to the devices set as easyeffects  input/output devices.

Virtual devices will work as long as the restrictions above are followed. You can have a virtual device that is visible as source to easyeffects just like a microphone is. And applying effects to it. But that is it.

**Comment by ghost** [comment]
> You can have a virtual device that is visible as source to easyeffects just like a microphone is

So If I recompile and lift the restrictions of "virtual sinks" being filtered/not included they will be applied into the output list?

> Everything you are requesting are things I would expect from a general purpose digital audio workstation.

Considering its pipewire and here's really no difference in general, I'd rather be able to have both.

**Comment by wwmm** [comment]
>So If I recompile and lift the restrictions of "virtual sinks" being filtered/not included they will be applied into the output list?

It is not that we filter them. Sinks and streams are used for different purposes and work in different ways. It isn't just a matter of "unblocking". It doesn't make sense to ask PipeWire to move a sink to our virtual device. It probably will never work.

That being said there are some nodes that behave as a sink or a source but are actually composed by a combination of streams. For example loopback devices are implemented by PipeWire this way. That is why they are usually visible in our players/recorders list.

But if the sink or source is created by loading a null-sink just like we do to create our virtual devices you may just have a broken EasyEffects trying to make them visible in our list. I am not sure if the command we use to ask PipeWire to move streams around even works with a null-sink...
