### ISSUE TITLE
Theming inconsistent with other applications

### ISSUE THREAD

**Issue by Eonfge** [wwmm/easyeffects#1340]
### EasyEffects Version

6.2.1

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35, Flatpak 1.12

### Describe the bug

There are some discrepancies with the Adwaita-dark branding of other Flatpak apps. like Lollypop

![Screenshot from 2022-01-15 07-37-35](https://user-images.githubusercontent.com/33983090/149612086-a07904f4-d57a-4959-9507-3411cd97549d.png)

### Expected Behavior

Would it be possible to streamline the theming so that it matches the theming of the rest of the system. You'll also have to test this with other themes.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Uhm...?
```
</details>

**Comment by vchernin** [comment]
Adwaita-dark is different from Libadwaita's dark style appearance, and lollypop still is GTK 3, so to some extent making these apps look and feel similar is an uphill task.

Technically you can use `GTK_THEME` and other configuration files to theme any GTK app (but those are meant for development purposes), but I don't know if anyone has made GTK4 themes that support libadwaita's css at all correctly.

I imagine though, that Lollypop might eventually move to Libadwaita/GTK4 too, making them _very_ consistent since they use the same ui/platform library?

FYI the theming/look isn't supposed to change with Flatpak vs non Flatpak builds (assuming the theme is installed as a Flatpak).

**Comment by wwmm** [comment]
It is exactly what has been said by vchernin. It is the applications using older GTK versions that have to adapt. Or GTK developers have to create some kind of means to ensure consistency between gtk3 and gtk3 applications. In any case it is not something that can be fixed on our side.
