### ISSUE TITLE
Running multiple pulseeffects (easyeffects) instances?

### ISSUE THREAD

**Issue by davidmcnabnz** [wwmm/easyeffects#1397]
Hi there,

Is there a way to run multiple instances of pulseeffects (or easyeffects) on the one machine?

I've got several USB sound cards, and would like to have a different instance of pulseeffects working with each soundcard.

When I have a pulseeffects instance already running, and try to start another one, the command simply exits without starting up the second instance.

**Comment by wwmm** [comment]
>Is there a way to run multiple instances of pulseeffects (or easyeffects) on the one machine?

No, it is not possible and never will. The two instances would conflict with each others in ways that can not be avoided. Not only because they would compete at the moment of redirecting the audio streams or trying to load and use virtual devices with the same name. They would also try to write to same configuration database.
