### ISSUE TITLE
OS crashes if import preset button is clicked

### ISSUE THREAD

**Issue by Netherquark** [wwmm/easyeffects#1407]
### EasyEffects Version

6.2.3

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 35

### Describe the bug

1. Launch EasyEffects
2. Open the Presets popdown
3. Select import from file
4. Nautilus pop up opens, but Presets is above Nautilus popup, freezes Gnome (can't open other apps, can't close EasyEffects, nothing. surprisingly, transparency effects still work).

### Expected Behavior

The Nautilus window hides the Preset window and the system doesn't crash.

### Debug Log

Can't record a debug log

### Additional Information

inxi:
[inxi.txt](https://github.com/wwmm/easyeffects/files/8108993/inxi.txt)
Gnome Tweaks config:
![image](https://user-images.githubusercontent.com/65618735/154958725-c3f52f56-5927-44f3-8fc8-61fbcc0bc093.png)

**Comment by wwmm** [comment]
This problem is being discussed at #1179. Long story short it is something that only GTK's developers can fix.

**Comment by wwmm** [comment]
>should I downgrade EE in the meanwhile?

This will help only if you downgrade to a very older version based on GTK3 instead of GTK4. In many cases it is not viable. What the import dialog does is copying files to the folders inside `~/.config/easyeffects/`. If I were having this problem on my current `GNOME + Wayland` installation I would copy files manually as a workaround.

**Comment by Netherquark** [comment]
Hey I found the maximising solution so nvm


Thanks for the prompt hep :))
