### ISSUE TITLE
Add a noisetorch plugin

### ISSUE THREAD

**Issue by JacobTravers** [wwmm/easyeffects#1469]
[Noisetorch](https://github.com/lawl/NoiseTorch) seems to preform better than rnnoise in my experience so I was curious to see if it would be possible to integrate noisetorch as a plugin in easyeffects, that way we don't need to install and configure a whole separate interface. It would also be nice for automatically applying the filter with a preset. We already have an rnnoise plugin, and I know noisetorch used rnnoise so I wonder if it would just be a matter of adapting/updating that plugin?

**Comment by wwmm** [comment]
As far as I could see they also use rnnoise. So even if it were possible it does not seem to make much sense if the core library responsible for the noise suppression is the same.

As rnnoise is based on a neural network its performance is depedent on whether the model being used is a good match to the type of noise that someone wants to filter. So far I have had very good results with it. Maybe NoiseTorch is using a custom neural model instead of the default that built-in in the rrnoise library. That could explain why it performes better in your case.

**Comment by wwmm** [comment]
>and I know noisetorch used rnnoise so I wonder if it would just be a matter of adapting/updating that plugin?

You can load another model. I think that the rnnoise page has instructions on how to create one customized for your needs. But I never tried to do this.

**Comment by wwmm** [comment]
>It would also be nice for automatically applying the filter with a preset

I did no understand. Rnnoise is already saved to the user preset file. But the only parameter is the file path to the custom model that has to be loaded. So there is not much to be saved.

**Comment by wwmm** [comment]
I am looking at noise torch code and they are doing some kind of processing on top of rnnoise. I did not understand what yet. But involves FFT.

**Comment by JacobTravers** [comment]
> I am looking at noise torch code and they are doing some kind of processing on top of rnnoise. I did not understand what yet. But involves FFT.

@lawl would you be willing to help or comment on this?

**Comment by lawl** [comment]
It's GPL. So is this project. No FFT.

**Comment by wwmm** [comment]
Now that our master branch has another `noise reduction + voice detection` plugin based on libspeex I think we can close this issue.
