### ISSUE TITLE
Last tag was 6.2.4 and is now 4.8.6 please explain.

### ISSUE THREAD

**Issue by barjac** [wwmm/easyeffects#1470]
### EasyEffects Version

4.8.6

### What package are you using?

Other (specify below)

### Distribution

Mageia

### Describe the bug

How can a new tag jump backwards from 6.2.4 to 4.8.6?

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by vchernin** [comment]
Any release < 5 is for the old pulseeffects pulseaudio branch.

**Comment by Digitalone1** [comment]
Indeed that tag is related to pulseeffects legacy branch, not master easyeffects.

**Comment by wwmm** [comment]
@barjac For simplicity I manage EasyEffects and the legacy branch for Pulseaudio (PulseEffects) in the same repository. Because of some changes in the `Linux Studio Plugins` library PulseEffects needed a new maintenance release. EasyEffects interact with the plugins in a very different way and does not need a new release to deal with `LSP 1.2.0`.

**Comment by wwmm** [comment]
It may be a little confusing but as PulseEffects is only going to receive new releases in extreme situations like this one it is fine to handle everything in the same place.

**Comment by barjac** [comment]
Thanks, I understand now.
I do still feel that you should have kept pulseeffects as a separate archive repository and simply forked it for easyeffects.
I maintain both packages now for Mageia and my script for detecting new package updates will now need some hacking to handle these.
