### ISSUE TITLE
EasyEffects imposes a default output for players in WirePlumber unless they are explicitely excluded

### ISSUE THREAD

**Issue by kawazoe** [wwmm/easyeffects#1515]
### EasyEffects Version

6.2.5

### What package are you using?

Arch (easyeffects)

### Distribution

Garuda (Arch)

### Describe the bug

While EasyEffects is running, WirePlumber will store a `target` node in the `Output/Audio:application.name:FooBar` section of the `~/.local/state/wireplumber/restore-stream` file and always set its value to the default system output. This happens even if the "Process All Outputs" options is set to false. The only way to prevent this is for the app to be excluded in EasyEffects *before* it creates a node. Once the target is set in the restore-stream file, it is impossible to unset without shutting down pipewire, deleting the property, and starting pipewire again. This node target will override any in-app output configuration or custom configuration that you might have done through pipewire's configs.

This is a massive problem for systems with multiple audio outputs. All of my custom bindings completely stopped working after starting EasyEffects for the first time and it took me a while to figure out what was happening.

## Repro steps (clearer steps with pictures further down the thread):
- On a system with at least 2 audio outputs,
- Start EasyEffects.
- Set the "Process All Outputs" setting to false.
- Close EasyEffects and ensure it is not running in the background.
- Install an app that let you chose an output (like discord).
- Go into the app's settings and set the output to use an output that doesn't match the default. (Eg if A is default, pick B)
- Open the restore-stream file in a text editor.
- Notice that the app is listed in the Output/Audio/application section (WEBRTC\sVoiceEngine for discord)
- Notice that there is no target listed for that application, even though you changed the output.
- Open EasyEffects.
- Notice that the restore-stream file has changed and that a target has been set with the default output for that application.
- From this point, changing output in the app has no effect.

### Expected Behavior

Unless an output/input is set to enabled, EasyEffects should not have any impact on the routing of that input. This behavior means that EasyEffects is impossible to use in "whitelist" mode as every new app that you open will have their output explicitly routed in WirePlumber at least once before you get to exclude it.

### Additional Information

According to #549 , setting the "Processing all outputs" to false should be the equivalent of setting EasyEffects in whitelist mode. It was used as a justification to not include an explicit whitelist. Clearly, it isn't the case as EasyEffects still affects the streams in some way unless they are explicitly excluded.

**Comment by wwmm** [comment]
It may seem to you that "EasyEffects" is doing something but it isn't. When you disable `Process All Outputs` EasyEffects does not try to move streams. It does not touch them. WirePlumber is the one deciding to move streams to our devices through its `restore-stream` feature. I have no control over its behavior.

**Comment by wwmm** [comment]
>Clearly, it isn't the case as EasyEffects still affects the streams in some way unless they are explicitly excluded.

Again all that the blocklist does is avoiding that EasyEffects tries to move the stream to its virtual devices. The media session manager as well as third party applications like Pavucontrol are still able to force the stream to be moved to our virtual devices.

**Comment by wwmm** [comment]
Something you may try is replacing WirePlumber by the built-in PipeWire media session manager and check if the behavior is different. Based on what you say WirePlumber seems to be giving higher priority to our virtual devices when deciding what to do with the streams. I would expect it to favor the hardware instead of a virtual device.

**Comment by kawazoe** [comment]
Ok, from what I'm reading, we're not on the same page. I'd like to clarify a few things with you before we move on.

## The test app is included in EasyEffects
First, lets look at a normal situation using Discord (`WEBRTC VoiceEngine`) as an example:
![image](https://user-images.githubusercontent.com/406575/167065759-d2562c35-13de-4ac9-84b7-bf7f6eb75ec9.png)
![image](https://user-images.githubusercontent.com/406575/167065777-96b95b82-10e6-4309-9695-a67ac650ade0.png)

In this setup, I have a device with an input and output named `MG-XU Digital Stereo`. This device is the one that I have picked in the PipeWire configuration tab for EasyEffects. As you can see, the pipeline looks totally fine, just as expected.

Now, lets go in discord and change the input device to the system default's and the output device to `MG16XU 7+8`. This is a virtual device that routes the signal to a pair of ports on a separate sound card configured in pro mode:

![image](https://user-images.githubusercontent.com/406575/167066223-f59795ce-37a2-4cfa-8527-00226cd4ddec.png)
![image](https://user-images.githubusercontent.com/406575/167066012-2a14cbe7-3d16-452d-ac6d-89673f0ee5c4.png)

Ok, nothing changed... that's odd. Here, we expect `WEBRTC VoiceEngine` to be directly connected to the devices but `WEBRTC VoiceEngine` is still enabled in EasyEffects, so while it is odd that it takes over in-app settings, it is sensible to assume that it is desired. Let's try to disable it in both the input and output tabs of EasyEffects.

![image](https://user-images.githubusercontent.com/406575/167066319-a73cbc49-3861-441e-8676-69d581a4de7a.png)

And now, we hit the bug. First, we can see that Discord is now bound to the proper input device, as we might have expected in the previous set of screenshots. Second, `MG16XU 5+6` is my default system output device, but Discord is configured to use the `MG16XU 7+8` output. In fact, the device selection in discord doesn't do anything anymore. I can pick any input or output in the list, and it sticks to my system defaults. This is why the binding for the input device appear to have worked when we disabled the app in EasyEffects. If pick any other input device, it still sticks to my system's default.

## The test app is excluded in EasyEffects
Now, let's add Discord to the exluded devices in EasyEffects (both tabs), close everything, delete the `restore-stream` file, restart pipewire, start EasyEffects, and start discord again.
![image](https://user-images.githubusercontent.com/406575/167067070-866eb9d2-8bea-4d24-b2e9-5660dea0c616.png)
![image](https://user-images.githubusercontent.com/406575/167067078-e60c90a4-b879-4809-adfb-0b88dbdeefef.png)

We are back to our normal behavior, as expected. EasyEffects shows Discord as enabled automatically; nice. Let's pick different devices in Discord.
![image](https://user-images.githubusercontent.com/406575/167067133-857cb9d5-fa8e-44e8-9048-a6d64776e87b.png)
![image](https://user-images.githubusercontent.com/406575/167067140-cb832b56-f5de-4003-ac75-22aa8861f226.png)

Now the routing works correctly. EasyEffect didn't take over the app's settings and Discord appear as disabled automatically; nice. I can go back and forth between multiple different input or output devices, including EasyEffect's, and everything continues to work correctly. This is the expected behavior.

## Moving on
While I agree that this might be a WirePlumber issue, EasyEffects **MUST** be having an impact on why it decides to brick itself like this. There must be a difference between doing the first set of actions and the second from an API call point of view. This isn't a one off either. I can reproduce this 100% of the time.

Now, this leaves 3 possibilities:
1) This discrepancy is a bug in EasyEffects. Somehow, one of the call sets a permanent node target of "default" instead of "none" which ends up stored by WirePlumber with no way to undo the change. In this case it should be fixed so that it behaves the same whether the input/outputs where excluded or not in the first place.

2) This discrepancy comes from a necessary behavior in EasyEffects; in which case there should be a way to set the app in some sort of whitelist mode that would automatically exclude new devices *unless* they have been included manually. This would let user choose the behavior that they want (take over, or manual) which is useful for people will multiple inputs/outputs.

3) There is a bug in WirePlumber. BUT! It is impossible for EasyEffects to "not touch [the streams]" while simultaneously producing different outcomes depending on settings chosen inside it. This bug is still triggered by something that's happening in EasyEffects. Saying that EasyEffects isn't the problem, while technically true in this case, isn't helpful at finding the cause of the problem. In fact, in this case, the cause is definitely located in the differences of API calls done between the two scenarios. If there's a way to log these, I could bring it up with the WirePlumber team for further investigation.

What do you think?

**Comment by wwmm** [comment]
The real issue is the discord device selection not working. And the one responsible for that is wireplumber. Even if you enable "process all outputs" in easyeffects the application device selector has to work. Just like pavucontrol is still able to do that even if easyeffects is running. 

Once you try to use easyeffects switch to turn off effects you force it to touch the stream. The problem is you can't "just turn off effects". You have to move the stream somewhere else. There is no way around that. And the easiest thing to do is moving it to the default device. We can not guess which one the user wants. And even if we had this information saved somewhere the device may not be available at the time.

There are 2 ways to create links in pipewire. The manual and hard way we are forced to use when linking filters and the easy way that is asking the session manager to do it for us. But this one only works for streams. When you disable/enable effects for apps in easyeffects what happens under the hoods is that a request is done to the session manager (wireplumber) to do the move for us. Any long term association is a wireplumber thing. We just ask it to move the stream to a given device. Nothing else beyond that.

Something similar happens with our virtual devices. We just ask pipewire to load them for us. There is no tag anywhere saying these devices should be forced to streams.

**Comment by kawazoe** [comment]
> We just ask it to move the stream to a given device.
Hmm. interesting. So that would mean that the way you're doing it some how ends up tagging the device, while the way the pulse compat layer doesn't.

I'll bring that up with the WirePlumber team and see if there's something on their that they can do and link it over here.

**Comment by wwmm** [comment]
>So that would mean that the way you're doing it some how ends up tagging the device, while the way the pulse compat layer doesn't.

It seems so. I will have time to do some tests now. Let's see how wireplumber is reacting on my computer. I also have 2 sound cards.

**Comment by wwmm** [comment]
It did not take long to see the problem happening. After disabling `Process All Outputs` I started `mpv`. Moving it from EasyEffects virtual device to the soundcard through `Pavucontrol` did not create the `target` property inside `wireplumber/restore-stream`. But moving it with EasyEffects creates the property.

But after doing more tests I've noticed something interesting. It is not that Pavucontrol does not cause the target property to be set. When I move the stream to my second soundcard it does create it. It does not when I move the stream to the default soundcard. The different in EasyEffects is that the PipeWire function we use creates the target in all cases and not just when the stream is moved to something that is not the default.

From an API point of view in EasyEffects it is used the native PipeWire function `pw_metadata_set_property` to ask the session manager to move streams between devices. Pulseaudio application will do calls to functions like `pa_context_move_sink_input_by_index` or `pa_context_move_sink_input_by_name`. Somehow different things happens when these functions are used.

**Comment by wwmm** [comment]
I am not sure I can workaround what is happening. It is super weird that different things happen depending on weather streams are moved with PipeWire's API or Pulseaudio API. The behavior should be the same. It does not make sense...

**Comment by kawazoe** [comment]
Well, that's why I initially suggested to have some kind of whitelisting. The second a new app is opened, it will show up in the list as "included" and trigger the bug, even if you don't "enable" it. If we could have an option as a workaround to have new apps excluded by default (not even a full whitelist), then at least EasyEffects would still be usable for people in this situation until we get some news from the WirePlumber folks.

**Comment by wwmm** [comment]
>Well, that's why I initially suggested to have some kind of whitelisting.

I do not see much point. There is the option to force effects to all applications and using the blocklist to avoid EasyEffects touching the ones you do not want it to move to its devices. The whitelist isn't adding a lot on top of that to justify the complication it will add to the code. With or without a whitelist the media session manager is still free to do whatever it wants with the stream.

**Comment by wwmm** [comment]
>If we could have an option as a workaround to have new apps excluded by default 

That will still cause problems. "Excluded" means moved somewhere else that is not our virtual device. We have to call `pw_metadata_set_property` in order to force an exclusion. What means causing the target property inside `wireplumber/restore-stream` to be set to "something".

**Comment by kawazoe** [comment]
That's not the behavior that I am seeing. If the apps are excluded before they appear in EasyEffects, there is no "target" tag added in the restore-stream file for those apps, and they continue to function correctly. This is how I made the screenshots for the "expected" scenarios. Eg, if you just add `WEBRTC VoiceEngine` to the exclusion list before starting Discord "for the first time", the device selection doesn't break and no stream is moved to the wrong device, even in very complex setup like mine with 6 different devices where I don't use my default device anywhere. That's what I hope to enforce with this workaround.

**Comment by wwmm** [comment]
>That's not the behavior that I am seeing. If the apps are excluded before they appear in EasyEffects, there is no "target" tag added in the restore-stream file for those apps, and they continue to function correctly.

We are probably thinking about different meanings for the word "excluded" in this context. Any solution implemented in EasyEffects would involve either doing a call to `pw_metadata_set_property` or just doing nothing with the stream that is what the blocklist actually does. There is no middle ground. If we call `pw_metadata_set_property` we set a target. And the only way this could possibly help is adding all the logic necessary for the user to select to which device it wants the "whitelisted" or "excluded" stream to be set if the default device is not the desired target. This is going way beyond what the current blocklist code does.

**Comment by pv** [comment]
Shouldn't easyeffects "disconnect" streams, by
```
pw_metadata_set_property(metadata, origin_id, "target.node", NULL, NULL);
pw_metadata_set_property(metadata, origin_id, "target.object", NULL, NULL);
```
so that it removes the redirection instruction? But maybe there was some problem with this?

The target metadatas are indeed persistent. The intended mental model is probably that the stream is "pinned" to a given target, not that they are moved around. The metadata pinning overrides what the application itself sets. The design is here somewhat constrained by aiming to have it work as with pulseaudio. With Pulseaudio API, moving streams to default target indeed unpins them, but with PW api you can do that by unsetting the metadata.

**Comment by wwmm** [comment]
>But maybe there was some problem with this?

No. That is not what happened. There was no mention anywhere when I was porting our code from Pulseaudio to PipeWire that setting metadata to null values was the right procedure or even a supported thing. The only reason why I even used `pw_metadata_set_property` was because I asked to taymans how I was supposed to move streams from one device to another. The documentation was really lacking in this topic. Once the procedure I had in Pulseaudio was working I just moved on with my life. I did not even considered trying set the metadata to null values.

I haven't looked at PipeWire docs in a while but things related to links and metadata needed some love. It is not even clear which metadata object we are supposed to use. There are 3 of them `settings, default, route-settings` and the reason why I am using `default` is because the others do not work for this. It was a trial and error process. Same thing for the links between filters. I had to read the code in the Jack module to figure out how to do them...

That being said things do not have to stay as they are. What exactly is going to happen to the stream if I set the metadata to null? Will it "magically" go back to the last used device instead of staying in our virtual device?

**Comment by wwmm** [comment]
>Will it "magically" go back to the last used device instead of staying in our virtual device?

No. If I use Pavucontrol to initially move the stream to my second soundcard (that is not the default) and then enable/disable effects the stream goes back to the default sound card when the metadata is set to null. It is not the end of the world considering that what we do at this moment is explicitly move it to the default device.

**Comment by pv** [comment]
> The documentation was really lacking in this topic

Yes, the documentation probably is not only lacking but non-existent... This should be improved.

> That being said things do not have to stay as they are. What exactly is going to happen to the stream if I set the metadata to null? Will it "magically" go back to the last used device instead of staying in our virtual device?

The session manager will notice the change, and update the routings. If the metadata has been removed, there's no longer a reason for the stream to go to the EE sink, so it will be directed according to the preference from the application (or to the default devices if application does not specify).

**Comment by wwmm** [comment]
>or to the default devices if application does not specify

I see. I am testing at this moment with `spotify` and `mpv`. I do not think I have ever tried to specify a device in these apps. That is probably why their streams are being redirected to the default device instead of the last used device set in Pavucontrol.

**Comment by wwmm** [comment]
@kawazoe the master branch has been updated. Now the metadata is set to null when effects are disabled using the app switch in EasyEffects window. The question now is how Discord is going to behave. You can test the master branch through the AUR pkgbuild.

**Comment by kawazoe** [comment]
@wwmm I have just tested your changes and they do fix the issue that I have been having!

**Comment by kawazoe** [comment]
Just a quick question. After switching to the AUR build ( `easyeffects-git-6.1.5.r231.gda287d7b-1` ) most of the effects just stopped working. They still appear to connect correctly in pipewire's graph, but they don't show any activity on the VU meters. Some still work fine though. For instance, the Noise Reduction effect seams to work, but the Equalizer doesn't. Is this a known issue of this build?

**Comment by wwmm** [comment]
>Is this a known issue of this build?

No. Although I do not use the AUR package I use the master branch everyday for testing purposes. As long as all the dependencies are installed all plugins should work. Try to run in debug mode https://github.com/wwmm/easyeffects/wiki/Reporting-Bugs#basic-logs so you can see if something weird is going on.

**Comment by kawazoe** [comment]
Thanks! Ok I didn't noticed that most dependencies that comes with the community package aren't in the AUR one. I'm missing LSP so that's probably what's going on. I expected them to not show up in the list if the dependencies where missing and didn't really pay attention to that because of it. My bad!
