### ISSUE TITLE
Inform the user about an invalid preset.

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1528]
I think EasyEffects could implement a system to warn the user about an invalid/corrupted preset loaded in the presets menu.

As we saw in #1524, an invalid preset can be inserted into the list and the user does not know which is the reason why it's not loaded after clicking the "Load" button.

Maybe showing a dialog, warning the user that the preset could not be loaded because it's invalid or corrupted, gives a suggestion to the user to check the file or redownload it in a correct way rather than blaming the application or opening a new ticket in the issue page.

I don't know if EasyEffects ever used a dialog widget to show a message. It could be also tricky to implement because we should show it only when the window is opened, excluding the cases when the preset is autoloaded or switched while the window is closed.

**Comment by wwmm** [comment]
>I don't know if EasyEffects ever used a dialog widget to show a message. It could be also tricky to implement because we should show it only when the window is opened, excluding the cases when the preset is autoloaded or switched while the window is closed.

I agree. It may be a little annoying. GTK has some overlays that can be used for this kind of message instead of a dialog but the annoying part is exactly the fact we can run in the background. I think that at least for now the work in your last PR may be enough. At least now the logs will show something about it :-). And as far as I remember issues about preset parsing problems are rare.

**Comment by wwmm** [comment]
I think we can close this. We have dialogs for presets errors now.
