### ISSUE TITLE
For the compressor, have a bidirectional mode (like "loudness equalization" in Windows).

### ISSUE THREAD

**Issue by DavidSmolinski** [wwmm/easyeffects#1533]
For the compressor, the mode dropdown gives you unidirectional options. "Downward" makes loud sounds quieter. "Upward" and "boosting" makes quiet sounds louder.
You should be able to have a bidirectional mode ("downward" and "upward" at the same time). In Windows, "loudness equalization" is supposed to do this. There should be a preset for this, so users don't need to know what settings to use.

**Comment by wwmm** [comment]
The compressor we use is a third party plugin developed by another project (Linux Studio Plugins) whose focus is on music production. This kind of feature can not be implemented on our side. The plugin code has to implement and expose
such a control.

What you are proposing is to some degree done by the autogain plugin. Like any other automatic volume control it is not perfect but at least to me it works decently in almost all situations. If you want loudness equalization curves on top of it the loudness plugins will have to be used. But it is not going to be a "plug and forget" process because it is another plugin where the author target audience is quite different from most EasyEffects users. 

>You should be able to have a bidirectional mode ("downward" and "upward" at the same time). In Windows, "loudness equalization" is supposed to do this

I have my doubts this is what windows is really doing. That is not what the expression "loudness equalization" usually means. There is probably loudness equalization curves https://en.wikipedia.org/wiki/Equal-loudness_contour being applied at some point. And besides this compressors need a threshold to work. Be it in upward or downward mode. Without automatically adjusting it somehow you will have very different results depending on the average signal level. There is definitely more than just a combination of downward and upward compression being done in windows. But as it is a black box we will never know.

In any case like I explained before changing third party plugins code is out of our reach. So I will close this issue.
