### ISSUE TITLE
Cannot figure out how to record speaker sounds with ffmpeg when EE is running

### ISSUE THREAD

**Issue by Rabcor** [wwmm/easyeffects#1560]
### EasyEffects Version

6.2.5

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

When easyeffects is not running I can easily make ffmpeg record system sounds with:

```
ffmpeg -f pulse -i alsa_output.pci-0000_00_1f.3.analog-stereo out.wav
```

however when easyeffects is running that will not work, the whole `-f pulse` setting gets broken it seems, now i don't know if that qualifies as a bug or something unfixable, but the net result is that the only sound i'm able to record with ffmpeg is my mic osunds using:

```
ffmpeg -f alsa -i plughw:0,0 out.wav
```

Now it stands to reason that there should be a configuration using the `-f alsa` setting that i can use to record the system sound but I've spent many hours over two days looking for one with no success (both via websearches and via guesswork) and i'm at my wit's end here since I would really like to get this working, preferably with easyeffects running (I don't particularly care if it's the easyeffect modified sound that gets recorded though, just that the sound gets recorded at all)

### Expected Behavior

`ffmpeg -f pulse` configurations should work.

### Additional Information

 I'm not entirely sure if this qualifies as an easyeffects issue (a side effect of easyeffects it sure is though), or if i'm just going crazy and stretching definitions seeking help wherever i can think of.

**Comment by wwmm** [comment]
As far as I could see ffmpeg creates a record stream like any other that is visible in the `Recorders` tab of our microphone effects section. If you have `Process All Inputs` enabled or if PipeWire decides to move this streams to our virtual source for some reason you are not going to get what you want.

I think the only way to workaround this is trying to blocklist ffmpeg streams in our input effects section.

**Comment by Rabcor** [comment]
Oh man this worked! Finally! Thanks man!

**Comment by wwmm** [comment]
At least in our current master branch a stream that records from monitor devices like this one from ffmpeg should be automatically ignored. That is because of a workaround for the OBS problems. Some information about it can be seen at #1541. But after some investigation I noticed that in the ffmpeg stream PipeWire does not set the property
```
stream.capture.sink = "true"
```
As far as I could understand this property should be set to any stream that records from sink monitors. PipeWire does that to the OBS stream. But for some reason I do not understand it does not do the same with ffmpeg. Maybe ffmpeg is doing something odd. Maybe it is a PipeWire bug.

**Comment by Rabcor** [comment]
That's good to hear, i'm just real happy to have a solution and being able to record sound now :+1:
