### ISSUE TITLE
Showing info messages to the user

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1607]
Sooner or later we should add a way to show the user some messages/information like in a dialog box.

We could use Adwaita [Toast](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.Toast.html) or [ToastOverlay](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/1-latest/class.ToastOverlay.html). We already use the warning messages, but those are for debugging purpose and the user usually don't read them because they did not start the application through the command line.

This could be useful for various things we already discussed in other issues. The first ones that comes in my mind:

- informing about a failing in loading a preset
- informing about a wrong locale which causes the inability of all spinbuttons

The problem is that they should have a visible window to be shown, but we might trigger them while the service is running and the window is hidden. So we have to find a way to detect if the window is visible or not. I though something like 

```
if (window_pointer == nullptr) {
  return;
}

show_toast();
```

But don't know if it's really possible,

Regarding the Toast construction, we could define an helper which takes a string as an argument and construct the widget at the moment. That string will be also translatable. Maybe additional optional parameters could be added if we need to automatically hide the Toast (specifying the timeout) or let it close by the user.

**Comment by wwmm** [comment]
>The problem is that they should have a visible window to be shown, but we might trigger them while the service is running and the window is hidden.

Assuming we find a decent way to make the signal connections it should not be a problem because the connections would be made only if the window is created. The problem is where to make the connections...

**Comment by vchernin** [comment]
Toasts are nice but I think for errors requiring the user to be aware, like a preset not loading maybe a [GtkMessageDialog](https://docs.gtk.org/gtk4/class.MessageDialog.html) would be better. It is much more visible and they can show more information. I used one for the the portal errors that can occur in the Flatpak with the background portal.

**Comment by Digitalone1** [comment]
> > The problem is that they should have a visible window to be shown, but we might trigger them while the service is running and the window is hidden.
> 
> Assuming we find a decent way to make the signal connections it should not be a problem because the connections would be made only if the window is created. The problem is where to make the connections...

The main window should be involved somehow. But why the signal? Can't we use a method call? That would be a metter of exposing the object of the main window. Sorry if I'm wrong, but on GTK windowing system I still have to learn.

**Comment by Digitalone1** [comment]
> I think the main difficulty is that the 'elegant way" of doing this is showing the warning inside the main window. So checking if it has a null pointer and calling a separate code to show the warning is not going to be useful. Our main window code will need to receive some kind of signal with the warning message. The annoying part will be making these connections.

Making a call to a static method and checking if the class has a non null pointer? Like the singleton. Did you hear about them? Class with only one instance that track their pointer.

**Comment by Digitalone1** [comment]
> Toasts are nice but I think for errors requiring the user to be aware, like a preset not loading maybe a [GtkMessageDialog](https://docs.gtk.org/gtk4/class.MessageDialog.html) would be better. It is much more visible and they can show more information. I used one for the the portal errors that can occur in the Flatpak with the background portal.

No problem, that would be a secondary issue. Personally I like more adw toasts because they could be automatically hidden with a timeout value. But for long messages a GTKMessageDialog could be done.

**Comment by wwmm** [comment]
>But why the signal? Can't we use a method call? That would be a metter of exposing the object of the main window.

For the same reason we use signals to emit the level meter values or for the communication between the PipeWire manager class and the main window. We could not have used signals in each of these places but the problem is being forced to do exactly what you are considering doing. The locations emitting the information will need direct access to pointers related to the window. If we have to change the window object for some reason now we have to change many other places...

With signals the location emitting the information does not have to think about what is happening where it is being received. There is less coupling between what is happening in different places. The location emitting the signal does not care if the one receiving it has a null pointer or not.

>Making a call to a static method and checking if the class has a non null pointer? Like the singleton. Did you hear about them? Class with only one instance that track its pointer.

Sure but why passing pointers around when you can just connect to a signal? Trying to create singletons for the communication between different sections of the code feels like reinventing the wheel...

**Comment by wwmm** [comment]
>Personally I like more adw toasts because they could be automatically hidden with a timeout value. But for long messages a GTKMessageDialog could be done.

I have the same opinion on this. I think Toasts are better. But it could be a dialag.

**Comment by Digitalone1** [comment]
You're right. Signals are more appropriate for these cases.

**Comment by Digitalone1** [comment]
@wwmm Regarding #1642, the user cannot import an unsupported irs file, but they can place the same file in the irs folder and show it inside the `impluses_menu`. If the user tries to load it, the `file_name_label` shows an error message, so in this case we don't need a toast, we take advantage of that label using the error class.

Anyway I'd like to show a message informing the user why an irs file cannot be imported. Since the import is done through a popup menu, the best way could be to show a dialog message, but we can't do that because connecting signals from the `application_ui` to plugin instances is tricky, especially if they are multiple.

So a toast can be done in this case, but I'm in the `impluses_menu` and I need the pointer to the `convolver_ui` to get the toast widget. How can I take it? Should I use the `parent_instance`?

I didn't have time to test this, so I thought to ask here which is the best way.

**Comment by wwmm** [comment]
>How can I take it? Should I use the parent_instance?

I think that in this case the easiest thing to do is trying to load the dialog directly from the `convolver_menu_impulses` code. When it shows the "import preset dialog" it gets a pointer to the main window this way https://github.com/wwmm/easyeffects/blob/b2789245b36432e1ce1da5d54a463f90d1a2e2c0/src/convolver_menu_impulses.cpp#L82. You can just do the same thing and use `setup_simple_message_dialog(active_window, title, descr);` directly to show the warning dialog.

**Comment by wwmm** [comment]
What I am not sure is how this dialog is going to interact with the one for importing the file. The function that tries to load the impulse is executed inside the `GtkFileChooserNative` callback.

**Comment by Digitalone1** [comment]
Nice. I'll try to do that.

**Comment by Digitalone1** [comment]
> What I am not sure is how this dialog is going to interact with the one for importing the file. The function that tries to load the impulse is executed inside the `GtkFileChooserNative` callback.

If there's an issue with the dialog, can I just get the pointer to the convolver ui through `parent_instance`?

**Comment by wwmm** [comment]
>If there's an issue with the dialog, can I just get the pointer to the convolver ui through parent_instance?

I would have to take a look at it. But even if it is possible as the other dialog types `gtk_message_dialog_new` needs a pointer to a window object. The pointer to the conlvolver ui widget won't work.

I think you have all the pointers you need in the `convolver_menu_impulses` code. As the other files its data structure has a `self->application` member. I am just not sure if GTK is going to like the call to a dialog inside another dialog callback.

**Comment by wwmm** [comment]
>It's an issue with the translating service _(""), but only in ui_helpers. Why?

Maybe the compiler needs `#include <glib/gi18n.h>` in `ui_helpers.hpp`.

**Comment by Digitalone1** [comment]
> Maybe the compiler needs `#include <glib/gi18n.h>` in `ui_helpers.hpp`.

Yes, that was the reason.

**Comment by Digitalone1** [comment]
Completed by #1652.

**Comment by Digitalone1** [comment]
@wwmm [Here](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/ctor.Toast.new.html) is written that `title` string is `owned by the caller of the function`. Does this mean we have to free it after the toast dismiss?

In our case it's a reference to the string copy sent by the signal, so I suppose it's already freed before the dismiss. So is libAdwaita doing a copy here? Otherwise it shouldn't work...

**Comment by wwmm** [comment]
>[Here](https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/ctor.Toast.new.html) is written that title string is owned by the caller of the function. Does this mean we have to free it after the toast dismiss?

Yes in general but not in our particular case https://github.com/wwmm/easyeffects/blob/945d9a0b080047d225ec3879933c420fa9dc52a6/src/ui_helpers.cpp#L40. When they say something is owned by the caller we have to free it indeed. But in our case the `const char*` is coming from a `std::string` object. Once this object is out of the scope the `std::string` destructor will free the const char that was being used by `adw_toast_new`.

>In our case it's a reference to the string copy sent by the signal, so I suppose it's already freed before the dismiss. So is libAdwaita doing a copy here? Otherwise it shouldn't work...

Yes. In these cases where we pass a `const char*` to a gtk/libadwaita function and they say we are the ones responsible for freeing it it is because internally the function is creating a copy of the `const char*`. The same thing happens whe we pass a `const char*` to `std::string`. It creates a copy. We had some small memory leaks in the past because of this. That is why I call `g_free` here https://github.com/wwmm/easyeffects/blob/945d9a0b080047d225ec3879933c420fa9dc52a6/src/util.cpp#L243.

The reason why `std::string_view` is interesting in some cases is because it does not create a copy of the `const char*`. But unfortunately this is exactly the reason why we cannot use it in EasyEffects in many situations. Specially in the signals.

**Comment by Digitalone1** [comment]
Interesting, but now I have some doubts.

In some parts of the code we create new labels and use them, but we don't free them.

For example the labels in the excluded apps list. We append the widgets to the box and also in this case the data is owned by the caller.

Maybe the GTK objects have some mechanisms to free themselves when they go out of the scope?

**Comment by wwmm** [comment]
Oh... What is called is `gtk_widget_unparent` and not `g_object_unref`. Interesting... I wonder if at the end of the day this has the same effect of removing the reference from the widget. In their own code they do not free widgets added to a container.

**Comment by wwmm** [comment]
I was curious so I decided to take a look at GTK's code :smile: https://gitlab.gnome.org/GNOME/gtk/-/blob/main/gtk/gtkwidget.c#L5948. `gtk_widget_set_parent` calls `gtk_widget_reposition_after` that calls `g_object_ref_sink`. And `g_object_ref_sink` increases the widget reference count. What does not allow GTK to destroy the child that has been added to the widget.

Maybe the documentation says it is owned by us because it isn't actually freeing the object. It just removes the reference it added when becoming the parent of the widget. I imagine that there are situations where a reference could have been manually added to the widget before inserting it in the container. As the widget is being handled by the GTK's reference counting system it makes some sense for the docs to say they do not own the object.

**Comment by Digitalone1** [comment]
So it's not really clear if we have to free them? 

I'm asking this because I wanted to add the wrap property to the toast and it seems the only way to do this is calling `set_custom_title` which allows to append a custom label with wrap properties (but this method is only available in libAdwaita 1.2).

But is the new constructed label copied or not? It's not clear.

Another interesting thing is that the example in the Toast documentation is duplicating a string with the `g_autofree` macro. It's the first time I see this and that's a mechanism to free the object automatically.

**Comment by Digitalone1** [comment]
Okay. 

The documentation is here: https://gnome.pages.gitlab.gnome.org/libadwaita/doc/main/method.Toast.set_custom_title.html

**Comment by wwmm** [comment]
One way to double check when we have to manually remove an object reference is calling `g_object_unref` on them and watching what happens. If there is only one reference in the object what will happen is that GTK will free it while the thing is still being used. What usually leads to `GTK-Warnings` or even a segmentation fault.
