### ISSUE TITLE
can't close EQ band properties by clicking outside the menu

### ISSUE THREAD

**Issue by zurrty** [wwmm/easyeffects#1611]
### EasyEffects Version

6.2.6

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux (5.18.7-arch1-1)

### Describe the bug

after clicking any dropdowns under a band's settings in the equalizer (band type, mode, and slope), the menu doesn't close when i click outside of it. i can only close the menu if i press escape, or manually terminate the app.

this doesn't happen when adjusting the frequency or quality properties, only the dropdowns above them.

video:

https://user-images.githubusercontent.com/64922277/176773884-5311a64d-f597-4508-b84d-c0a64e02ba72.mp4

### Expected Behavior

normally when adjusting a band in the equalizer, i can close the menu by simply clicking outside of it.

### Debug Log

debug log didn't provide any output related to the issue

**Comment by wwmm** [comment]
Unfortunately it is a known problem with gtk4. Take a look at #1182 and #1179. In the case of the menus you can try to play with the option `Hide Menus on Outside Clicks`. It will avoid the lock but the downside is that you will only be able to close the menu if you click again on its button. This was the most I could do on my side. The real fix has to be done by the gtk4 developers. I think the related issues about these problems are still open in their GitLab page. If they are working on this or not I have no idea. I think more than one 1 year has passed since these problems were reported to them. For people on Xorg it is even worse than for the ones that like me use Wayland.

As we already have an older issue about this I will close this one
