### ISSUE TITLE
Migrate here the Flatpak update process

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1660]
As a reminder, @vchernin talked about this in another ticket. Triggering the update from here every time a new commit is added will help flatpak users to debug new features just like `easyeffects-git` package on AUR.

**Comment by vchernin** [comment]
Since a human is currently required to generate tokens on the flathub end, it isn't commonplace for apps to be able to push binary builds directly yet. 

CI artifacts (a `.flatpak`) here on master and PRs are fairly easy to produce though, I think I can discontinue the flathub-beta branch and instead point all testers here.

**Comment by vchernin** [comment]
This can be closed, I still have ideas for more testing and making flatpak builds more discoverable, but the core work is done. The flatpak manifests are maintained here and as little as possible is kept downstream. In the future perhaps we can push builds directly but this is a good enough setup for the time being.
