### ISSUE TITLE
Feature request: Auto gain bounds

### ISSUE THREAD

**Issue by road2react** [wwmm/easyeffects#1699]
Auto gain would be more optiminal with configurable bounds. 

For example, if an audio clip becomes quiet, auto gain turns the quiet noise into loud noise which could be avoided.

**Comment by wwmm** [comment]
Maybe instead of bounds that would be `2 controls` needing adjustments what we should do is allowing the loudness that we consider to be silence to be customized. The `EBUR128` standard considers signals below `-70 LUFS` as silence https://en.wikipedia.org/wiki/EBU_R_128. So what I did in the autogain was disabling any gain correction when the `relative` and the `momentary` loudness are below `-70 LU`. Maybe allowing the user to set a higher threshold value for "silence" is enough.

**Comment by wwmm** [comment]
I have updated our master branch with a `silence threshold` control for our autogain plugin. While the momentary loudness is below this threshold no changes will be done to the current gain being applied to the signal level. I think this is enough for the users to be able to customize when the autogain should stop amplifying signals whose level is too low.
