### ISSUE TITLE
Inform the user about missing plugin 

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#1730]
As reported in https://github.com/wwmm/easyeffects/issues/1685#issuecomment-1194723147

Since we already have UI util to show toasts in the plugin interface, this should be easily implemented.

The big work is adding an overlay to all existing effects. At the moment only few of them have it for showing toasts.

We should also format the message including the package needed for the effects. Something like:

```c++
_("%s is not installed on the system. This effect in not available.", "Linux Studio Plugins");
```

**Comment by wwmm** [comment]
>The big work is adding an overlay to all existing effects. At the moment only few of them have it for showing toasts.

Maybe we should take a completely different approach in this case and not even showing the plugin controls if the required dependency is not available. For example instead of directly doing calls like
```
auto* box = ui::compressor_box::create();
```
inside `plugins_box.cpp` we could first check through the filter instance that is available there if the dependency was found. If not we do something like `auto* box = create_box_with_message_to_the user(plugin_name);`.

this way we can create only one function to generate the "error message" widgets and passing the plugin name as argument we can customize the error message like you are suggesting. The advantage of this approach is not needing to create overlays for each plugin.

**Comment by wwmm** [comment]
>The advantage of this approach is not needing to create overlays for each plugin.

And not wasting memory and processing time creating widgets that are not going to be useful anyway.

**Comment by Digitalone1** [comment]
I already did with the overlay. 

The overlay is not a big issue since we could have the need in the future to show toasts in the plugin interface, so having it inside every effects is not a problem.

The idea of showing only the message and not the controls is good. At the moment I did with the toasts, it remains only to test, but it can be modified to show only the message.

There's a problem with gettext including the plugin package inside the translation strings because it does not have a way to format strings. The method with `%s` works only with `printf` that we don't use anymore because we went with `fmt::format`.

But doing the same with fmt I have to format the string with `fmt::runtime` because gettext does not provide a constexpr string which is needed by `fmt::format`.

**Comment by Digitalone1** [comment]
Unfortunately I failed with my implementation. 

I though as we already have multiple instances where the plugin is built when needed and if the lv2 wrapper is not found, it emits a signal to show the toast in the relative interface.

Unfortunately the single plugin instance is made at startup, so the interface built afterwards never catch the signal and the toast is never shown.

I have to rework it.

**Comment by Digitalone1** [comment]
So I will make a draft pull request with all the data prepared to show the alerts. Then we decide if going with toasts or hiding the interface ui.

**Comment by wwmm** [comment]
>But doing the same with fmt I have to format the string with fmt::runtime because gettext does not provide a constexpr string which is needed by fmt::format.

It is fine. unless we write a template function to deal with string joining at compilation this will be done at runtime anyway.

>Unfortunately the single plugin instance is made at startup, so the interface built afterwards never catch the signal and the toast is never shown.

Yes. I think signals are not going to be a good fit in this case. The filter classes are created before their corresponding widgets. As we already have to get a pointer to the filter class anyway it is better to just write a getter that returns if `package_installed` is true or false.

>Then we decide if going with toasts or hiding the interface ui.

Although things will work with toasts as they are usually meant for temporary messages I think that a permanent warning window fits better for the task.

**Comment by wwmm** [comment]
>I think that a permanent warning window fits better to the task.

And as we already do this for empty lists it makes some sense to do the same when the plugin is not available.

**Comment by Digitalone1** [comment]
We do it with overlays. But if we don't want to load the plugin box we should create a new box with a custom message.

What do you suggest?

**Comment by wwmm** [comment]
>We do it with overlays.

Oh. I forgot about this. In the listviewes that can be empty there is an overlay. Now that I am thinking again about it the lists are a slightly different situation. Once the list is empty there is no widget there anyway so from this point of view "there is no widget loaded for no reason". In the case of missing libraries it is different. Gtk will construct and use additional memory for all the widgets. Even if they are hidden by the overlay. From a performance point of view it is a little dumb because we go through all the work involved in creating all of them for nothing. That is exactly what we do right now and it is something that has been bothering me for a while. So if we are going to change this, in my opinion, it makes sense to try to do it in a smarter way.

I think that we can keep the overlay because as you said before they can be useful for other reasons. But for this particular case I think we can just call `gtk_builder_new_from_resource` like we still do in some places. In the xml we define a GtkBox and inside of it an `AdwStatusPage` for the warning message.

I will use the `autogain` as an example. We could do something like this
```
for (const auto& name : plugins_list) {
    if (name.starts_with(tags::plugin_name::autogain)) {
      auto plugin_ptr = effects_base->get_plugin_instance<AutoGain>(name);
      
      GtkBox * box = nullptr;

      if(plugin_ptr->package_is_installed()){
           auto* box = ui::autogain_box::create();
      }else{
          box = ...; // here we create the warning message through the xml loaded by gtk_builder_new_from_resource
      }     

      ui::autogain_box::setup(box, plugin_ptr, self->data->schema_path + name + "/");

      gtk_stack_add_named(self->stack, GTK_WIDGET(box), name.c_str());
    } else if
...
```

**Comment by Digitalone1** [comment]
Okay, I think that the autogain setup has to go inside the conditional statement.

It seems overkill to me just doing a new xml builder for a box containing only an adw status page.

We can do it with a UI util returning a box with a status page appended. We pass it also the names of the plugin and the package, so we can construct the formatted translated string to append to the status page.

The only concern is if GTK is smart enough to destroy the box avoiding memory leak when the plugin is removed from the list. I don't know.

**Comment by wwmm** [comment]
>Okay, I think that the autogain setup has to go inside the conditional statement.

Yes. I forgot that the setup function probably will crash with a generic box.

>We can do it with a UI util returning a box with a status page appended. We pass it also the names of the plugin and the package, so we can construct the formatted translated string to append to the status page.

Ok. I do not see any problem in writing this code directly in C.

>The only concern is if GTK is smart enough to destroy the box avoiding memory leak when the plugin is removed from the list. I don't know.

It will free it because the GtkBox reference count will go to zero once it is removed from the gtkstack.
