### ISSUE TITLE
crystallizer and exciters

### ISSUE THREAD

**Issue by idkman2021** [wwmm/easyeffects#1903]
what does the crystallizer value mean and what do exciter harmonic mixing values mean

**Comment by Digitalone1** [comment]
> what does the crystallizer value mean and what do exciter harmonic mixing values mean

Please read the manual. It's written there.

> The Crystalizer plugin can be used to add a little of dynamic range to songs that were overly compressed. The signal is split in multiple bands to which different intensities can be applied in order to alter the overall dynamic range.

> Blend Harmonics - The "colour" (or octave) of the harmonics.

**Comment by wwmm** [comment]
>what does the crystallizer value mean

As explained in the manual the crystalizer is a poor man attempt to add artificial dynamic range to songs that were too compressed. It is not a restoration algorithm. It is just a `peak enhancer` whose strength is set by each band control.

>what do exciter harmonic mixing values mean

The bass enhancer and the exciter works based on similar principals. When we here a harmonic we may have the feeling that the fundamental frequency is there. In the case of the bass enhancer instead of trying to directly amplify the fundamental frequency it adds some of its harmonics (higher frequencies that are a multiple of it) to the signal. This is done in a clever way that makes us think that the bass fundamental frequency was actually amplified. Something similar is done by the exciter but at the higher frequencies. The `Blend harmonics` control is configuring which of these harmonics will have more influence in the output signal.

**Comment by idkman2021** [comment]
> 

what is the difference between crystallizer positive and negative values

**Comment by wwmm** [comment]
>what is the difference between crystallizer positive and negative values

St the end of the day the decibel values become a linear value in the peak enhancement algorithm. `Do not` think about them in the same way as an equalizer band gain.

**Comment by idkman2021** [comment]
> > what is the difference between crystallizer positive and negative values
> 
> At the end of the day the decibel values become a linear value in the peak enhancement algorithm. `Do not` think about them in the same way as an equalizer band gain.

yes well negative values seem to make the freq louder just like positive ones so still unsure what the difference is. Frequency of harmonics?

**Comment by wwmm** [comment]
>yes well negative values seem to make the freq louder just like positive ones so still unsure what the difference is. Frequency of harmonics?

The scalar value related to the decibel gains is just controlling the intensity of the peak enhancement. The lower the value the less the signal is changed. It is not related to harmonics.

**Comment by wwmm** [comment]
>right, but it has negative values, pretty sure it goes from -40 to +36. Why not 0 to 76? 

`-40 dB` will correspond to a scalar value of `0.01` and the maximum value of `32 dB` to a scalar value of `39.8`. If only positive decibel values are used it is not possible to have scalar values below `1`. 

>And -40 actually makes it louder

The peak enhancement is changing the signal peaks. So depending on the situation the perceived signal loudness may be louder. It will depend on by how much the peaks  are being increased. But it does not make sense  that lower values cause louder sounds. It is not what I see in my tests. And looking at how the scalar value is used in the equation the lower the scalar value the less changes are done to the signal https://github.com/wwmm/easyeffects/blob/c9e6b0c271e53442bc7b8587fe092a7dde3545c0/include/crystalizer.hpp#L186.

**Comment by wwmm** [comment]
>And looking at how the scalar value is used in the equation the lower its value is the less changes are done to the signal 

Unless you are listening to a peculiar type of signal where subtracting by a less intense second derivative actually makes strong peaks to stand out even more. But I have never seen this happening.

**Comment by HubKing** [comment]
Where's "the manual"? I had searched Google, and this page was Google's top result. Is the "help" screen below the manual? It doesn't seem to say much.

![image](https://github.com/wwmm/easyeffects/assets/10900489/3da2be50-e8be-4348-a2ad-19e2c4add431)

**Comment by Digitalone1** [comment]
> Unless you are listening to a peculiar type of signal where subtracting by a less intense second derivative actually makes strong peaks to stand out even more. But I have never seen this happening.

Did you try with the white noise test signal?

It's the first time in years I tested the crystalizer deeply. I don't understand its core working method because of the math functions involved, but I usually try to make an idea testing with the white noise.

It's weird to me that bypassing all the bands except the last one, I get +9 on the level meter, no matter what intensity I set on that last band. I expected to see something like +1 on -40 and +10 on 32.

But I also noticed that bypassing all the bands except the first one, the signal is basically the same, no matter what intensity I set.

Is the white noise a specific type of signal which triggers this side effect? On crystalizer default values, the white noise peaks at +9 or +10 while it stays around 0 on bypass. That's because the higher bands get always amplified. If you bypass them, the peak is reduced.

Based on what I tested, I have to say that listening compressed music with the crystalizer (on default values) makes the sound better (if not equal), even if I don't see very high changes on the output level meter. But having +9 on the white noise makes me wonder: are there edge cases where the signal is simply amplified, no matter which intensity is set? +9 is a lot.

**Comment by wwmm** [comment]
> I don't understand its core working method because of the math functions involved

This is what I've implemented https://terpconnect.umd.edu/~toh/spectrum/ResolutionEnhancement.html. The general idea is to do small enhancement to the peaks based on the signal second derivative.

>Is the white noise a specific type of signal which triggers this side effect? 

I do not think white noise is a good choice to evaluate an algorithm based on the signal derivatives. By its very nature the noise is chaotic. The derivatives are probably changing by insane amounts from one instant to the other. A superposition of sine waves feels like a better choice.

>Based on what I tested, I have to say that listening compressed music with the crystalizer (on default values) makes the sound better (if not equal), even if I don't see very high changes on the output level meter. But having +9 on the white noise makes me wonder: are there edge cases where the signal is simply amplified, no matter which intensity is set? +9 is a lot.

My intention with this algorithm was to reduce a little the excessive compression some songs are recorded with. It is not possible to undo what was done in the studio without knowing exactly what was done and having the inverse operations for each step. And even if this is known it may be impossible depending on what was done. So the most that the crystalizer can do is artificially increase the dynamic range. 

When I was implementing the algorithm I've noticed that using too much enhancement deforms the signal in very undesirable ways. So the idea is setting the intensity to as little as possible. Open a terminal inside the `util` folder in EE sources and run the script `crystalizer.py`. It will show a chart where the original and the processed signal are compared. The `aggressive` mode in the legend does not exist anymore. But it will give you an idea about what can happen to the signal if too much intensity is used.

If I remember well high intensity is specially bad the higher the frequencies. That is why I've made a default setting that descreases the intensity for higher frequency bands.

**Comment by Digitalone1** [comment]
https://github.com/wwmm/easyeffects/commit/83b9d5cc5f53ad6ce2a1094a846d9d8317b67869

@wwmm So the Crystalizer was not working in the way it was intented for all this time?

**Comment by wwmm** [comment]
> So the Crystalizer was not working in the way it was intented for all this time?

Not exactly. When EasyEffects was restarted the right values were applied during the initialization phase. The bug affected the on the fly update of the intensity when the slider was moved. What still is a big problem. But the plugin was not totally broken.

**Comment by Digitalone1** [comment]
> > So the Crystalizer was not working in the way it was intented for all this time?
> 
> Not exactly. When EasyEffects was restarted the right values were applied during the initialization phase. The bug affected the on the fly update of the intensity when the slider was moved. What still is a big problem. But the plugin was not totally broken.

Okay. I think the libadwaita version deserves this fix in the next release (which will be the final for GTK).
