### ISSUE TITLE
[Request] Expander/Gate support for microphone

### ISSUE THREAD

**Issue by nohatssir** [wwmm/easyeffects#191]
It would be nice if we could have expander/gate effect for the microphone. It's very helpful for filtering out and reducing background noise and other unwanted sounds below a certain threshold.

**Comment by wwmm** [comment]
Do you want an gate and an expander or only the gate? Linux Studio plugins have both plugins and could add them:

[gate](http://lsp-plug.in/?page=manuals&section=gate_stereo)
[expander](http://lsp-plug.in/?page=manuals&section=expander_stereo)

**Comment by Bleuzen** [comment]
Just my two cents..
I like to keep my system 'clean' and install as less (AUR-)packages as possible.

At least for the Gate:
Calf also has a Gate. The Calf plugins are one of the best for Linux in my opinion (and I already have them installed anyway and they are in the Arch repos).
So why not use the Calf Gate? ;)

But yeah, a Gate for the mic is a pretty good idea.
And because I don't want to open a new issue just for a single effect..
Could you please also add the Calf Deesser for the mic? It would make sense after the Equalizer.

**Comment by Bleuzen** [comment]
Well, I'm not an expert, but when I produce music / record vocals, I always put the Gate as the first effect. Because the reason to use it is to cut sounds that are not needed .. it would make not that much sense to process them with all the other effects.
So I would add the Gate as the first, even before the Limiter.

**Comment by nohatssir** [comment]
Currently I use the gate from from Calf so that would probably work for me. Don't know if we need both an expander and a gate. Start with one and decide the other one later. Both have their uses I think even if there's only minor differences between them. :)

In my chain current chain in Calf the gate is first since I don't want any noise after that so to me that makes most sense.

**Comment by wwmm** [comment]
I agree it does not make sense to put the gate after other effects. I was considering to put it after the limiter to avoid any possibility of clipping. Depending on the amount of amplification of the input signal its input could be saturated. Or is this an very unusual situation in this case?

**Comment by Bleuzen** [comment]
The Gate not saturates the input. It won't get louder.
So clipping should be no problem, you can add it before the Limiter.

**Comment by wwmm** [comment]
I was thinking about the input of the gate being saturated by the mic signal sent by pulseaudio. If I remember well Pulseaudio allows software amplification the mic signal.

**Comment by Bleuzen** [comment]
Yes, you can set the input level in PulseAudio. If it clips, a user can simply lower this.

**Comment by wwmm** [comment]
Master branch has Gate and Deesser plugins from Calf Studio in the mic pipeline. Could you test it?

**Comment by nohatssir** [comment]
I've been trying the gate with a build from a few days ago and it seems to work.

**Comment by Bleuzen** [comment]
Deesser also works, than you!

**Comment by Arecsu** [comment]
Hi! I'm resurrecting this thread to make a request for an expander plugin effect in the input chain! The gate and everything else works wonderfully. 

Thing is: a gate is not an expander, and I feel the need to have an expander in the input chain. If I'm talking while I'm writing something with the keyboard, the gate won't turn down the volume of my keystrokes. Same goes for other ambient noises and things happening around. The gate will just work to filter noise below a certain threshold. An expander works really great for the purposes mentioned.

Thank you so much for your work!

**Comment by RichardFevrier** [comment]
Now that multiple filters instances are implemented in `master` the last thing missing to make it usable for voice production to me is the `gate` implementation 🙂

Thank you a lot for all the work already done @wwmm 🎉

**Comment by wwmm** [comment]
>Now that multiple filters instances are implemented in master the last thing missing to make it usable for voice production to me is the expander implementation slightly_smiling_face

I think that now it is just a matter of having enough free time. So I remember in the future the expander we should be integrating in EasyEffects is https://lsp-plug.in/?page=manuals&section=sc_expander_stereo. If we are lucky most of what was done to integrate the sidechain compressor can be reused for the expander.

**Comment by danielzgtg** [comment]
Hi, I'm looking for a [downwards expander](https://music.stackexchange.com/questions/25472/how-to-remove-reverb-from-a-recording-of-a-voice#comment49147_33637). My use case would involve the speakers not the microphone. My professor's lectures have a lot of reverb in them and I want EasyEffects to remove this reverb so that these lectures are easier to listen to.

**Comment by wwmm** [comment]
Implemented in our master branch
![Screenshot from 2023-07-31 13-20-35](https://github.com/wwmm/easyeffects/assets/16225172/167e0132-b293-4594-b89b-e511ff7be964)
