### ISSUE TITLE
Autogain - Silence feature adjusts Output Gain despite silence

### ISSUE THREAD

**Issue by polarathene** [wwmm/easyeffects#1951]
### EasyEffects Version

7.0.0

### What package are you using?

Arch (easyeffects)

### Distribution

EndeavourOS

### Describe the bug

I have a Gate effect enabled, thus there is no signal that should affect Autogain effect that is immediately after it.

When I add an Autogain, initially disabled, regardless of what the Silence threshold is set to and a Gate effect prior that is actively muting the audio Autogain is to respond to... **As soon as the Autogain effect is enabled, the Output Gain jumps to `35.89`.**

My understanding of Silence was that this should not happen. It also remains impossible to reset Output Gain to 0 as neither of the reset buttons adjust Output Gains value when clicked. Thus I used the 7.0.0 feature to add another Autogain effect which does start Output Gain at 0 while disabled.

### Expected Behavior

Autogain should not be boosting Output Gain from 0 when enabled if the input signal is silent.

**Comment by wwmm** [comment]
>When I add an Autogain, initially disabled, regardless of what the Silence threshold is set to and a Gate effect prior that is actively muting the audio Autogain is to respond to... As soon as the Autogain effect is enabled, the Output Gain jumps to 35.89.

For some reason I can not reproduce this on my computer. I've put a gate before the autogain and set the gate threshold to `0 dB` to make sure there would be only silence after it. The autogain `output gain` stayed at 0 dB.

>Autogain should not be boosting Output Gain from 0 when enabled if the input signal is silent.

What the silence function actually does is comparing the desired threshold to the current `momentary loudness`. If the momentary loudness is below the silence threshold the autogain does not change the current value of the output gain. In other words the current gain factor is kept until the momentary loudness is again higher than the silence threshold. Resetting the gain to its default value after every time "silence is detected" will cause undesirable volume jumps in some situations. For example when watching a movie and a large period of silence happens. Once the sound is intense enough again we expect the volume to be were it was before.

**Comment by polarathene** [comment]
**Summary**

- Presumably `Output Gain` is jumping from the initial `0` value when the effect is enabled, before having time to settle (_around `-80db` for me if I have no Gate/Reduction active_).
- It is a minor issue now, but seems odd that the "Reset" button does not reset `Output Gain` to `0` (_maybe it does and the previous point applies here too since "Reset" enables a disabled effect?_).

---

<details>
<summary>Verbose response with images</summary>

Adding the effect disabled (_seems to rely on what the previous effect state was, so I added an Autogain, disabled it, then trashed it, now the next Autogain I add is disabled properly_):

![Screenshot_20221108_182721](https://user-images.githubusercontent.com/5098581/200482409-54a31371-a8d0-414c-a02d-9d8ccb4236cc.png)

Then just by pressing the bottom "Reset" button here then changes all these values (_**EDIT:** I noticed that "Reset" also enables the effect if it's disabled_):

![Screenshot_20221108_182739](https://user-images.githubusercontent.com/5098581/200482458-2242741c-91d3-41f7-8f21-273eaff7de93.png)

Prior to that reproduction, I do recall seeing some times when I added the effect it went with `-747` as the `momentary loudness`, and enabling the effect made the value grow (_in negative amount_) until `-inf`. I was going to try reproduce that but using the bottom "reset" button shows the issue well?

Output Gain should not boost, but presumably does because `momentary loudness` initialized at `0`? (_even though the effect wasn't enabled yet_)

---

> Resetting the gain to its default value after every time "silence is detected" will cause undesirable volume jumps in some situations.
> For example when watching a movie and a large period of silence happens.

This makes sense, but my usage is with the Input mic, not for speakers like that example.

The Silence feature works well when the threshold is set, but without the ability to reset Output Gain, if the noise is not filtered/muted via Gate or Noise Reduction effects prior, the Output Gain remains high and boosts those undesirable sounds until a loud enough one exceeds that threshold to "fix" it.

With Silence threshold (paired with Gate and Noise Reduction) my issue with Autogains Output Gain is effectively resolved. However I don't see why "Reset" should not also reset the Output Gain, or "Reset History" if that seems more suitable. The example given isn't one that I imagine you'd have by resetting the effect state explicitly, if you're doing that you probably want a clean state, and not Autogain amplifying a signal by a much larger amount until something above the threshold is received to set it to an appropriate Output Gain value (_from then on, it should be fine now_ :man_shrugging: ).

I thought I could work around that by adding the Autogain effect _disabled_, and later enabling it, but as shown it boosts right away.

---

Output Gain that is desirable level for me is just under 20 instead of the 40-ish shown earlier. Here it is with Noise Reduction active:

![Screenshot_20221108_185513](https://user-images.githubusercontent.com/5098581/200486416-df65a4b3-1300-4e6d-8a43-59104630ce67.png)

and then with the Gate active, it changes and settles to this:


![Screenshot_20221108_185707](https://user-images.githubusercontent.com/5098581/200486499-012f2c56-e941-40a2-906b-7e756b1cd25a.png)

---

Disabled the Gate and Noise Reduction, then clicked "Reset" button:

![Screenshot_20221108_185850](https://user-images.githubusercontent.com/5098581/200487038-f8b993a1-92f7-47f1-9e08-53c50e0f098f.png)

And now, I set the threshold to `-70db` default, and introduced some noise for it to boost excessively. Then set it back to `-40db`, I snapped my fingers by the mic, and presumably due to the history this **only reduced Output Gain down to `29`**. So I need to tweak settings more, reset history or accept that the boost will remain (_generally not an issue with the Gate while it's closed or speaking for a while_)

![Screenshot_20221108_190233](https://user-images.githubusercontent.com/5098581/200488145-5b3bfa28-c1dd-478a-aa52-034a529dc3d5.png)

</details>

It would be nice though, if one could actually reset to `Output Gain` to `0`, rather than required to making loud enough noises to get it to adjust appropriately. At least while experimenting, the inability to get a clean state is a bit of a hindrance?

**Comment by wwmm** [comment]
> but seems odd that the "Reset" button does not reset Output Gain to 0 (maybe it does and the previous point applies here too since "Reset" enables a disabled effect?).

I agree that the current reset button may be a little misleading. What it actually does is resetting the settings that are saved to the database. Mostly the same that are saved to preset files. In the particular case of the autogain plugin what I can do is making the `reset history` button also reset the current gain factor. I will try to remember to to this.

>Output Gain should not boost, but presumably does because momentary loudness initialized at 0? (even though the effect wasn't enabled yet)

The library libebur128 that is used by the autogain plugin calculates the momentary value using a time window of `400 ms`. What is specified by the EBUR128 standard if I am not mistaken. So depending on how short are of the transient noises being given to the plugin the momentary value may not have stabilized yet. But it should cause the signal to be boosted only if the estimated loudness is below the target loudness.

>Adding the effect disabled (seems to rely on what the previous effect state was, so I added an Autogain, disabled it, then trashed it, now the next Autogain I add is disabled properly)

I did not pay enough attention to this part of your procedure before. Due to some technical difficulties removing the plugin does not destroy the filter object. The filter is removed from the window, the effects pipeline and is also disconnected from PipeWire's graph. What makes it invisible to programs like Helvum. But the filter object and the structures and data inside of it are not destroyed. As no CPU will be used and the memory consumption is negligeable this is fine is almost all situations. But in the tests you are doing you may have some old data and history in the plugin once you put it back in the pipeline.

In the future I expect we will be able to fully destroy the filter object. Last time I tested it was almost fine enabling this. The reason why I am not allowing this yet is because some "unrealistic tests" still can cause crash in some corner cases. For example if the user decides to switch between presets very fast. I know no normal people will do this. Specially because to cause the crash I had to switch between presets a lot and very fast. So for most people nothing bad would happen. But I think it is better to be on  the safe side and only enabling the filter object to be destroyed once I can not cause a crash. No matter how unrealistic the test is.

**Comment by wwmm** [comment]
`Reset History` now resets the current gain. I guess it is the most that can be done to mitigate this problem.
