### ISSUE TITLE
Why it is not advised to set easyeffects' devices as the default ones?

### ISSUE THREAD

**Issue by coordinatio** [wwmm/easyeffects#2028]
Hello there!

I use easyeffects to suppress echo and noise during videoconferences. The echo cancelling requires, if I understand things correctly, for all output to be forwarded to the virtual sink. Otherwise, sounds produced by system notifications and other programs would not be filtered from the videoconference sound input.

How can I achieve that except by setting the easyeffects' virtual devices as the default ones?

Actually, I have been using the program in that mode for a long time and was pretty happy with the result. Now I face [that](https://github.com/wwmm/easyeffects/issues/1817) change and have to employ trickery to be able to control system volume.

Would you please advise me how is it intended to achieve the described above echo cancelling effect in the right way, without settings the virtual devices as the default ones?
And why it is not advised to set easyeffects' devices as the default ones?

**Comment by wwmm** [comment]
>And why it is not advised to set easyeffects' devices as the default ones?

There is a detailed discussion about this here https://github.com/wwmm/easyeffects/discussions/1836. Long story short there is no need to set EasyEffects devices as default in 99% of the cases. And depending on the order PipeWire initializes its objects in some systems EasyEffects may be completely broken if you set its devices as the system default.

>The echo cancelling requires, if I understand things correctly, for all output to be forwarded to the virtual sink. Otherwise, sounds produced by system notifications and other programs would not be filtered from the videoconference sound input.

No. The echo canceller probe is linked directly to the soundcard device monitor ports and not to our virtual device monitor ports. If your microphone is being processed by EasyEffects echo cancellation should work even if everything is playing directly to your soundcard instead of our virtual sink. That being said our echo canceller has other limitations to have in mind https://github.com/wwmm/easyeffects/issues/951.
