### ISSUE TITLE
Noise Reduction plugin does not remove speaker/headphone output from microphone input

### ISSUE THREAD

**Issue by syphoxy** [wwmm/easyeffects#2092]
### EasyEffects Version

6.3.0

### What package are you using?

NixOS

### Distribution

NixOS 22.11

### Describe the bug

Noise Reduction module does not remove speaker output from microphone. As far as I can tell, this module should be similar to what NoiseTorch does and NoiseTorch does subtract speaker/headphone output from the microphone.

**Comment by wwmm** [comment]
>Noise Reduction module does not remove speaker output from microphone. 

Noise removers do not no this. This is the `echo canceller` task.

>NoiseTorch does subtract speaker/headphone output from the microphone.

Probably because it is enabling the server built-in echo canceller. As NoiseTorch does not have to manage an effects pipeline it can make use of it. Unfortunately in EasyEffects we have to provide our own solution for echo cancellation. But as you can see at #951 it has some limitations. I hope to be able to improve it in the future.

**Comment by wwmm** [comment]
>I tried using the Echo Canceller task but it didn't do the job either. is there documentation on how to use it?

Besides the few things said by the `Speex` library developers https://www.speex.org/docs/manual/speex-manual/node7.html#SECTION00740000000000000000 I am not aware of more explanations about the echo canceller `frame size` and `filter length` parameters. But based on the discussion at #951 the main factor in this library performance seems to be the microphone signal level. When it is too strong it fails miserably. I have to see if there is something I can do to improve this.
