### ISSUE TITLE
Autoloading: default preset

### ISSUE THREAD

**Issue by malinges** [wwmm/easyeffects#2099]
While EasyEffects makes it very easy to autoload a given preset when a specific device is connected, doing the opposite (auto-reverting to a default / empty preset when this device is disconnected) is a bit cumbersome in comparison: EasyEffects doesn't seem to have any "default preset" concept, so the only way (that I could find) to get this behavior is to create an autoload rule with this default preset for every other single device that I own. As someone with quite a few USB & Bluetooth devices, this becomes tedious quite quickly. Having a default / fallback / catch-all preset that would be autoloaded for every device, but only if no other rule targets this specific device explicitly, would make this trivially easy. Is this a feature you'd consider for EasyEffects? Thanks in advance!

**Comment by wwmm** [comment]
I think that what is being asked here is the same as #1359. So it is better to close this issue and keep the discussion on #1359.

>EasyEffects doesn't seem to have any "default preset" concept

Although each plugin has default settings that can be loaded by resetting them the default (and only) behavior is saving to the database the current values and reloading them in the next startup. The reason is that the whole "autoload preset" idea came to be when this project was already doing lots of things. And restoring the last used settings is what the database we use is designed for.

>Having a default / fallback / catch-all preset that would be autoloaded for every device, but only if no other rule targets this specific device explicitly, would make this trivially easy. Is this a feature you'd consider for EasyEffects?

It is something that will have to be done eventually but I am not sure yet about how straightforward it is going to be. The whole autoloading code was written around the idea it should apply the preset if the current device name and hardware profile matches what was saved before. Forcing something to everything except a few is the opposite of what this code wa written for. So it will need some serious redesigning as well as support for configurations options for people that do not want/need this behavior.

**Comment by spikespaz** [comment]
Why would you close this if it is planned? The described feature would undoubtedly be the better way to do this.

1. Default preset is activated on startup.
2. If device is activated and matches an autoload config, switch to the autoload preset. If device does not match autoload preset, switch to default.

**Comment by teohhanhui** [comment]
> And most people do not even need this change considering that GSettings will already reload the last used settings anyway.

There is a serious UX problem with that. The last used settings could be anything, so essentially you'd be applying a random preset to a previously unknown device.

**Comment by wwmm** [comment]
>The last used settings could be anything, so essentially you'd be applying a random preset to a previously unknown device.

Although I understand what you are trying to say you are exaggerating the whole situation by a lot. It is not like a random number is generated at startup and the setting can be something the user has no idea about. It will be the last setting the USER configured there. What in some cases is exactly the behavior some people will be expecting.

**Comment by spikespaz** [comment]
Maybe you could expose that "history" to the user in a JSON file, and then I can set it read-only.

**Comment by teohhanhui** [comment]
Isn't it just gsettings?

**Comment by wwmm** [comment]
>because the last used preset could be anything, depending on which device was used last

The device only plays a role if the user sets an autoload profile. Thinking about the people that do not care about automatically loading a preset depending on the device. They will have the same settings all the time unless they touch the controls and change them.

>Isn't it just gsettings?

Yes. It is all in the gsettigns database. 

>Maybe you could expose that "history" to the user in a JSON file, and then I can set it read-only.

Unless the user intends to break EasyEffects they should not try to make its gsettings database readonly. In any case as I explained above the settings are only modified if autoloading profiles based on devices are set and if the user changes these devices.
