### ISSUE TITLE
[Question] Could you help me understand Auto Gain?

### ISSUE THREAD

**Issue by p-chan5** [wwmm/easyeffects#2134]
Hi, I'm trying to add the Auto Gain effect to [my presets](https://github.com/p-chan5/EasyPulse); this to compensate for the volume loss caused by the Equalizer (subtractive type). The problem is that I want to get the same result with EasyEffects and PulseEffects. I have read both manuals and they both use the same library, [libebur128](https://github.com/jiixyj/libebur128), but in the GUI everything changes:

<img src=https://user-images.githubusercontent.com/123143444/221319348-5f7c127e-4b80-4034-8202-dc0eec395641.png height=200> <img src=https://user-images.githubusercontent.com/123143444/221319365-e59407a5-5bab-4328-9baa-4a26232f3882.png height=200>

For easy reading I exported both manuals to PDF:

[pe_auto_gain.pdf](https://github.com/wwmm/easyeffects/files/10829685/pe_auto_gain.pdf)
[ee_auto_gain.pdf](https://github.com/wwmm/easyeffects/files/10829690/ee_auto_gain.pdf)

With some observation I can assume the following (but I may be wrong):

- ~~`Detect Silence` is enabled by default in **EE**~~

- ~~`Silence` is the `Relative` in **EE** and it is not configurable in **PE**~~

And ask me the following:

- What is the value of `Maximum History` in **PE**? Is it automatic value?

- What are the values ​​of `Momentary`, `Weights` and `Integrated` in **EE**?

Something that has saved the life of my ears when using this effect is the Maximizer and setting the `Integrated` to `100` in **PE** to avoid clicks in some songs like [this](https://www.youtube.com/watch?v=VlmTfyocUzk) (where every time the kick is played these clicks are triggered). Based on this, do you have any other recommendations when using Auto Gain?

**Comment by wwmm** [comment]
>What is the value of Maximum History in PE? Is it automatic value?

I imagine you meant `EE` instead of `PE`. PulseEffects does not have the maximum history control. The maximum history is controlling a moving window average https://github.com/jiixyj/libebur128/pull/49. In PulseEffects and in older EE versions we did not use this mode. The library was configured in a `histogram` mode that has higher performance but works in a different way and does not allow a time window to be set. The integrated value considered the history since the moment the library was initialized. What made it barely change through time.

>What are the values ​​of Momentary, Weights and Integrated in EE?

We do not do this kind of average anymore. Only the geometric mean.

>Something that has saved the life of my ears when using this effect is the Maximizer and setting the Integrated to 100 in PE to avoid clicks in some songs like [this](https://www.youtube.com/watch?v=VlmTfyocUzk) (where every time the kick is played these clicks are triggered). Based on this, do you have any other recommendations when using Auto Gain?

At least for my needs the geometric mean of the main loudness estimation `Geometric Mean (MSI)` is enough. If you want the a slower reaction you may either play with the maximum history value or use the other geometric means that do not use the momentary loudness. As the autogain evolved through the years replicating the behavior in PulseEffects may not be possible. And in my opinion the autogain is way better now. The way to configure is just a little different.

**Comment by p-chan5** [comment]
Thanks for your reply. I have read the discussions pointing to this pull request and now I understand. It is good to know that you have improved the implementation of this library.

Volume has become a problem for me since I equalized my headphones. It was hard to choose between Auto Gain, Limiter or Gate. Basically I fear for the health of my ears, anecdotally... The other day I used the Gate from PulseEffects (Calf Studio) and the volume shot up to `+70dB` luckily I had the Maximizer on or it would be dead ever since. Using the Limiter `Threshold` didn't work either. I messed up the dynamics and had Automated Level Regulation (ALR) problems. That's why I put all my hopes in the Auto Gain. It is like an intelligent leveling that analyzes the material and shapes it based on a history.

Thank you for taking the time to clarify my doubts. I'll cross out my misstatements and do my best to get the most out of both versions.

Greetings from China! 🇨🇳

**Comment by wwmm** [comment]
>It is good to know that you have improved the implementation of this library

I do not know about the libebur128 or the ebur128 standard enough to contribute with code there :-). I am just using it to build an autogain.

>The other day I used the Gate from PulseEffects (Calf Studio) and the volume shot up to +70dB luckily I had the Maximizer on or it would be dead ever since. Using the Limiter Threshold didn't work either. 

I do not remember it having this weird behavior. But I do not have much reason to use a gate in my workflow. In any case I almost always have at the end of my pipeline `autogain -> limiter`. The reason is that the current autogain code does not have efficient protection for signals above `0 dB`. So I like to have the limiter there as a safeguard even if it is doing nothing almost 100% of the time. I keep my autogain target at `-23` and adjust the system volume level accordingly depending on what I am doing. So if everything goes well the signal getting to the limiter won't get anywhere near to saturation if nothing weird happens.

>It is like an intelligent leveling that analyzes the material and shapes it based on a history.

The library libebur128 estimates loudness in a while that tries to take into account the human ear frequency response. It is not perfect but it is decent enough for what I am trying to achieve in the autogain.

**Comment by p-chan5** [comment]
> The other day I used the Gate from PulseEffects (Calf Studio) and the volume shot up to `+70dB`

No wait, I remember, it was Loudness. I set the same to `0.00` (thinking it was the threshold) and the Link to `-6.03` suddenly the volume shot up. I use this version of PE on my old laptop. At that time `MDA.LV2` was imported (this according to the manual for that version)

[pe_4_7_1_loudness.pdf](https://github.com/wwmm/easyeffects/files/10830499/pe_4_7_1_loudness.pdf)

I didn't understand what was written there so I tried my luck and since then I love the Maximizer and the Limiter; they are like the audio firewall.

<img src=https://user-images.githubusercontent.com/123143444/221344565-fa12af1c-c9d4-47db-9d1a-4174545cf349.gif height=300>

Fortunately, [LSP Loudness Compensator Stereo](https://lsp-plug.in/?page=manuals&section=loud_comp_stereo) was implemented in the current versions and it is rare to see things like this again.

**Comment by wwmm** [comment]
Although the MDA plugin calls itself "loudness" if I remember well it only tries to correct bass and not the whole spectrum like the loundness plugin from LSP does. It can indeed amplify it enough to saturate the soundcard. But I do not think a `0.01 dB` step should be having such a catastrophic result. Weird...

**Comment by wwmm** [comment]
Version `7.0.1` released. It has the features marked as completed in this issue first post.
