### ISSUE TITLE
Mono microphones are only connected to the left channel

### ISSUE THREAD

**Issue by Massimo-B** [wwmm/easyeffects#2138]
### EasyEffects Version

6.2.8

### What package are you using?

Other (specify below)

### Distribution

Gentoo

### Describe the bug

Hi, I have 2 mono microphones. Both are only connecting to the left channel of ee_sie_spectrum up to the EasyEffects Source. Using the loopback button I only hear the mic on left channel.

I tried with 2 different microphones, one is definitly a Mono mic inside a USB webcam.
The other is a "Samson Technologies Corp. C01U condenser microphone" which reports being a stereo mic but is just a cascaded mono-amp. Since pulseaudio I used to fix that now on pipwire with:
```
cat /etc/pipewire/pipewire-pulse.conf.d/custom.conf 
context.exec = [
    { path = "pactl"        args = "load-module module-remap-source source_name=Samson_C01U-mono master=alsa_input.usb-Samson_Technologies_Samson_C01U-00.analog-stereo master_channel_map=front-left channel_map=mono" }
]
```
Anyway I guess the issue is not based on the remapping since my USB webcam mic has the same issue. On qpwgraph I'm going to additionally set a wiring from the mono mic to FR and get the mono signal right on both headphone channels as expected.

But using EasyEffects with default source and switching the default source between the 2 mics, I always loose my bugfix and need to add it again. Is that a bug in EasyEffects?

The bugfix is also lost when adding new filters.

**Comment by wwmm** [comment]
There are some limitations when it comes to mono mics but there is a simple workaround #1312 that is using the `stereo tools` plugins.

As we already have an open issue about mono mics we can close this one.

**Comment by pinkflames** [comment]
I think the core complaint here is that MONO should get linked to both FL and FR. Feel free to correct me if I'm wrong.

**Comment by Massimo-B** [comment]
I just wonder I don't have that issue on my laptop using the internal OR some bluetooth headset microphone (both should be mono, but I'm going to check that later..).

**Comment by wwmm** [comment]
>I think the core complaint here is that MONO should get linked to both FL and FR. Feel free to correct me if I'm wrong.

Yes. In a way that is similar to what is being asked at #1312 and I intend to do it one day. But as the stereo tools plugin is a decent workaround for this problem I have prioritized other issues where no workaround is available.

>I just wonder I don't have that issue on my laptop using the internal OR some bluetooth headset microphone (both should be mono, but I'm going to check that later..).

When PipeWire configures the mic as a stereo device its 2 channels will be linked just fine. My microphones behave that way. The only problem is when the mic has only one channel. EasyEffects PipeWire is  stereo. So something has to be done in this case. But while it isn't you can just add the stereo tools plugin to the effects pipeline and configure it in a way that the stereo matrix generates a mono signal. This way both channels will have the mic signal.

**Comment by pinkflames** [comment]
Supporting MONO input does not require changing the entire filter chain. Correct me, if I'm wrong, but currently EasyEffects creates a single MONO to FL link which is what causes this particular issue. The solution appears to me to be as simple as also creating a second MONO to FR link. This, I believe, should also match the expected behavior that PipeWire clients exhibit by default when dealing with MONO to stereo use cases.

**Comment by wwmm** [comment]
>Supporting MONO input does not require changing the entire filter chain. 

That is right.

>Correct me, if I'm wrong, but currently EasyEffects creates a single MONO to FL link which is what causes this particular issue. The solution appears to me to be as simple as also creating a second MONO to FR link. 

Creating a second link should work. What has to be done is improving the function responsible for the filters links https://github.com/wwmm/easyeffects/blob/224b641aac1c013219ded7c675e558275a678450/src/pipe_manager.cpp#L1669. At this moment this function maps `out FL` to `in FL` and `out FR` to `in FR`. Or it does that with index if the channel has not tags. What usually happens when the card is in `Pro mode`.

Maybe some small changes ot https://github.com/wwmm/easyeffects/blob/224b641aac1c013219ded7c675e558275a678450/src/stream_input_effects.cpp#L176 may be necessary. But I do not expect anything hard. IT is just a matter of not breaking the other kinds of links that the function also has to do.
