### ISSUE TITLE
Manual does not show up in KDE's KHelpcenter

### ISSUE THREAD

**Issue by HurricanePootis** [wwmm/easyeffects#2141]
### EasyEffects Version

7.0.1

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Whenever I go to open the EasyEffect's manual, it automatically launches KDE's KHelpcenter (on KDE). However, it goes to KHelpcenter's `Documentation not Found` page.

Looking through the search bar in khelpcenter itself, nothing shows up for khelpcenter.

### Expected Behavior

For the manual to show up loaded in khelpcenter

### Additional Information

I was able to load up the manual with GNOME's yelp.

**Comment by wwmm** [comment]
Same as the issue #2046. So we can close this one.

I have to be honest. I have no idea about how to fix this. It was easy to do the documentation using `http://projectmallard.org` but it seems only yelp plays nice with it. Maybe because our Meson scripts are using gnome extensions to generate yelp files https://github.com/wwmm/easyeffects/blob/224b641aac1c013219ded7c675e558275a678450/help/meson.build#L47

 But then the question is if it is possible to do something similar for KDE. Last time I checked it was not clear at all.
