### ISSUE TITLE
(UI/UX) Spectrum analyzer - always full scale

### ISSUE THREAD

**Issue by violetmage** [wwmm/easyeffects#2151]
In the spectrum analyzer window, regardless of the volume of the incoming audio, the vertical scale seems to dynamically shrink to fit the highest peak on the graph.

This behavior negates the usefullness of the analyzer in measuring absolute volume, for example when bringing signals to line level. This is ok if one is only interested in the relative volume of the harmonics in the current sound, but is unhelpful when trying to compare and analyze different sounds.

Not sure if this is the intended behavior, so maybe this is ok.

I remember back in pulseeffects having some sort of indepedent exponent / gain control over the spectrum analyzer, not sure if we can reimplement that somehow. A cursory glance leads me to believe we could add some user configurable stuff around here [base_plugin.cpp +378](https://github.com/wwmm/easyeffects/blob/e3ba877d7b9243b42c45dddc091e039d15e3d16a/src/plugin_base.cpp#L378) somewhere.

Another thought, since the spectrum analyzer is already quite sophisticated (and by far the most aesthetic of the linux offerings imo), maybe it would be worth making it a standalone plugin / app, so that people could play around with it in DAW's, or without needing to load up all of easy effects.

**Comment by wwmm** [comment]
>In the spectrum analyzer window, regardless of the volume of the incoming audio, the vertical scale seems to dynamically shrink to fit the highest peak on the graph.

I think it is the same as #1512. I will try to remember to take a look at this when I have time to work on the next minor release. It definitely should not be the default behavior. So a configuration option will be needed.

>I remember back in pulseeffects having some sort of indepedent exponent / gain control over the spectrum analyzer, not sure if we can reimplement that somehow

I did not bring it back because it had some problems. The intensity showed by the mouse hover was totally wrong once that scaling was in place. The usefulness of that scaling did not seem worth the trouble of fixing the problems it introduced.

>maybe it would be worth making it a standalone plugin / app

It is possible but there is a fair amount of work involved if we want the same code to be used in EasyEffects. If I remember well there is a way to make standalone PipeWire filters. The problem is we do not use this approach in EasyEffects. Our window code is directly accessing information from the plugin. So a lot of work to decouple plugins from the rest of EE is needed.

**Comment by violetmage** [comment]
Whoops. Forgot to close this.

Closed as duplicate of #1512
