### ISSUE TITLE
EasyEffects pw_filter_add_listener invocation needs to use pm->lock()

### ISSUE THREAD

**Issue by pinkflames** [wwmm/easyeffects#2246]
### EasyEffects Version

7.0.1 with a patch from master to fix a crash

### What package are you using?

Gentoo

### Distribution

Gentoo

### Describe the bug

In debugging a PipeWire issue involving EasyEffects it was determined by Wim that: threaded mainloop handling in easyeffects can be improved.. it uses sleep and needs to release the lock but it should instead be using the thread wait and signal functions.

Since doing that might be involved, the easiest fix, as suggested by Wim is: do pm->lock() before pw_filter_add_listener, then do pm->unlock() instead of reworking the mainloop.

I hope this is useful. If you have questions, feel free to ask them either at the PipeWire matrix room when Wim is around or in a comment here and I'll pass it on.

**Comment by wwmm** [comment]
I am a little confused. After `pw_filter_connect` we call `pm->sync_wait_unlock();` and the lock is released. When the while loop runs PipeWire's thread isn't locked anymore. Why putting EasyEffects main thread to sleep is a problem?

**Comment by wtay** [comment]
When using a thread loop, *all* pipewire calls (except for the ones you can use in the realtime thread like pw_filter_get_time(), pw_filter_(de)queue_buffer(), pw_filter_flush(), pw_filter_get_dsp_buffer() and pw_filter_trigger_process()) need to be called with the thread loop lock.

So also pw_filter_get_state() and pw_filter_get_node_id() (ideally... in this case it might work okish)

In this code fragment,  pm->sync_wait_unlock(); does not do much. The sync with the server ensure the connect completes but that doesn't really mean much for a client, there is no state updated in the client as part of this.

What I would do is the pm->sync_wait_unlock() and keep the thread locked.

The pw_filter_get_state(filter, nullptr)  can also return an error, you want to get that and exit the while loop.

Instead of std::this_thread::sleep_for(std::chrono::milliseconds(1)); use pw_thread_loop_timed_wait_full() (in a new pm->wait() method or so). This releases the thread lock and lets things continue. It will wake up again after the timeout or when some thread does pw_thread_loop_signal(). You could remove the timeout and add a state_changed event handler where you do the pw_thread_loop_signal() to wake up the waiting thread.

After the filter is in PAUSED, the node_id is always known. (again, this might not have been the case without the locking as it is now). So, you don't need the loop and sleep.

then to wait for the ports, I would use the _timed_wait() again. You could also possibly signal when a new port was added instead of polling with a timeout.

After all that, you can install the listeners (with the lock) and then pm->unlock().

**Comment by wtay** [comment]
> There are probably other places where PipeWire functions like these ones are being called without locking the loop.

Yes, master branch in pipewire tells us that pw_filter_destroy() is also called without locks.

**Comment by wwmm** [comment]
>Yes, master branch in pipewire tells us that pw_filter_destroy() is also called without locks.

PipeWire's master branch? Is it building and running EasyEffects now? Are these logs public? It would be nice to have a way to know where we are forgetting to lock the loop.

**Comment by wwmm** [comment]
Oh. Understood.

**Comment by wwmm** [comment]
>I have applied the latest EE commit as another patch but I'm still seeing:

Was this after using a test signal? I see now that the only other call to `pw_filter_add_listener` is there and there isn't a lock before it yet.

**Comment by wwmm** [comment]
Probably it isn't even necessary to try to play a test signal. The test signal class will probably make that call once the window is initialized.

**Comment by pinkflames** [comment]
I just realized that those timestamps may belong to the old build before EasyEffects was rebuilt. Sorry for the noise. I'll let you know if they show up again.. Sorry once more.

**Comment by wwmm** [comment]
@pinkflames I have updated the master branch again. The calls to `pw_filter_add_listener` and `pw_filter_destroy` are now done when the loop is locked.

**Comment by pinkflames** [comment]
Thanks for the quick fixes. I have built EasyEffects 7.0.1 with 4 patches from git master branch now and so far no more warnings about threading issues. I'll report (probably via a new issue), if any additional warnings are noticed.
