### ISSUE TITLE
Level meters are hard to use

### ISSUE THREAD

**Issue by NicolasLM** [wwmm/easyeffects#2332]
In practice I found setting levels using easyeffects quite difficult for a few reasons:

1.  Most meters in easyeffects do not have a scale.
2.  Most meters in easyeffects only show the current level and they are updated many times per second. Typically meters in other software have a floating peak indicator that is very helpful.
3. Parts of the UI show an integer for level, like `-12 dB`, but the value is updated many times per second, making them almost unreadable. See for example the level in the left part of the footer or the compressor gain.

**Comment by wwmm** [comment]
>Most meters in easyeffects do not have a scale.

That is because `GtkLevelBar` does not provide a scale while in `continuous` mode. Maybe they show one in `discrete` mode but even if they do this mode is not suitable for the kind of values we have to show. So the solution to this would be making our own custom level meter. What I really would like to avoid for reasons I will tell later.

>Most meters in easyeffects only show the current level and they are updated many times per second. Typically meters in other software have a floating peak indicator that is very helpful.

Recent EasyEffects versions have a setting called `Update Interval` in the preferences window. Choosing higher values will make the spectrum and level meters to be update slower.

The peak values is something someone else has already asked in the past. I think that the main difficulty is figuring out a clever way to find space in the window for them. In the plugins with few widgets it is not hard. The harder ones will be the multiband plugins that already have a lot of things to show. Let's see what the future holds. Maybe a good idea will come.

Something I would really like to avoid is creating custom widgets. They require a fair amount of time to be created and we will also have the headache to keep them working as gtk moves from one major release to another. And there is also the eternal drama about people wanting the widgets to follow their desktop theme. If possible I would like to avoid these kind of troubles.

**Comment by wwmm** [comment]
That is the issue where the peak volumes were requested before #1452.

**Comment by NicolasLM** [comment]
Thank you for the explanation.

My understanding regarding reducing the update interval to have more stable level meters is that it just reduces the number of samples it takes. So setting the update interval to one per second will make a readable level meter but it won't register a 50 ms loud peak.

**Comment by 1player** [comment]
> The peak values is something someone else has already asked in the past. I think that the main difficulty is figuring out a clever way to find space in the window for them.

Terrible hacky, but simple idea: why not have an effect plugin that all it does is show this kind of information? Given the pipeline nature of Easy Effects, one can slot it in where they need it, and then remove it.

**Comment by NicolasLM** [comment]
Having this data between plugins is also very useful, for example for setting up a compressor. The main knob for the compressor is the threshold in dB at which it will start affecting the signal. This is easier to do knowing the characteristics of the signal entering the compressor.

**Comment by wwmm** [comment]
>Terrible hacky, but simple idea: why not have a "Debug" effect plugin that all it does is show this kind of information? Given the pipeline nature of Easy Effects, one can slot it in where they need it, and then remove it.

>I think it's simpler to measure it on the hidden filter we already have at the bottom of the pipeline. Making another visible plugin is more tricky.

>Having this data between plugins is also very useful, for example for setting up a compressor. The main knob for the compressor is the threshold in dB at which it will start affecting the signal. This is easier to do knowing the characteristics of the signal entering the compressor.

Considering what has been said here and an old discussion at #1592 I think that having a dedicated plugin measuring the level is the better approach. The reason is that our level meter is very simple. For example it does not measure true peak, LUFS or dBFS. I will take a look at some LV2 level meters to see which one seems suitable for this task.

**Comment by wwmm** [comment]
Note to myself so I do not forget. The library `libebur128` we already use to estimate loudness has a true peak mode that returns `dbTp` https://github.com/jiixyj/libebur128/blob/67b33abe1558160ed76ada1322329b0e9e058b02/ebur128/ebur128.h#L403. It seems to be capable of estimating the true peak of the last sample as well as the true peak of the total history.

**Comment by wwmm** [comment]
The new level meter plugin is available for testing on our master branch
![Screenshot from 2023-05-11 15-43-47](https://github.com/wwmm/easyeffects/assets/16225172/2a9c40af-3a24-441e-a0ab-699d3856c3a8)

The `true peak` estimation done by `libebur128` are based on `all the frames` received by the plugin. In other words it is the true peak of the whole data that passed through it after its insertion in the pipeline. So depending on what is being done the `reset history` button will have to be used to reset the true peak estimation.

**Comment by NicolasLM** [comment]
It looks great!

**Comment by 1player** [comment]
Fantastic. Is it lightweight enough I can keep it enabled long-term? 

I have a custom EQ curve, and right now I have no idea if it ever clips or I have still some headroom for amplification, so I'd leave this new Level Meter plugin enabled for a few weeks, and re-adjust my volumes.

**Comment by NicolasLM** [comment]
I wonder if the values in the loudness section have a more precise unit or qualifier? I guess the first three are LUFS but it would be helpful to confirm and have the unit displayed after the value.

**Comment by wwmm** [comment]
>Is it lightweight enough I can keep it enabled long-term?

That depends on your CPU. As the level meter is based on the `libebur128` library it is as heavy as the `autogain` plugin. I use the autogain plugin all the time but I have a powerful CPU in my desktop. At this moment it is `Ryzen 7700` and before it a `Ryzen 3700x`. In processor like these ones it is almost like EasyEffects isn't even running. Even with lots of plugins enabled. But on older CPUs like the `i7` I have in my laptop anything based on libebur128 will be intense on resource usage. You will have to take a look at your CPU usage to judge how it is on your computer.

>I wonder if the values in the loudness section have a more precise unit or qualifier? I guess the first three are LUFS but it would be helpful to confirm and have the unit displayed after the value.

Oh... You are right. While copying and pasting that the `range` is in `LU` and the other loudness estimation are in `LUFS`. I will correct this once I have time.

**Comment by wwmm** [comment]
We can close this issue. It is better to put effort into adding more functionality to the level meter plugin than to try to improve the level meter bars since this involves gtk and piepwire limitations.
