### ISSUE TITLE
Report units also in the AutoGain UI

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2359]
In the Level Meter every measurement reports its unit, but that does not happen for the AutoGain.

Since they show the same meters, I think it's better to report the units also in the AutoGain.

Besides this could be the opportunity to switch the AutoGain UI to use the `AdwPreferencesRow` like the Level Meter. But this is not the highest priority, having the units reported it's enough.

**Comment by wwmm** [comment]
>Besides this could be the opportunity to switch the AutoGain UI to use the AdwPreferencesRow like the Level Meter. But this is not the highest priority, having the units reported it's enough.

I think that we should do both things. Switch to the `AdwPreferencesRow` approach and showing the units.

**Comment by wwmm** [comment]
I think that instead of having all the spin buttons and the dropdown in a top horizontal line we could put them in a left panel like the level meter `true peak` and in loudness meters in a `loudness`panel like the one in the level meter. And like in the level meter the `reset history` button could stay at the top.
