### ISSUE TITLE
Any hack/plan to fix the look of the GUI ?

### ISSUE THREAD

**Issue by medmedin2014** [wwmm/easyeffects#2448]
### EasyEffects Version

7.0.5

### What package are you using?

Arch (easyeffects)

### Distribution

Manjaro

### Describe the bug

EasyEffects looks really bad compared to how GTK3/4 apps appear on Plasma KDE, I don't understand why such important app was created using that cursed LibAdwaita library, it locks any attempt to customize it with that ugly embedded Adwaita theme. Are there any hack to fix the appearance of the app to look more beautiful ?

![image338](https://github.com/wwmm/easyeffects/assets/7027319/535b2e51-fa73-4e31-bfb4-a6932b4a2edb)

**Comment by wwmm** [comment]
>I don't understand why such important app was created using that cursed LibAdwaita library

CAlling it cursed is not going to help you to get what you want. I used KDE for many years before switching to GNOME. Bringing the "old and tiring theme war" between these desktops here is not going to be productive. For example I use okular in GNOME to deal with digital signed pdf and Okular looks really ugly. Not as ugly as KDE is making EasyEffects look but it still feels ugly and alien. So is the solution rewriting Okular in GTK? No it isn't. GNOMe/GTK should do a better job when QT/KDE apps are loaded.

There is no company or big organization behind EasyEffects. I started this project to solve my personal needs and eventually decided to share it. And although I also had experience with QT at the time GTK was the tool that allowed me to do what I wanted with the least amount of effort. 

Most of the cool LibAdwaita widgets are not available in pure GTK. So like it or not most GTK programs will start to use LibAdwaita at some point. The fact that it is a lot easier to do some things using LibAdwaita is reason enough for this. The real issue here is at whatever is integrating LibAdwaita on KDE. There is no justification for it to be stretching EasyEffects widgets as shown in your image.

**Comment by wwmm** [comment]
>Are there any hack to fix the appearance of the app to look more beautiful ?

I haven't followed KDE development in many years so I do not know how gtk4/libadwaita apps are supposed to integrated. Looking at your images it is clear KDE is not doing a good job on its own. Maybe a manually tweaked `~/.config/gtk-4.0/settings.ini` file will help it.

**Comment by medmedin2014** [comment]
LibAdwaita forces its own embedded Adwaita theme to be used, and GNOME devs refuse to provide any API to change it, this makes it impossible to use another theme on any non GNOME desktop. 

GTK4 without LibAdwaita works fine and follows Plasma themes.

**Comment by medmedin2014** [comment]
> So is the solution rewriting Okular in GTK
 
Qt4/5/6 and GTK2/3/4 (4 without LibAdwaita) can be easily customized to use any provided and compatible theme.

**Comment by wwmm** [comment]
>LibAdwaita forces its own embedded Adwaita theme to be used, and GNOME devs refuse to provide any API to change it, this makes it impossible to use another theme on any non GNOME desktop.

I see. This kind of mentality is something I have never liked in the GTK world.

>Qt4/5/6 and GTK2/3/4 (4 without LibAdwaita) can be easily customized to use any provided and compatible theme.

Sure. But implementing in pure GTK4 some of the functionality LibAdwaita offers for free is a pain and time consuming. I have tried to follow this road in the past and it was not a pleasant journey. Just using LibAdwaita is `a lot` easier from a development point of view.

**Comment by medmedin2014** [comment]
Thanks, It's just I'm daily using this great application and its looks always bothers me, and truthfully I love it because it never fails to impress me with its performance and quality sound.
