### ISSUE TITLE
Button to toggle input/output devices

### ISSUE THREAD

**Issue by Bleuzen** [wwmm/easyeffects#2492]
Hi, on some machines without a microphone it does not make sense to have the "Easy Effects Source" input device loaded all the time. On another machine I use EE for mic processing, but very rarely for output processing, so the "Easy Effects Sink" output device does not need to be loaded all the time.

It would be nice to have a toggle button for EEs input/output devices.
For example...
Here (idea 1):
![](https://github.com/wwmm/easyeffects/assets/12885163/4462094d-71d8-47f4-a0b5-37794c9a89d7)

Or here (idea 2):
![](https://github.com/wwmm/easyeffects/assets/12885163/de56555e-8842-47fb-a9e9-8f1326451484)

This button should completely unload/load either the "Easy Effects Sink" device (if "Output" tab is selected) or "Easy Effects Source" device (if "Input" tab is selected).

Why?:
- possibly free up some resources (not sure how much this matters)
- avoid UI clutter (looks cleaner, no need to see an unused device in every application, patchbay and volume controls)

**Comment by wwmm** [comment]
>possibly free up some resources (not sure how much this matters)

The amount of memory consumed by an inactive sink is negligible. The main source of memory consumption is EasyEffects is the graphical interface. And an idle virtual device has no impact on CPU.

>avoid UI clutter (looks cleaner, no need to see an unused device in every application, patchbay and volume controls)

Maybe. But I do not think we should put so much effort on our side just for some devices to not be visible on other applications. They are the ones that should provide a way to hide what is not needed. Just like we ignore some things that we do not need. And our code is not designed around the idea that these devices may not be there. There are many places here and there that will have to be reworked just for an unloaded device to not break many things.

While I can see this could be visually nice (no real difference from performance point of view though) it requires an amount of work that is quite larger than the benefits it brings.

**Comment by sgtcoder** [comment]
Well the microphone doesn't work when Easy Effects resets to be the default input/source sink.

As much as I like Easy Effects for the output, it's becomming more of a problem than a solution.

**Comment by wwmm** [comment]
>Well the microphone doesn't work when Easy Effects resets to be the default input/source sink.

EasyEffects does not forces its sink to be the system default. There is no code for that in our sources. WirePlumber or another third party tool is doing it.

**Comment by sgtcoder** [comment]
Can we remove the easy effects sink for the microphone?

**Comment by wwmm** [comment]
>Can we remove the easy effects sink for the microphone?

What do you mean? This affirmation does not make sense. Can you show an image?

**Comment by sgtcoder** [comment]
![image](https://github.com/wwmm/easyeffects/assets/2577827/0de27532-0b63-4cd0-82c8-af02810e34ec)

**Comment by wwmm** [comment]
> ![image](https://private-user-images.githubusercontent.com/2577827/308037828-0de27532-0b63-4cd0-82c8-af02810e34ec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDkwMDg3NTUsIm5iZiI6MTcwOTAwODQ1NSwicGF0aCI6Ii8yNTc3ODI3LzMwODAzNzgyOC0wZGUyNzUzMi0wYjYzLTRjZDAtODJjOC1hZjAyODEwZTM0ZWMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIyNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMjdUMDQzNDE1WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YWZlODY4Yzc4ZDkwYzBhZGY2ZjYwMGQ0YzdhMmMxZTMxNzRiYjA1NDNkMWE5MGIwZDM0YjljOTdjYWMwNmI0OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.YrbF-KWgA6Ixb59kzovO9kdZxEVVRGtGJEAEshpZ8pk)

Although that device is made through a null-sink module it is configured by pipewire as a source device. As Pavucontrol is still a Pulseaudio app it can not see this. In any case it is always loaded. So no, it can't be removed. It would just add more code complexity for no reason. It causes no problems as long as WirePlumber does not misbehaves or forces it to be the default. What is not a common occurrence.

WirePlumber has some internal logic that may force our source/sink as default if the user selected it manually as default in the past. If you do not want that source device to be used the first thing to do is disabling `Process All Input Streams` in EasyEffecs preferences window. The second step is resetting WirePlumber to make sure it does not have any association that could force our virtual source to be forced as default.

There are cases where the system has no microphone that wireplumber sets our source as default because it sees no other device. But even in this case if the user plugs a mic and our virtual source was never set manually by the user as default wireplumber should prefer the hardware over a virtual device. If it is not doing it it is a bug on its side.

**Comment by sgtcoder** [comment]
I don't have process all audio for input devices checked. It still loses the default setting. I might have to uninstall Easy Effects and simply not use it due to the unnecessary microphone sink being generated.

Thanks for your help
