### ISSUE TITLE
Using microphone as default device does not enable any effects.

### ISSUE THREAD

**Issue by subanz** [wwmm/easyeffects#2525]
### EasyEffects Version

7.0.7

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

From what I understand we are not suppose to select the Easy Effects Sink/Source as default.
Setting Line In for default audio works fine and all the effects apply without any issues.
However microphone effects only work if I set the Easy Effects Source as the default device.

### Expected Behavior

Using the microphone device instead of Easy Effects Source should still apply effects?

**Comment by wwmm** [comment]
>Using the microphone device instead of Easy Effects Source should still apply effects?

Yes. That is how I apply effects to my microphone when participating in online meetings. Kill EasyEffects `easyeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=easyeffects easyeffects` so we can see what is printed when you try to apply effects to your microphone. It may also help to run `pw-dot` its output file can be viewed with the command `xdot` and will show where your microphone and filters are linked to.

**Comment by wwmm** [comment]
>new metadata property: 0, default.audio.source, Spa:String:JSON, {"name":"easyeffects_source"}

Initially your hardware was set as default but eventually EE virtual devices was set as default by something. What is not guaranteed to work in some cases. But what is strange is that there is no audio recording app or filter present in your pw-dot output. Was there an app recording audio when the logs were taken?

**Comment by subanz** [comment]
Debug and pw-dot while recording audio in Counter Strike: Global Offensive(+voicerecord) and the default recording device set as microphone:
[easyeffects-debug-mic.txt](https://github.com/wwmm/easyeffects/files/12371544/easyeffects-debug-mic.txt)
[pw.dot-mic.txt](https://github.com/wwmm/easyeffects/files/12371526/pw.dot-mic.txt)

With default recording device set as Easy Effects Source:
[easyeffects-debug-source.txt](https://github.com/wwmm/easyeffects/files/12371554/easyeffects-debug-source.txt)
[pw.dot-source.txt](https://github.com/wwmm/easyeffects/files/12371559/pw.dot-source.txt)

Thank you for taking time to help with this.

**Comment by wwmm** [comment]
The problem is that csgo is not linked to our virtual device. It is linked directly to you microphone. I know that there are applications where its developers disable audio redirection. But I have never heard of a game doing this. The reason why it is working when our virtual device is the default is just the fact the audio application is only allowing default devices to be used.

Another possibility is that there is something in your system forcing recording streams to be moved to the default device. In the past gnome system settings did this. I do not know if on KDE this kind of horrible idea is in place too.

**Comment by subanz** [comment]
I tried arecord and audacity and they also exhibit the same behavior.
Assuming this is just how KDE does its thing can I get by just leaving the Easy Effects Source as default?
Should I open a bug report on the KDE issue tracker?
I suppose its still possible that its something else on my end.

**Comment by wwmm** [comment]
>I tried arecord and audacity and they also exhibit the same behavior.

These applications should work fine as they do not ask the audio server to disable audio redirection. So there is something in your system forcing the default input device to be used.

>Assuming this is just how KDE does its thing can I get by just leaving the Easy Effects Source as default?

If things are working  keep doing it. As I explained at #1836 the reason why I do not recommend our virtual devices to be set as default is that there is a chance PipeWire/WirePlumber will report our own devices to us as default instead of your hardware. And as it does not make sense EasyEffects records from its own source  instead of the mic its input device will be undefined. It is a random problem. It depends on the timing PipeWire is doing its operations. It seems that on your computer it always broadcast your hardware as default to us. So you should be fine as long as it keeps doing this.

>Should I open a bug report on the KDE issue tracker?

Only if they are the ones forcing the streams to be moved to the default device. In order to figure this out we would have to investigate PipeWire logs. But I am not sure if this information will be shown in a clear way there.

**Comment by subanz** [comment]
Thank you for all the help. I'll just stick with using the Easy Effects Source as default since its for the time being not causing any issues.
