### ISSUE TITLE
Expose new LSP 1.2.10 features in EasyEffects

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2533]
The new release has a ton of new features. See [here](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.10).

- [x] Add phase switches to Delay Compensator plugin series.
- [x] Add Allpass filter to the Filter plugin series.
- [x] Add Bandpass, Ladder-pass and Ladder-rej filters to Parametric Equalizer plugin series.
- [x] Introduce Linear Phase mode for multiband plugin series: Multiband Compressor, Multiband Expander, Multiband Gate, Multiband Limiter.
- [x] Add Band Width option (with `oct` unit).
- [x] Implement Stereo Split mode for stereo version of Compressor.
- [x] Implement Stereo Split mode for stereo version of Gate.
- [x] Implement Stereo Split mode for stereo version of Expander.
- [x] Implement Stereo Split mode for stereo version of Multiband Compressor.
- [x] Implement Stereo Split mode for stereo version of Multiband Gate.

**Comment by wwmm** [comment]
I guess it is time to start the work on the `filter` plugin and move from cal to lsp. I will do it this week.

**Comment by p-chan5** [comment]
Thanks @Digitalone1 and @wwmm I was also thinking of making a feature request :D

**Comment by p-chan5** [comment]
> Hope I'm no missing something.

You are forgetting the new Inspect button and Inspected filter identifier (oct) introduced in version [1.2.6](https://github.com/sadko4u/lsp-plugins/releases/tag/1.2.6).

![002](https://github.com/wwmm/easyeffects/assets/123143444/deb22fd7-f98a-437c-82bc-5a4524b75ed2)

I don't know if it's possible, but it would be very useful to see the scale detuned in cents in the equalizer band options; something similar to what happens with Width.

![003](https://github.com/wwmm/easyeffects/assets/123143444/2ebe94fb-72bd-410b-b283-02e3d3ecb091)

**Comment by wwmm** [comment]
>You are forgetting the new Inspect button and Inspected filter identifier (oct) introduced in version

Native window controls like this one should work out of box. Just the controls that make sense to add to EasyEffects custom window and presets that will need some work.

**Comment by LebedevRI** [comment]
Looks like Gain/Envelope/Curve meters in `Compressor` plugin
are no longer working with `LSP 1.2.10` + `EasyEffects 7.0.7`.

I guess ports were renamed?
Probably some other effects are also affected.

**Comment by wwmm** [comment]
>I guess ports were renamed?

Based on the warnings in the terminal they were.

**Comment by wwmm** [comment]
>Looks like Gain/Envelope/Curve meters in Compressor plugin

I am looking at the plugin ttl file and they were renamed because now left and right channel have their own ports. For example the curve level meter port moved from just `clm` to `clm_l` and `clm_r`. I think that for now I will do a quick fix and send the average of both channels to our custom window. Users wanting the detailed information have the option of opening the plugin native window.

**Comment by Digitalone1** [comment]
@wwmm Can we make this before the next release? Do you have time in the next weeks?

**Comment by wwmm** [comment]
>Can we make this before the next release? Do you have time in the next weeks?

I think I will have time.

**Comment by Digitalone1** [comment]
If I'm not missing something else, the Bandpass type is already implemented for the Filter plugin.

And, always if I'm not missing something else, the new Band-Pass, Ladder-Pass and Ladder-Rejection filter types should only be added for the Equalizer.

I did it a couple of minutes ago. 

But I noticed something weird. We remove the scale sensitivity for the High/Low Pass modes, but in the native UI I can still change the frequency on those modes. Another weird thing is that the quality knob grays out in the native UI on the Bell filter, but I can still change its value.

Following all those details it's hard for us, so I propose to remove the sensitivity only on the scale for the `Off` mode, just to signal that the band has been disabled. Maybe the scale has no meaning on certain types, but who cares? On other modes (especially on newer ones in the future) will be tricky to determine if the scale has a meaning. For a better maintenance it's easier to keep the scale always sensitive, except for the `Off` mode.

**Comment by Digitalone1** [comment]
For the Delay, the new parameters are only the following?

```
	Port 24:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      phase_r
		Name:        Phase Invert Right
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/lv2core#toggled

	Port 14:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      phase_l
		Name:        Phase Invert Left
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/lv2core#toggled

```

Just two bool parameters? Is it worth to add them?

**Comment by Digitalone1** [comment]
Trying the new Linear Phase mode of multiband plugins, it adds about +85 ms to the latency.

**Comment by wwmm** [comment]
>We remove the scale sensitivity for the High/Low Pass modes, but in the native UI I can still change the frequency on those modes.

This is normal. In our custom window the frequency can also be changed. Just the gain has to be disabled. The native ui does not disable the control but we can see it does nothing on the signal when we change it.

**Comment by wwmm** [comment]
>Another weird thing is that the quality knob grays out in the native UI on the Bell filter, but I can still change its value.

Does it? I did not notice it. In any case the quality control has to be enabled.

**Comment by wwmm** [comment]
>Following all those details is hard for us, so I propose to remove the sensitivity only on the scale for the Off mode

I do not think it is necessary. Our window is fine. It is just that the native window is not disabling the control.

**Comment by Digitalone1** [comment]
> This is normal. In our custom window the frequency can also be changed. Just the gain has to be disabled. The native ui does not disable the control but we can see it does nothing on the signal when we change it.

You're right, I confused the gain with the frequency, but the native UI still allows to change it. I think we should follow this behavior. It's easy to maintain. We don't know which other mode in the future will have a meaning for the gain.

> Does it? I did not notice it. In any case the quality control has to be enabled.

I don't think it's a good idea, this way it become too hard for us to stay behind LSP changes...

> It should not be tricky. Some modes traditionally do not expose the gain control to the user. If we let the gain control active in these cases then we will be misleading people by giving the impression that in our case the gain can be customized. It will be worse than keeping things as they are now.

Just explain to people that the gain does not affect that mode. Nobody complained about the quality...

**Comment by Digitalone1** [comment]
Meanwhile added the Invert Phase to the Delay plugin.

Not it remains the Stereo Split mode for other plugins which needs a switch for

```
	Port 11:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      ssplit
		Name:        Stereo split
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/lv2core#toggled

```

And an additional Dropdown for the following sources:

```
	Port 12:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Scale Points:
			0 = "Left/Right"
			1 = "Right/Left"
			2 = "Mid/Side"
			3 = "Side/Mid"
			4 = "Min"
			5 = "Max"

		Symbol:      sscs
		Name:        Split sidechain source
		Minimum:     0.000000
		Maximum:     5.000000
		Default:     0.000000
		Properties:  http://lv2plug.in/ns/lv2core#integer
		             http://lv2plug.in/ns/lv2core#enumeration
		             http://lv2plug.in/ns/ext/port-props#hasStrictBounds

```  

So I propose to rename the label for the current Dropdown in `SC Source` (Sidechain Source) and the new one will be `Split Source`.

**Comment by wwmm** [comment]
>but the native UI still allows to change it. I think we should follow this behavior.

I disagree. The native window is the one that should change and disable a control that will never do anything in a given context because the algorithm does not allow the control to be changed. It does not make sense. When I look at a control in a window I expect it to do something. Otherwise there will always be the doubt if the control is doing nothing because it is supposed to do nothing or because there is something in the signal being analyzed that does not make the change noticeable. Disabling the control makes this clear from the start.

>Nobody complained about the quality...

The quality control does not have a huge slider begging to be touched. And it is also confusing to not be sure about whether the mode allows the quality to be set or not.

>We don't know which other mode in the future will have a meaning for the gain.

But if we don't this means we have no idea about what the mode is doing. What isn't great. I still think it is fine to keep things as they are.

**Comment by wwmm** [comment]
>So I propose to rename the label for the current Dropdown in SC Source (Sidechain Source) and the new one will be Split Source.

It seems fine. Though if space in the window is available `Split Mode Source` maybe be more clear about what the control is doing.

**Comment by Digitalone1** [comment]
I get your point. If we were talking about Calf plugins, I would agree. But LSP is very active in it's development and it's not so easy for us to stay behind. Not touching the controls sensitivity too much will bring a robustness to the app for the future. Think if LSP dev will change the code and in the future the quality will have a meaning. If we follow your suggestion, people can't change the quality with the updated LSP versions and we are forced to make a new release. If the sensitivity is not touched, we won't do nothing.

**Comment by p-chan5** [comment]
For the `Stereo Split` feature maybe you can imitate the behavior of the limiter, i.e. name each port according to the Compressor / Multiband Compressor / Gate / Multiband Gate / Expander meters.

![limiter](https://github.com/wwmm/easyeffects/assets/123143444/4fd8f178-6145-4d97-8d54-e33b9c4dbd19)

**Comment by Digitalone1** [comment]
> But if we don't this means we have no idea about what the mode is doing. What isn't great. I still think it is fine to keep things as they are.

Let's be honest. The majority of people using EE don't know the meaning of the controls. Even I don't. If you want to understand something, you have to read the LSP documentation. Trying to catch what LSP does will only get more difficult our work.

**Comment by wwmm** [comment]
>But LSP is very active in its development and it's not so easy for us to stay behind

Based on what I have seen in the last years we stay behind in things that are unavoidable. For example when they add a new mode. We have to write code for this case anyway. But things like a control that did nothing suddenly doing it in an already existing mode are far from common. I do not even remember this. When did this happen in a case that did not involve a new mode we would have to write code for anyway?

>If you want to understand something, you have to read the LSP documentation

I see this the other way around. For example I do not remember having ever seen a high-pass or low-pass with gain control. IF suddenly I see one I will look for the documentation in order to understand why the hell in a particular plugin this control is there. We are talking about filters that are not originated from LSP code. When we read some of these names there is already some expectation about how the filter behaves.

**Comment by wwmm** [comment]
>I mean even if some parameters don't make sense in certain modes, you can still set values

For what reason would someone want to set values that will do nothing???

**Comment by Digitalone1** [comment]
I still don't agree, but okay.

> For what reason would someone want to set values that will do nothing???

The same reason LSP is allowing them to be set in the native UI.

**Comment by p-chan5** [comment]
> For what reason would someone want to set values that will do nothing???

I learned about the LSP project thanks to EE. At that time I was a novice user like many. I basically had no idea what I was doing.

**Comment by Digitalone1** [comment]
> What reason?? I mean other than writing less code. I am talking about reasons from an usability point of view. It makes no sense to set values that do nothing. What is the advantage for the user? What does this person gain from setting values that are ignored?

From the point of view of the user, you're right. But we can make choices also considering that we are developers. Writing less code and making the app more robust is a big target.

We have the target to make the app user-friendly and partially we reached it. But we also gave up in reaching a step forward in this direction, otherwise at the moment EE would stayed in the Gnome Circle. But we made a compromise, not following Gnome directions and making things easier for us. 

> And if you spend time configuring a control that by definition does nothing you will have even less idea about what you are doing. It is more productive in this case to make clear for the novice user that the control has no meaning in the filter he/she is learning to use.

In theory you're right, but in the reality we can't stay behind the documentation that is lacking the explanation of the new features at the moment.

Anyway, I have to go to bedroom. I tested the native UI of the Equalizer another time and noticed the following things:
- Quality controls do not gray out (my mistake).
- What grays out is the width which could be set in certain modes. Indeed the width is a knob in the native UI, not a label like our UI.
- This should to be investigated, but I don't have time at the moment. Maybe a new issue should be opened to remember to implement this new parameter.

**Comment by wwmm** [comment]
>Writing less code and making the app more robust is a big target.

Maybe it is because I do not see LSP doing the changes you think that they may do in the future but I do not see this adding so much robustness. For example in the case of the high and low pass it seems really unlikely that the gain will ever do something in the future. Not only because no other eq seems to allow this but because LSP already has the slope control affecting this indirectly for the changes in frequency response. I can see things getting more confusing for the users but not this code maintenance advantage materializing in the future... Most likely they will add a completely new control that will require code changes on our side anyway...

My suggestion is letting an open issue about this and waiting for people feedback. I think it is a bad idea but if users are fine with it whatever....

**Comment by Digitalone1** [comment]
Added new tasks.

The band width is the new option missing in EE.

```
	Port 713:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      wl_31
		Name:        Filter Width Left 31
		Minimum:     0.000000
		Maximum:     12.000000
		Default:     4.000000
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds
```

I confused it with the quality yesterday. This new parameter is grayed out for all modes except the Band-pass, Ladder-pass and Ladder-rej.

I suppose we have to remove the width label and use this new option in the band settings. @wwmm what do you think?

There is also this additional parameter, but I don't find it inside the native UI. What is it?

```
	Port 727:
		Type:        http://lv2plug.in/ns/lv2core#ControlPort
		             http://lv2plug.in/ns/lv2core#InputPort
		Symbol:      huer_31
		Name:        Hue Right 31
		Minimum:     0.000000
		Maximum:     1.000000
		Default:     0.968750
		Properties:  http://lv2plug.in/ns/ext/port-props#hasStrictBounds
```

Besides we should add the `oct` unit to the quality and the new width, as it's reported in the native UI.

**Comment by wwmm** [comment]
>I suppose we have to remove the width label and use this new option in the band settings. @wwmm what do you think?

This is the reasonable assumption considering that the new parameter is named width. But in LSP window the label is followed by `oct`. What in my mind means that it is a width measured in octaves and not in Hertz. In this case we cannot remove our label because it is not the same kind of information.

But there is something else I do not understand in this new parameter. Usually I think about the filter width as in the relation `width = central freq / quality`. But changes to the quality and the width lead to very different frequency response curves in the plugin window. So at this moment I have no idea about what is the width this parameter is controlling. It seems to be something very different than what I had imagined.

**Comment by Digitalone1** [comment]
@wwmm I'm not an expert in this kind of topic. Please, test the native UI selecting one of the last 3 modes and change the width. You will see the curve in the plot will change its shape.

**Comment by wwmm** [comment]
>Instead of controlling the quality we would control the width

The quality is just a indirect way to change the response width. This is a popular way to change the width so I was expecting the width control to be a direct way to affect it. But it does not seem to be the case. This control seems to do something else.

**Comment by wwmm** [comment]
>There is also this additional parameter, but I don't find it inside the native UI. What is it?

Based on lsp docs

>Hue - the color of the frequency chart of the filter on the graph.

It is something that is only used by the native ui. We can ignore it.

**Comment by Digitalone1** [comment]
The only way is to read the LSP documentation to understand its meaning...

I will take a look tomorrow.

**Comment by wwmm** [comment]
>The only way is to read the LSP documentation to understand its meaning...

I am looking at it now and it does not seem to explain it...

**Comment by wwmm** [comment]
The filter plugin docs talking a little about it https://lsp-plug.in/?page=manuals&section=filter_stereo. I think that there is a reason why the native window does not use this width control in the other modes like `Bell`. This seems to be some kind of effective width of the band and ladder pass response. It is a width but not the same kind of width we talk about in the other filters.

**Comment by wwmm** [comment]
After reading a little about this my conclusion is that the difference comes from how the width is defined. This is probably why the native window uses this control only for the bandpass variants and not for all filters.

>I suppose we have to remove the width label and use this new option in the band settings. @wwmm what do you think?

In any case I think we can do back to this question. We should remove our width label but disable the control in anything that is not the bandpass variants for the following reasons

- As we calculate the width now it is probably only useful for the bell filter and not accurate for any other mode. Specially the ones like high-pass and low-pass. 
- The new width control gives accurate information only for the new filter modes and is useless for the others. If we do not disable it we will not only give the wrong impression that the value is used but we will also suggest wrong information because that is not the width the filter actually has.

**Comment by p-chan5** [comment]
> There is also this additional parameter, but I don't find it inside the native UI. What is it?

`Hue` is the color of the knobs in the native UI, so it doesn't affect the sound at all. In versions prior to 1.2.0 it was still in the UI, but with some recent changes, it had to be removed (I don't know the reason).

https://github.com/wwmm/easyeffects/assets/123143444/6db34210-1540-4ab5-a53c-e0cd73470ad8

**Comment by Digitalone1** [comment]
It misses only the Stereo Split for Multiband plugins.

@p-chan5 maybe because the UI has different colors for knobs by default.

**Comment by Digitalone1** [comment]
> For the `Stereo Split` feature maybe you can imitate the behavior of the limiter, i.e. name each port according to the Compressor / Multiband Compressor / Gate / Multiband Gate / Expander meters.
> 
> ![limiter](https://user-images.githubusercontent.com/123143444/275991156-4fd8f178-6145-4d97-8d54-e33b9c4dbd19.png)

@p-chan5 this ticket will be closed. For this request, please, open another issue.

**Comment by p-chan5** [comment]
Sure! Thank you very much for addressing this issue. I hope they can be tested soon in a new stable release :D

**Comment by Digitalone1** [comment]
@wwmm Should we make a new release? I'm testing since almost a week and got no issues.

**Comment by wwmm** [comment]
>Should we make a new release? I'm testing since almost a week and got no issues.

It is also fine here on my computer. I will make a new release now.

**Comment by p-chan5** [comment]
I also released [a new version of EasyPulse](https://github.com/p-chan5/EasyPulse/releases/tag/1.1.0) making use of these new features. I hope it can also be useful.

Thank you very much guys, I have no words to express the happiness I feel right now :')

**Comment by sadko4u** [comment]
> There is also this additional parameter, but I don't find it inside the native UI. What is it?

Hue parameters are deprecated, they are just left for backward compatibility. They just controlled the color of filter (as one of many rainbow filter colors) in the UI. Do not use them.

If you have any questions about parameters or filters, you can ask me directly. This also will help to improve documentation for other people which also may be confused.
