### ISSUE TITLE
Unable to add effects

### ISSUE THREAD

**Issue by LuciusofLegend** [wwmm/easyeffects#2615]
### EasyEffects Version

7.1.0

### What package are you using?

NixOS

### Distribution

NixOS

### Describe the bug

When I click on the plus icon next to an effect, in order to add it, it does nothing.  It's as simple as that.

### Expected Behavior

I expected to be able to add effects.

### Debug Log

<details><summary>Debug Log</summary><br/>

```

(process:10235): easyeffects-DEBUG: 08:49:08.276:       easyeffects.cpp:35      easyeffects version: 7.1.0
(process:10235): easyeffects-DEBUG: 08:49:08.277:       easyeffects.cpp:45      locale directory: /nix/store/5jy39vdsw5h2xrrbb5hddvf4wzjf2chb-easyeffects-7.1.0/share/locale
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.279:   presets_manager.cpp:162 user presets directory already exists: /home/lucius/.config/easyeffects/
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.279:   presets_manager.cpp:162 user presets directory already exists: /home/lucius/.config/easyeffects/input
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.279:   presets_manager.cpp:162 user presets directory already exists: /home/lucius/.config/easyeffects/output
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.279:   presets_manager.cpp:162 user presets directory already exists: /home/lucius/.config/easyeffects/autoload/input
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.279:   presets_manager.cpp:162 user presets directory already exists: /home/lucius/.config/easyeffects/autoload/output
(easyeffects:10235): easyeffects-DEBUG: 08:49:08.386:   easyeffects.cpp:60      Exitting the main function with status: 1
```
</details>

**Comment by wwmm** [comment]
Your log is too short. Another EasyEffects instance was probably already running in the background. Kill it first `easyeffects -q`.

**Comment by wwmm** [comment]
>When I click on the plus icon next to an effect, in order to add it, it does nothing.

You may be facing some kind of gtk4 bug. IF possible try to record a small video showing the process.

**Comment by arilotter** [comment]
I hit this exact issue, debugged, and solved it - It's because you don't have dconf enabled.
With full logs, you'll see something like `the name ca.desrt.dconf was not provided by any .service files`
This is because home-manager doesn't enable dconf by default, and if you're using a non-gnome desktop environment, it won't be auto-enabled - see https://discourse.nixos.org/t/error-gdbus-error-org-freedesktop-dbus-error-serviceunknown-the-name-ca-desrt-dconf-was-not-provided-by-any-service-files/29111

The fix is to add `programs.dconf.enable = true;` in your system-level `configuration.nix`.

**Comment by LuciusofLegend** [comment]
arilotter your solution worked.  Thank you!
