### ISSUE TITLE
[Feature Request] Easy Effects Sink to Multiple Device Outputs, with each output device having its own Effect Stack.

### ISSUE THREAD

**Issue by mastr-ch13f** [wwmm/easyeffects#2753]
Hello @wwmm ,

Seeing how PipeWire can work like a patchbay (via Helvum anyways), it would be nice if there's a feature within the app to be able to add additional Output Devices with its own separate effect stack.

Although I can do this through Helvum, my configuration would be reset everytime Easy Effects times out due to inactivity.
![Screenshot from 2023-11-14 02-26-32_mark](https://github.com/wwmm/easyeffects/assets/78100517/e474cb8a-ea90-4d65-b4e8-5f2bd955d224)

The Implementaion could be something like:
```
                        _________________________________________
Players             ___|                 ___________________     |
 - Output Device 1 <___   Device Output |___Audio Device A__|    |
   | + Convolver       |                                         |
 - Output Device 2     |                                         |
   | + Convolver       |                                         |
   | + Filter          |                                         |
   | + Filter          |_________________________________________|
```

My use case for this is that I have an Impulse response files made (via mic calibration or recreated from AutoEQ) for my speaker and my collection of headphones, The ability to just switch the input on my DAC without having to switch device outputs in settings and switching Presets in the App would be great!

Thanks!

**Comment by violetmage** [comment]
While I agree that such abilities would be wonderful for more professional applications, I think that parallel pipelines is just begging for edge cases and feature creep.

For example, the very first problem to overcome is deciding what pipeline an application should be attached to. There would need to be a mechanism for picking a "default" pipeline, and each pipeline might also have it's own application whitelist/blacklist. Additionally, pipelines might share the same output device(s), which complicates handling connection and disconnection of hardware devices, especially because easyeffects would need to keep track of what applications are associated with each pipeline, and what pipeline they should be moved to.

This is only the first problem I can come up with without much thought. Again, it would be truly a great capability, but it would probably take the easy out of easyeffects.

**Comment by mastr-ch13f** [comment]
> Additionally, pipelines might share the same output device(s), which complicates handling connection and disconnection of hardware devices, especially because easyeffects would need to keep track of what applications are associated with each pipeline, and what pipeline they should be moved to.

Doesn't Easy Effects force every program it can find that outputs sound to be routed in to the **Easy Effects Sink** when the app/service is running? That was my basis for this feature request.

**Comment by wwmm** [comment]
This is almost the same as #1145 and unfortunately will have the same technical difficulties:

-  Our window is designed for one output pipeline and one input pipeline. Its whole code has to be rewritten to allow multiple pipelines to be configured by the user.
- Our interaction with the gsettings database evolved over the years around the idea we have only 2 pipelines. So the way we use gsettings will have to go through major changes
- Our presets infrastructure also assumes 2 pipelines. So more major changes here
- Our interaction with pipewire will be obviously more complicated because we would have to load a virtual device for each extra pipeline. And all of them will be visible to the user.
- Out preset autoloading code will also have to go through major changes

And the list will probably grow once actual work is put on this. It would be a cool feature to have. But the amount of work required for it is really huge.

As we already have #1145 we can close this issue.
