### ISSUE TITLE
Clicking the text to the right of a volume slider causes that slider to instantly jump to the maximum value.

### ISSUE THREAD

**Issue by Expletive** [wwmm/easyeffects#2767]
### EasyEffects Version

7.1.3

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux

### Describe the bug

Clicking the text to the right of the volume slider for input/output causes the slider to instantly jump to the maximum value. 

### Expected Behavior

When I clicked the text for "0.0db" I was hoping to be able to enter a value as text, or failing that, that nothing would happen. Instead, the volume instantly jumped to +36 db, which is very bad if there happens to be audio playing because now that audio will be much louder, possibly at harmful levels.

![image](https://github.com/wwmm/easyeffects/assets/9963278/259bab0d-06a1-4ea0-97e4-5e5b44b3dd9f)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by violetmage** [comment]
Nice catch! I will have to do some googling before I try to make a PR, as I'm still learning, but this is definately something that needs to be addressed.

**Comment by violetmage** [comment]
@wwmm Is this actually just a GTK quirk, and not something we really have control over?

From what I understand, the GtkScales in the loudness_ui are just using the `draw_value` property that is provided by GtkScale itself, and therefore it's behavior when clicked as well.

**Comment by wwmm** [comment]
> Is this actually just a GTK quirk, and not something we really have control over?

Definitely a GTK thing. Somehow in all these years I never tried to click over its label :smile: . We have no control at all of this. 

I think they are doing this by design. A click on a label is not going to set the scale to its maximum value on its own. You have to add the code that processes the click and do something with it in side a callback you have to add. In any case nothing we can do about it here without resorting to unsupported and obscure methods that try to change the private implementation of the widget.
