### ISSUE TITLE
Easyeffects Still Remember Previous Settings Even After Uninstall And Deleting ./config/easyeffects

### ISSUE THREAD

**Issue by Jam3alay8** [wwmm/easyeffects#2803]
The tittle says it all.
Using Easyeffects 7.1.3. I noticed that I can no longer change the order of the effects.
I uninstalled Easyeffects, flushed ./config/easyeffects, reinstalled and easyeffects somes up with the multiband compressor that I had previously chosen. Any effects that I add, are listed after the multiband compressor.
Next to each effect there is a (down) arrow at left of the effect, and a hamburfer icon to the right of the effect, saying click to move the effect up or down. Neither the arrow nor the hamburger menu have any effect.

I need to know how can I have a clean install of easyeffects.
My DE: KDE (Wayland)

**Comment by wwmm** [comment]
>I need to know how can I have a clean install of easyeffects.

Try to run `easyeffects -r` to reset its settings. The folder in the user config is only for preset and impulse response files not for the plugins parameters. These ones are stored in a GSettings (dconf) database.

**Comment by violetmage** [comment]
@Jam3alay8 It would also be great to know what distribution you're using, as well as where you installed easyeffects from (distribution package manager, flatpak, source)

**Comment by Jam3alay8** [comment]
Thanks for the quick response. My distro is Garuda. I have come to realize
that I don't need Easyeffects, several reasons, I have an excellent set of
external speakers, my music library is vorbisgain tagged, Easyeffects uses
Ebu R 128.
Thanks for eluciding the mystery.

**Comment by violetmage** [comment]
Thanks for the update.

Did running `easyeffects -r` fix your problem by any chance?

**Comment by Jam3alay8** [comment]
@violetmage I didn't run easyeffects -r, once I came to the conclusion that I didn't need it.
However this does not explain why after uninstalling, easyeffects still remembers previous settings. 
This might be useful for current and/or future users of easyeffects.
Audio is fun, audio is weird. Found out that dB, sound pressure, perceived loudness are listener dependent.
I tagged some songs with EBU R 128 and notice at the same dB level (with my main volume dialed down from 80 to 60)
the perceived loudness was higher than vorbisgain tagged music, go figure.
To me, EBU R 128 produces wickedly loud sound, compared to Vorbisgain, hence no EBU R 128 for me.
Closing this chapter of my audio wanderings.

**Comment by violetmage** [comment]
@Jam3alay8 Glad you found a solution.

However, I want to answer your question, "Why doesn't uninstalling easyeffects remove preferences?":

easyeffects uses gsettings / dconf by default, when you install it from a package manager like pacman. This means that because your settings are not saved to a regular file, and instead to your local user's dconf database, uninstalling easyeffects in this scenario won't remove your settings. That's why easyeffects has the -r option in the first place.

However, the flatpak package, for example, does not use gsettings or dconf to store settings, instead a regular file within it's sandbox. This means that uninstalling the flatpak using `flatpak remove --delete-data` _will_ remove the settings in this scenario, because the flatpak is configured to store settings in a regular file.

**Comment by Jam3alay8** [comment]
Ah thanks for enlightening me.
I want to take this opportunity to tell you that this brief interaction
with you was extremely pleasant.
Wishing you well,

Thanks.

**Comment by Jam3alay8** [comment]
Me again.
Back to using Easyeffects.
My formula: Multiband compressor
Limiter and Level meter.
Most importantly I play my music without the Vorbisgain tags.
I use the Raspberry player with EBU R 128 -23 LUFS.
I am happy.
Just wanted to let you know.
BTW Easyeffects is awesome.
Perhaps you could add to the docs of Easyeffects a warning related to
playing Vorbisgain files through EBU R 128.
Perhaps this is something that everyone knows.

That's all.
Thanks for a great piece of software.
