### ISSUE TITLE
Meters not updated when the pipeline changes

### ISSUE THREAD

**Issue by Digitalone1** [wwmm/easyeffects#2998]
I noticed this bug when I was testing #2997 

But I tested also on the master branch and I can reproduce it.

When the pipeline changes, the meters are not uploaded anymore, so level bars are stuck, no movement.

The plugins are playing correctly since I can change parameters and I hear the difference in the sound, but the meters in the UI are still frozen.

It should be quite easy to reproduce. Just add a level meter to your setup. Only the level meter is updating. The other plugins not. Then move the level meter in another place and it's also stuck.

@wwmm can you reproduce it?

**Comment by violetmage** [comment]
+1

I noticed this the other day with the level meter as I was messing with my pipeline. I'm using the flatpak, which is currently at version 7.1.4.

I noticed that this sometimes will happen with plugins other than the level meter, and involving the last plugin of the pipeline in the move in some way gives a higher probability of plugins getting "stuck". Getting a plugin "unstuck" sometimes only requires moving it, other times deleting and readding it entirely.

The level meter does seem to be the most consistently broken in this regard.

**Comment by wwmm** [comment]
I did some tests with the autogain that has lost of meters. When the bug happens all of them stop working. So one possibility is that the variables `post_messages` and `send_notifications` are not being properly updated somewhere...

**Comment by wwmm** [comment]
>@wwmm 

Randomly. It is not always that it happens and when it does usually only the plugin before the last one is affected.

**Comment by wwmm** [comment]
I forced `PluginBase::set_post_messages` to always set `post_messages = true` and the problem was gone. So it seems that something odd is happening when `PluginBase::set_post_messages` is called.

In order to not waste processing power we disable the level meters broadcasting when the window is closed. THis is done by calling `PluginBase::set_post_messages(false)` in the widgets `dispose` function. My guess is that a new plugin window is being called and setting `post_messages = true` before the previous plugin window dispose runs and calls `PluginBase::set_post_messages(false)`. So the previous widget dispose is probably setting the post_messages to false. 

How this is happening now I have no idea. Maybe some internal change in gtk4 is exposing the weakness in our code. We have to change how `post_message` is updated. And using mutex is probably not going to help because all of this is happening asynchronously in gtk main thread.

**Comment by violetmage** [comment]
Why would dispose ever get called when just re-ordering or adding plugins?

**Comment by wwmm** [comment]
> Why would dispose ever get called when just re-ordering or adding plugins?

Because the reordering is removing the widgets from the container and populating the container again. This is way easier than actually trying to micromanage what is happening to each container child.

**Comment by wwmm** [comment]
I've updated the master branch. Things seems to be fine now.

**Comment by Digitalone1** [comment]
Thanks. I will test it tomorrow when have time.

**Comment by violetmage** [comment]
I played with it a bit just now, seems to be fixed for me.

**Comment by Digitalone1** [comment]
This is resolved. A new release should be made to push the fix to regular users.
