### ISSUE TITLE
Output channel reverts to default after rebooting

### ISSUE THREAD

**Issue by Eonfge** [wwmm/easyeffects#313]
My PulseEffects installation keeps reverting back to the default output channel after I reboot my system. I have a somewhat unusual setup, which apparently doesn't play nice with PulseEffects:

all audio apart from music -> headset (default config)
music player -> PulseEffects -> room speakers

I instructed PulseEffects to not use the default output channel, but I have to do so every time I reboot. Am I missing a button or is this unintended behaviour?

![2018-08-25 08-02-59-audio-setup](https://user-images.githubusercontent.com/33983090/44615646-6d012e00-a83f-11e8-9d01-91beb12f1938.jpg)
_And there is nothing wrong with ABBA_

system details:
Ubuntu 18.04
PulseEffects 4.2.8
PulseAudio 12.2 

Can provide additional debug info if so required.

**Comment by wwmm** [comment]
Hi! This is a limitation. The custom device is not remembered. It is not that it can't be done but other features always had more priority. And up to now it didn't seem that people needed this.

I will take a look. Saving the custom device is easy. But it will also be necessary to check that it still exists in the next PE start and in case it doesn't we have to fallback to the default device somehow. Otherwise we will crash
