### ISSUE TITLE
Changing Pipewire Bitrate Breaks Easyeffects

### ISSUE THREAD

**Issue by StephanieSunshine** [wwmm/easyeffects#3223]
### EasyEffects Version

7.1.7

### What package are you using?

Arch (easyeffects)

### Distribution

Arch Linux / Endavour OS

### Describe the bug

Easy effects works fine on my machine until I try to set the bit rate using:

`pw-metadata -n settings 0 clock.force-rate 768000`

I have an SMSL DO-300 DAC via USB that can do this bit rate easily (and does), but when the bit rate changes, easy effects stops working.

I'm happy to supply any other information that might be needed. Thanks!

### Expected Behavior

I would expect EasyEffects to keep working after the bit rate change (the audio itself does, EasyEffects just isn't in the chain anymore)

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

### Additional Information

I'm happy to provide a log if requested. I have to reboot to properly create one and would lose this bug report at this time.

**Comment by wwmm** [comment]
Changing the sampling rate is fine. I've configured PipeWire on my machine in a way that it does this automatically. The problem here is the frequency you are trying to use. Some plugins do not work at such a high values. For example we use many plugins from `Linux Studio Plugins` (like the equalizer) and if I am not mistaken they do not support more than `384 kHz`. Look at  #2069 where LSP's author also commented.

**Comment by StephanieSunshine** [comment]
Thank you, that seems to the case here as well.
