### ISSUE TITLE
Auto gain

### ISSUE THREAD

**Issue by yurikfm** [wwmm/easyeffects#3245]
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Ubuntu 24.04

### Describe the bug

Doesn't work well auto gain Reacts to silence.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Paste your log here
```
</details>

**Comment by wwmm** [comment]
>Doesn't work well auto gain Reacts to silence.

You probably need to set the `silence threshold` in the autogain window to a higher value. Silence level is tricky to handle because it won't be the same for every source. It is easy to consider valid audio as background noise if the threshold is too high. But if it is too low then the autogain will keep updating its gain correction because of background noise.

Other than setting the silence threshold to a higher value I do not see what else can be done. There isn't much information in the report.

**Comment by yurikfm** [comment]
In PulseEffects, auto gain did not deepen the silence. And as a result, there were no bursts of sound. Probably easyeffects does not work correctly with sound modules.

**Comment by wwmm** [comment]
>In PulseEffects, auto gain did not deepen the silence. And as a result, there were no bursts of sound. Probably easyeffects does not work correctly with sound modules.

It doesn't "deepen the silence". The silence level is te one coming from the source and still not processed by the autogain. I use this plugin all the time in EasyEffects just like I did in PulseEffects and I do not hear bursts of sound. How are you configuring its `reference mode` and the target level?

**Comment by yurikfm** [comment]
I didn’t mean “deepens”, but rather intensified the silence. This is Google translation.

**Comment by wwmm** [comment]
>but rather intensified the silence

Hum... This would mean that the autogain reduced the magnitude of the gain correction. What is the oppose of what I would expect in a situation where the signal level is getting close to "silence". IS the output gain showed in its window at a lower value than normal when this happens?

**Comment by yurikfm** [comment]
> IS the output gain showed in its window at a lower value than normal when this happens?
This is a valid question. Output gain is broken. I installed Pulseeffect(4.8.7) on Ubuntu 24.04 and the output gain works correctly there.
![pulseeffects](https://github.com/user-attachments/assets/f5bc5491-5708-4340-bbc3-bbe05c76be3a)
