### ISSUE TITLE
Crackling Audio Output: Deep Noise Remover effect conflicts with equalizer ?

### ISSUE THREAD

**Issue by TriRetr0** [wwmm/easyeffects#3272]
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Pop!_Os

### Describe the bug

So everything sounds fine when I'm not in a voice call, but as soon as I do, the audio starts to crack badly
I have an equalizer as output effect and a deep noise remover as input effect
As soon as I disable deep noise remover (or the equalizer), the audio becomes clear again

### Debug Log

<details><summary>Debug Log</summary><br/>

```
[easyeffect.log](https://github.com/user-attachments/files/16366595/easyeffect.log)
```
</details>

### Additional Information

Here's my pw-top when it cracks:

![image](https://github.com/user-attachments/assets/9cca8b3d-4a3d-4298-86f6-72e0194b64d5)

As you can see there's a lot of errors on the audio output effects

**Comment by wwmm** [comment]
>So everything sounds fine when I'm not in a voice call, but as soon as I do, the audio starts to crack badly
I have an equalizer as output effect and a deep noise remover as input effect
As soon as I disable deep noise remover (or the equalizer), the audio becomes clear again

Usually when activating a second pipeline causes crackling the reason is PipeWire switching to a `QUANTUM` (related to the latency) that is lower than the one the system can handle with the current load. Your pw-top output shows that your soundcard quantum is `256`. Many systems are not able to handle this without crackling. 

What you may try is to temporarily force a fixed and higher quantum value to see what happens https://gitlab.freedesktop.org/pipewire/pipewire/-/wikis/Guide-Latency.

**Comment by TriRetr0** [comment]
I see

**Comment by TriRetr0** [comment]
I thought setting up the minimum quantum in the pipewire config files would be enough but apparently some apps can override that

**Comment by wwmm** [comment]
> I thought setting up the minimum quantum in the pipewire config files would be enough but apparently some apps can override that

Strange. I think that a minimum set in its configuration files should have enforced a lower bound for the quantum.
