### ISSUE TITLE
[Request] Display the current preset on the top bar

### ISSUE THREAD

**Issue by ParticleMon** [wwmm/easyeffects#3296]
Display the current preset between the Presets drop-down and the Bypass icon instead of at the bottom of the Presets modal.

Easy Effects 7.1.6

**Comment by wwmm** [comment]
Many years ago someone asked for something similar. The issue is this does not work well with presets that have long names. And some users need to set long names. This would be even worse on smaller screens. As much as I can see this being nice in some cases I still do not think this will work well in the title bar.

Also have in mind that there is no "current preset". Just the last loaded preset. At any time the user could have changed a parameter and the setting in place won't be necessarily equal to the preset. If we give to much visibility to the preset name people may have the wrong idea.
