### ISSUE TITLE
[Request] Cycle through drop-down items with arrow keys

### ISSUE THREAD

**Issue by ParticleMon** [wwmm/easyeffects#3298]
Allow drop-downs to be selected so up/down will cycle through their items.

Easy Effects 7.1.6

**Comment by wwmm** [comment]
We do not disable this it is the way gtk4/libadwaita works. Considering I have already started to work in a Qt port it won't be worth to put effort in figuring out how to force it to behave otherwise. If it is even possible. 

For now I will close this issue. Hopefully with Qt it will work on its own.
