### ISSUE TITLE
Deep Noise Remover isn't available

### ISSUE THREAD

**Issue by ghost** [wwmm/easyeffects#3469]
### EasyEffects Version

7.1.7

### What package are you using?

Flatpak (Flathub)

### Distribution

Fedora 40

### Describe the bug

![Capture d’écran du 2024-10-23 16-29-47](https://github.com/user-attachments/assets/01205940-756d-4b5c-bfbb-13328bd25d99)

As you can see above, even though the other filtres doing a great job, it says "deep filtre net not installed" which is the most important filtre ever.

### Debug Log

<details><summary>Debug Log</summary><br/>

```
Commit: Could not find commit of build
```
</details>

**Comment by wwmm** [comment]
Maybe the Flatpak package does not build the ladspa plugin for the deep noise remover. This is probably the most likely explanation. Is that the case @violetmage ?

**Comment by violetmage** [comment]
No, the flatpak does include deepfilternet:

https://github.com/flathub/com.github.wwmm.easyeffects/blob/master/easyeffects-modules.json#L341

I think this is actually the result of a somewhat confusing default setup in fedora; they have their own flatpak repo that is enabled by default, while the flathub repo is **installed but not enabled**. This can quickly cause confusion.

It is easy to confirm if this is the case, simply by running `flatpak list all`

**Comment by wwmm** [comment]
> No, the flatpak does include deepfilternet:
> 
> https://github.com/flathub/com.github.wwmm.easyeffects/blob/master/easyeffects-modules.json#L341
> 
> I think this is actually the result of a somewhat confusing default setup in fedora; they have their own flatpak repo that is enabled by default, while the flathub repo is **installed but not enabled**. This can quickly cause confusion.
> 
> It is easy to confirm if this is the case, simply by running `flatpak list all`

Oh... I see. Even without being a Fedora user I can see this being really confusing.I wonder why they can't just using flathub. Maybe because not everything that is there will be free of proprietary software...

**Comment by vchernin** [comment]
> So you say the whole problem will be solved if i remove the program and select the flatpak repo instead of fedora version on flatpak while downloading it?

Yes, the flathub flatpak package will work.

**Comment by alviceno** [comment]
Had the same problem with multiple plugins in EasyEffects with Fedora 40, the flathub version fixed it.

**Comment by balcala** [comment]
While I like and use Flatpaks for some apps (like Obsidian and Telegram) some of us prefer to use the Fedora native EasyEffects app instead of the Flatpak due to the permissions issues caused by the sandboxing (e.g., the inability to start EasyEffects as a service).

To use the Deep Noise Remover effect in the Fedora native EasyEffects app, download the latest DeepFilterNet LADSPA library, in this case libdeep_filter_ladspa-0.5.6-x86_64-unknown-linux-gnu.so:

`wget https://github.com/Rikorose/DeepFilterNet/releases/download/v0.5.6/libdeep_filter_ladspa-0.5.6-x86_64-unknown-linux-gnu.so`

Then run: 

`sudo cp libdeep_filter_ladspa-0.5.6-x86_64-unknown-linux-gnu.so /usr/lib64/ladspa/libdeep_filter_ladspa.so`

Quit EasyEffects from the menu and then restart it, you should now be able to use the Deep Noise Remover effect in native Fedora EasyEffects app.

Note that I used cp for a reason:

1) You can use mv but doing a cp lets you keep the original file you downloaded so you can verify the version you have installed.

2) You could create a symbolic link but if you do and inadvertently delete or move the file you downloaded you will break the Deep Noise Remover effect.

IMHO since this is such an simple fix the EasyEffects team should document this in a FAQ rather than push people to use the Flatpak.

**Comment by wwmm** [comment]
> IMHO since this is such an simple fix the EasyEffects team should document this in a FAQ rather than push people to use the Flatpak.

Feel free to add it to our FAQ https://github.com/wwmm/easyeffects/wiki/FAQ. It can be edited by the public. As I use Arch Linux I am not in a position to test solutions for other distributions.
