### ISSUE TITLE
Gnome extension to switch presets

### ISSUE THREAD

**Issue by vktRus** [wwmm/easyeffects#544]
Need to show the current preset in the tray. And fast switching of presets from tray.
Can be as gnome extension for sound indicator.

**Comment by wwmm** [comment]
The only way I see this happening is if someone that knows how to write  GNome extensions creates one for preset switching. As GTK 4 will not support tray icons there is no point in using them to add this functionality now just to remove it when The port to GTK4 begins.

**Comment by wwmm** [comment]
0And I wiould have to expose the necessary functions to this extension somehow. As a mind note to myself and for others these are the relevant places in PE code:

https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/src/presets_manager.cpp#L229

https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/src/presets_menu_ui.cpp#L228

https://github.com/wwmm/pulseeffects/blob/98ec74d58cdb7bd8bf29f816b5f6aafe43eafc29/src/application.cpp#L52

I think that the easier way would to change our code so that `presets_manager->load` is called when the gsettings key `last-used-preset` is changed. This way an extension would be able to change presents by writing to our gsettings key. No direct interaction with PE would be needed.

**Comment by wwmm** [comment]
There is one for this now https://github.com/wwmm/easyeffects/wiki/Preset-Selector-GNOME-Extension
