### ISSUE TITLE
Specify dependencies by feature.

### ISSUE THREAD

**Issue by AMDphreak** [wwmm/easyeffects#699]
I arrived at this github project because of a bug related to the equalizer plugin not working--while every other plugin works. First off, the equalizer plugin is *the* reason people use PulseEffects. It's there to correct for crappy speaker calibration or provide other spatial effects. I found this thread on Reddit that was entirely unhelpful:

https://www.reddit.com/r/debian/comments/djuo28/how_to_get_pulseeffects_equalizer_to_work/?utm_source=BD&utm_medium=Search&utm_name=Bing&utm_content=PSR1

Someone suggested to visit the project repository and look at the dependencies in the Applications Input section. It is clear however that that section is completely useless to anyone trying to get this working efficiently and not crud up their system with unnecessary packages.

You need to SPECIFY which packages are required for which features. They are not named sensibly, so you must map them for the user. Don't expect your users to be as familiar with your project as you are.

> Applications input
Gate
Multiband gate
WebRTC
Limiter
Compressor
Multiband compressor
Equalizer
Reverberation
Pitch
Filter (low-pass, high-pass, band-pass and band-reject modes)
De-esser
The user has full control over the effects order. Just use the up/down arrows next to the plugin label at the left side. To be able to use all plugins you must have the following installed in your system:
>
>GStreamer plugins "Good". Version 1.12.5 or higher
GStreamer plugins "Bad". Version 1.12.5 or higher
Linux Studio plugins
Calf Studio plugins. Version 0.90.1 or higher.
ZamAudio plugins
MDA.LV2
libsamplerate
libsndfile
zita-convolver
libebur128

**Comment by Digitalone1** [comment]
Install the latest git master. The interface plugin displays a credit giving the user a suggestion on which dependency he/she has to install.

**Comment by wwmm** [comment]
>You need to SPECIFY which packages are required for which features. They are not named sensibly, so you must map them for the user. Don't expect your users to be as familiar with your project as you are.

I think that what @AMDphreak wants is the name of each dependency package. This is hard to do because nowadays there are quite a few distribution shipping PulseEffects and they do not name their packages following the same conventions. I use Arch Linux and it names its packages differently from Debian. Fedora, OpenSUSE, Mandriva, Gentoo Solus, etc, probably have their own rules to name packages too.

Providing package names for distributions I do not use will require a time that would be better invested fixing bugs, reviewing pull requests or implementing features. It would be better that people actually using these distributions contributed to our wiki https://github.com/wwmm/pulseeffects/wiki/Package-Repositories writing these dependencies names.
