### ISSUE TITLE
[Feature Request] Ability to hide unused plugins.

### ISSUE THREAD

**Issue by Mlocik97-issues** [wwmm/easyeffects#725]
For example, I'm not using Reverbation, so I would like to hide it from interface.

**Comment by Digitalone1** [comment]
When you hide it, then how you will enable it if you would use it?

**Comment by wwmm** [comment]
We will need one more tab in the settings menu. But this is not what is going to require more work. The order of the plugins in the dynamic pipeline is kept in sync with the order of the entries in the interface. Once we start to hide things there we have to be careful to no t break the pipeline because removing the plugin container there will bring more headaches than benefits.

**Comment by wwmm** [comment]
It can be done in EasyEffects 6.0.0
