### ISSUE TITLE
How to disable PulseEffects config when using headphones?

### ISSUE THREAD

**Issue by airda2895** [wwmm/easyeffects#765]
Hi, I've recently installed PulseEffects and I set "Bass Enhancer" in order to improve the sound quality.

I like it how the music sounds on my laptop's speakers now. However, it's completely the opposite when I use headphones. I prefer the default config when I use them. So, I'd like to know if there's any way to disable PulseEffects config when headphones are connected. 

I know that I can disable "Bass Enhancer" manually, but is there any way to do it automatically so I won't have to disable it each time I use my headphones?

Thank you!

**Comment by wwmm** [comment]
There is a non optimal way of achieving this. Create a preset where all plugins a disabled. Let's say that you call it `none` like in the image below
![Screenshot from 2020-08-26 11-13-55](https://user-images.githubusercontent.com/16225172/91314822-5626a680-e78d-11ea-86f3-af1050fcbf7a.png)
While the headphones are plugged click on the middle button with a curved arrows icon. This is the preset autoload button. As long as it is activated when the target device is selected as default the corresponding preset will be automatically loaded whenever this device becomes the default again. IF I am not mistaken there is a `5 seconds` timeout before this autoloading happens.

I say it is not an optimal way to solve this issue because PulseEffects pipeline will still be processing the application output and introducing some latency. If this is not a concern then it is ok to follow this path.

**Comment by airda2895** [comment]
Thank you @wwmm! This works perfectly! Yes, there is a 5 seconds timeout.
By the way, I probably have a different icon theme because I see a folder icon instead of a curved arrows icon:
![image](https://user-images.githubusercontent.com/45570407/92509274-49cd2f80-f20a-11ea-8772-836ce22d167f.png)

**Comment by wwmm** [comment]
>I probably have a different icon theme because I see a folder icon instead of a curved arrows icon

That is something I did not expect. For sure you icon theme is different as you seem to be on KDE and I am on GNOME. I did not know this change in icon could happen in a way that the replacement is so different from the one intended. @Digitalone1 are you using KDE?

**Comment by Digitalone1** [comment]
@Digitalone1 not anymore, I switch to Gnome Shell.

If it's a theme issue, it could be resolved changing it. Maybe it's also because the icon is not "symbolic", but I don't remembered. Should be checked through glade.

**Comment by wwmm** [comment]
The icon is symbolic `emblem-synchronizing-symbolic`. This seems to be one of those cases where different art designers have very different ideas about how an action should be represented. I think that the only way to avoid these situations would be to have a custom icon embedded in our executable like it is done in the `sine wave` used in the test signal generator button.

**Comment by wwmm** [comment]
Or maybe not using an icon and writing text.

**Comment by Digitalone1** [comment]
It's an issue of the breeze theme on Plasma, the have to resolve it in my opinion. When I was using Plasma, and even now on Gnome, I had korla icon theme which I think is the best.

**Comment by airda2895** [comment]
Yes, @wwmm I'm using Kubuntu 20.04, so I have KDE Plasma 5.18.5.
