### ISSUE TITLE
Audio distortion/muddy after latest update to PulseEffects

### ISSUE THREAD

**Issue by yuljk** [wwmm/easyeffects#802]
Hi - I'm running Linux Mint 20 with a FIIO E10K and a pair of Sennheiser HD599's.  Everything was working fine with my EQ settings before the last PulseEffects update.

Now when I listen to most music at relatively high volume I get distortion/muddy sound.  I noticed when looking at the interface I see a warning symbol at certain dB levels.  I presume this is related to clipping?

I can provide my EQ settings if that helps. Although the same settings were working without issue prior to the upgrade.

Kind Regards

**Comment by wwmm** [comment]
>I noticed when looking at the interface I see a warning symbol at certain dB levels

In the new PulseEffects version this warning shows that the sound level sent to the sound card is too high (above 0 dB). This will cause distortion(clipping). But I wonder why you did not have this issue before.

>I can provide my EQ settings if that helps

Take a print of the window. Maybe it helps. But the source of the issue is probably too much amplification somewhere. Maybe the input or the output gain are set to too high values.

**Comment by yuljk** [comment]
Thanks for the reply.
Here are screenshots of my EQ settings.

[](https://imgur.com/a/wJGe4IM)

**Comment by yuljk** [comment]
https://imgur.com/a/wJGe4IM

**Comment by yuljk** [comment]
Reducing the volume of the input slider seems to have cleared up the clipping issue.  I'm still experiencing some muddiness at higher volumes though.  Anything I should modify on the EQ side?
Many thanks

**Comment by Digitalone1** [comment]
A good rule of thumb is to always set a limiter as last plugin to avoid clipping.

**Comment by yuljk** [comment]
Is this the case even if it is disabled?

**Comment by Digitalone1** [comment]
You set +5 of gain on the first band, this is likely to produce clipping.

You didn't take the saturation icon in the screenshot, but you already said that it was showing. 

Don't know why it wasn't happening before. It depends on the previous version of PulseEffects, maybe you were using an old one with a different release of lsp-plugins which could have a different behaviour.

**Comment by wwmm** [comment]
>Is this the case even if it is disabled?

No. You have to enable the limiter for its protection to take place. But avoiding too strong signals still is the best solution. the limiter will avoid the signal getting above 0 dB. But if signal average amplitude is too high the limiter will make the audio signal flat in order to achieve this goal. Something like applying a ridiculously strong compression. What will kill the dynamic range. Think of the limiter as a fail-safe for those rare situations where a transient bass would make the signal go above 0 dB. Do not enable the limiter thinking that now it is ok to amplify the signal without limits.

**Comment by wwmm** [comment]
>Don't know why it wasn't happening before

I have a theory. For some reason that is beyond me some applications decide to mess with our sink volume. Usually they reduce it. In the latest version PulseEffects sets the volume of our virtual devices to 100 %. Where they should be. Maybe one of those applications had decreased our virtual devices volume in his system. And Pulseaudio remembers this. It does not go away by rebooting. Now that he upgrade to the latest version the volume is where as it should be. But now there is clipping because the settings he had before were applying more amplification than necessary.

If that is not the reason I don't know what else could have been.

**Comment by Digitalone1** [comment]
It could be. And one has to look also if flat volume is disabled. 

The better solution would be to reduce the equalizer output by about 5-7 db and enable the limiter on 0 db (autoleveling and ASC both disabled)

**Comment by yuljk** [comment]
Hi guys - Thanks for the replies. I have reduced the input and output on the Equalizer pane to 5dB and enabled the limiter to 0dB.
I shall see how it sounds next time I'm listening to music.

**Comment by Digitalone1** [comment]
No need to reduce the input also. Maybe you can reduce only the output to 7 db, or leave both at 0 and reduce the limiter input only.

**Comment by yuljk** [comment]
Setting the input to 0 and output to -7.0 seems to have fixed the issue with clipping and muddiness.  I've disabled the limiter for now as don't want to run into compression issues as stated.

Not sure what happened during the upgrade to change the behaviour as previously both input/outputs were set to their defaults '0'.

**Comment by yuljk** [comment]
I should note my audio application is foobar2000 installed via snap with the output set to 'pulseaudio'

**Comment by wwmm** [comment]
Our virtual devices are the ones in these image. It is rare but sometimes it happens third party applications like games decide to change their volumes. Now whenever PulseEffects starts it sets our devices volumes to 100 % to mitigate these third party apps actions. This is the only change in the latest release that could have caused this change in signal level.
![Screenshot from 2020-10-10 11-15-31](https://user-images.githubusercontent.com/16225172/95657263-ec1e5280-0ae9-11eb-8938-7cda7ce570de.png)

**Comment by Digitalone1** [comment]
> Setting the input to 0 and output to -7.0 seems to have fixed the issue with clipping and muddiness. I've disabled the limiter for now as don't want to run into compression issues as stated.

If you want to avoid strong compression having no clipping at all, reduce anymore eq output (9-10 db) and enable limiter.

**Comment by wwmm** [comment]
>I've disabled the limiter for now as don't want to run into compression issues as stated

Usually I have the limiter enabled. It is good as a protection to the sound card and speakers in case an unintended strong transient happens. What you do not want is to have an average signal that is so strong that the limiter algorithm has to be active all the time. Take a look at the image below. As long as the attenuation level meter is almost always at `zero` you can have the limiter active with no worries about dynamic range changes.
![Screenshot from 2020-10-10 11-29-09](https://user-images.githubusercontent.com/16225172/95657635-dc077280-0aeb-11eb-9a6d-869322e34848.png)

When making your settings take a look at the attenuation level. If it is above zero reduce the equalizer output gain by an amount that you fill that it is enough to make the attenuation level equal to zero to all the material you usually listen to. This way the limiter will take action only when a unusual strong transient happens.

**Comment by yuljk** [comment]
Cheers for the very thorough explanation of the settings fellas.  Sounding a lot better now with the limiter set and input at -9.0.  The attenuation hasn't gone above 0 yet in my testing.
