### ISSUE TITLE
Import Filter Settings file from Equalizer APO to Pulseeffects EQ

### ISSUE THREAD

**Issue by rav242** [wwmm/easyeffects#808]
Is there any way to import Filter Settings file from Equalizer APO to Pulseeffects EQ? I have a few Settings files for different situations, each one of them contains of ~20-30 bands settings. Manual EQ setting takes huge time.

**Comment by Digitalone1** [comment]
Yes, it's a feature added from 4.8.0 version under Equalizer settings.

**Comment by wwmm** [comment]
Just have in mind that the support is not complete. For example multichannel presets are not supported as PulseEffects is a stereo application. There are also other things I do not remember now. But with luck what is available now will be enough for you needs.

And I recommend you use PE `4.8.2` because I made a mistake when releasing this feature in PE `4.8.0`. Only in `4.8.2` the bands are set to APO mode when a APO preset is imported.

**Comment by rav242** [comment]
Thank you!!
Is there any plans supporting 5.1 and HRTF?

**Comment by wwmm** [comment]
>Is there any plans supporting 5.1 and HRTF?

Not at the moment. Supporting 5.1 is hard not only because handling multiple channels is harder. Most of the plugins we use in PulseEffects only work with 2 channels. And unfortunately I do not have the necessary knowledge to rewrite them as 1 channel plugins. And in some cases this does not make sense. The stereo tools and the crossfeed plugins are an example. And on top of that the user interface our presets infrastructure has to be extended in a way where different channels can be appropriately configured.

**Comment by rav242** [comment]
Thank you for the answer. Any plans implementing HRTF switch in GUI (HRTF is already implemented in pulseaudio
 but without GUI)?

**Comment by wwmm** [comment]
Being honest I never really understood how Pulseaudio support for HTRF works. But I doubt we can just use it in PulseEffects. For us the ideal solution would be to use a GStreamer, LV2 or LADSPA plugin that does that. But I am not aware of any with HRTF implemented. And at this moment I do not know enough about HRTF to try do write my own plugin.
