### ISSUE TITLE
Permament shallow CPU usage by pulseaudio

### ISSUE THREAD

**Issue by sophiekums** [wwmm/easyeffects#829]
Hi,

First of all thank you for providing the community with such a powerful and easy-to-use tool! I was able to improve the sound quality of my notebook substantially.

I noticed that the pulseaudio process (not pulseeffects) constantly consumes 1-2% of one CPU core as measured by `top` after the first time that I play some audio. This is not the case when pulseeffects is disabled, so it must be caused by the presence of pulseeffects. The CPU usage does not settle down when the audio stops. I know, 1-2% is not a big deal, but it adds up over time, since the process runs constantly in the background and eliminating any amount of wasted CPU time is never a bad thing. I was able to eliminate it as follows:

With the help of strace I found out that for some reason pulseaudio keeps polling pulseeffects constantly and that the CPU load is caused by this polling. The usage becomes very much noticeable when the latency in pulseeffects is reduced to very small numbers, i.e. 100us. I am not advocating setting it this low, but for debugging purposes it is helpful, because the effect is more pronounced and easier to observe. Upon diving into the code of pulseeffects, I managed to eliminate the CPU usage (i.e., really bring it down to 0) by modifying the following line:

https://github.com/wwmm/pulseeffects/blob/26dc79f3d5c04003d4da2820e53fa7aa386e3cca/src/pipeline_base.cpp#L604

Instead of putting the pipeline into the `PAUSED` state, I changed the code to put it into `READY` state. I got the idea from the fact that the CPU usage drops to 0, when I play with the latency in the GUI. When the latency is changed, the pipeline is also put into `READY` state, so I figured why not do the same when pulseeffects is idle? This did the trick. With this simple modification, pulseaudio does not consume any CPU any longer when it is idle.

I did not observe any negative side-effects as a consequence of this modification. But frankly, I don't really know what I'm doing. This is all based on observations. I don't have a deep understanding of the code. My question is: Why is the pipeline put into `PAUSED` state? And is there a downside of putting it into `READY` state?

Ty,
Sophie

**Comment by sophiekums** [comment]
Forgot to mention:

pulseeffects 4.7.1-2
pulseaudio 1:13.99.1-1ubuntu3.7
Kubuntu 20.04

**Comment by wwmm** [comment]
>Why is the pipeline put into PAUSED state?

In the past there was a strong reason to do that. But this may not be necessary anymore. `GST_STATE_READY` tells GStreamer to finish the stream and free objects from the memory. Once we need to play again all these objects have to be reallocated and this takes time. At the time it was selected as the target state PulseEffects pipeline was stopped as soon as no app was playing audio. So this additional delay caused by a move to the `READY STATE` was annoying in situations where the user were doing pauses in  video or music player. That is why I replaced it by `GST_STATE_PAUSED` in this part of the code.

But time passed and eventually issue #504 was opened. Some apps like mpv actually restart their stream whenever the user does a operation like a seek in a video. In these situations stopping PulseEffects immediately causes very annoying side effects. That is why we now have a timeout during which we monitor if no applications is playing audio. And we only stop our pipeline if there is none. With this timeout in place going to the `READY STATE` may not be a problem as we do not stop our piepeline as often as we used to do in the past. I will do some tests before releasing PulseEffects `4.8.3`. By the way I suggest you update to a new version. Lots of things have changed since `4.7.1` https://github.com/wwmm/pulseeffects/blob/master/CHANGELOG.md.

**Comment by wwmm** [comment]
>When the latency is changed, the pipeline is also put into READY state

In this case we do not have a choice. Some parameters, like the buffer size, can only be set before the GStreamer stream is created. So we are forced to restart it for the new values to take effect.

**Comment by sophiekums** [comment]
Thanks for the prompt reply and the detailed explanation. I thought there was a reason for the `PAUSED` state, but simply did not notice any different behavior with the `READY` state (other than reduced CPU usage from pulseaudio). I'm glad if it turns out that you can adopt the `READY` state, but if you observe any negative side-effects in your tests, it's not a big issue either, since the CPU wastage is minor anyway.

I know I'm not using the latest version of pulseeffects. That is because I like to stick to the versions provided by the repository of my Linux distribution (Kubuntu 20.04) wherever possible. The Kubuntu version of pulseeffects works without problems on my system, so I don't see a need to upgrade. But thanks for the tip anyway!

**Comment by wwmm** [comment]
>That is because I like to stick to the versions provided by the repository of my Linux distribution (Kubuntu 20.04) wherever possible. The Kubuntu version of pulseeffects works without problems on my system, so I don't see a need to upgrade

No problems. In case you ever change your mind you can use the PPA provided by `mikhailnov`. He has been packaging PulseEffects for Ubuntu for a long time and the ones provided in Ubuntu official repository were probably based on his packages. He is also the one responsible for the debian folder in our source code https://github.com/wwmm/pulseeffects/tree/master/debian.
