### ISSUE TITLE
Multiple impulse responses at once

### ISSUE THREAD

**Issue by pulpan977** [wwmm/easyeffects#839]
I think it would be nice to be able to use multiple impulse responses at once with the convolver plugin. For example, my headphones sound a lot better with an AutoEQ impulse reponse, but I'd like to also use an impulse response that affects the stereo image.

**Comment by wwmm** [comment]
Unless there is a mathematical model allowing to combine impulse responses the only way I see to do this would be to put two convolver instances in series. But at this moment we have tons of limitations that do not allow this to be done in PulseEffects. Let's keep this issue opened for a while. Maybe someone comes with a clever solution.

**Comment by wwmm** [comment]
It seems that there are software that do that. I wonder if it is just a matter of summing the wav files of each impulse response...

**Comment by sadko4u** [comment]
>I wonder if it is just a matter of summing the wav files of each impulse response

No, just summing impulse responses will give the wrong result: you'll get two signals processed by convolvers and then summed together as a result instead of serial processing. For applying them in serial, you need to convolve one signal with another and get the impulse response which length will be sum of lengths of both responses without one extra sample.

**Comment by wwmm** [comment]
Thanks! Right now I have my hands full porting PulseEffects to PipeWire but one day I will work on this.

**Comment by capoei** [comment]
the latency will be the same, wether being to impulses in series, or one impulse that is the convolution of the two others.
So one solution without alowing two convolvers in series would be to offer an "add impulse to current one" or something like that that would make the convolution of the two impulses and than uses the resulting one. or just make it possible in the impulses list to load more than one. if two are loaded at the same time it would make the convolution and use the resulting impulse

**Comment by MalexTP** [comment]
any update of this? iwannnnnnnt :b

**Comment by wwmm** [comment]
The new code in the master branch allows impulse responses to be convolved
![Screenshot from 2021-10-29 17-55-00](https://user-images.githubusercontent.com/16225172/139501328-7c4f56f2-8e06-4b28-bbb7-47bdd30b4e57.png)
Just select the kernels and a name for the output file. Once the convolution is finished a new entry should be available in the impulse response list. People on Arch Linux can easily test this through the AUR package. I think things are being done correctly but there could always be bugs.

There is room for performance improvements. For now direct convolution is being done. Mostly because it is the only one I can code myself. I thought about using zita-convolver for this but as it requires power of 2 arrays I would have to pad the impulse responses with zeros. And I am not sure if that is something correct to do in this case. As I do not have a formal education in digital signal processing I do not know. 

In any case we do not really need this to be done with high performance. It is not done on the fly whenever we have a new audio buffer. It is calculated only when the user clicks on the "combine button". So the current approach should be enough. At least on my CPU it is no more than a few seconds looking at the progress bar when combining big impulse files.

**Comment by wwmm** [comment]
People testing this may also be hit by https://gitlab.gnome.org/GNOME/gtk/-/issues/4369

**Comment by sadko4u** [comment]
You can use [https://github.com/lsp-plugins/lsp-dsp-units](lsp-dsp-units) `dspu::Convolver` class for convolution purposes. It does not require additional threads to be started and does the job in right way.

**Comment by wwmm** [comment]
I think we can close this.

**Comment by stevecj** [comment]
> No, just summing impulse responses will give the wrong result

I just wanted to add that, although summing the IRs won't give the result being asked about, it can have a desirable result. If I understand correctly, summing them together will give the same result as running through them in parallel. Whether I have that right or not, I can say for sure that it can sound good and is worth experimenting with.
