### ISSUE TITLE
Start menu filled with undesirable entries

### ISSUE THREAD

**Issue by RUSshy** [wwmm/easyeffects#861]
![image](https://user-images.githubusercontent.com/18348637/103165056-3e326280-4813-11eb-85c0-f9ba4640fecd.png)

I feel like these entries should be removed from user start menu

**Comment by RUSshy** [comment]
This is why linux sucks so hard, people do not care about the poop they leave on people computer

**Comment by grpan** [comment]
I have been suffering from the same issue. All of these plugins which I don't use have been obstructing my searches.
However your attitude is NOT ok. Be kind, the issue will probably be fixed.

**Comment by RUSshy** [comment]
@grpan you are right, i edited the issue

**Comment by Digitalone1** [comment]
These are "spammed" by lsp and calf packages, not pulseeffects.

As you can see [here](https://archlinux.org/packages/community/x86_64/lsp-plugins/), there are tons of desktop entry files under `/usr/share/application/` installed by lsp and this package is needed by pulseeffects for some plugins like compressor and equalizer.

They can be hided by deleting the relative files, but when you upgrade the package, they will be restored.

**Comment by wwmm** [comment]
>However your attitude is NOT ok.

Thanks @grpan. I was considering not even answer to that question...

@RUSshy, as explained by @Digitalone1 all the entries in your image are from Linux Studio Plugins. The proper place to ask why this is done is this https://github.com/sadko4u/lsp-plugins/issues. But as has already been said... Be nice... This library was created way before PulseEffects development crossed my mind. Its developer probably had a reason to add these menu entries and PulseEffects users aren't his main target public. That `Provided by` in our interface does not mean `made for PulseEffects`. It is just a way to recognize each plugin developer work. His focus is on musician and audio engineers. So being aggressive there will accomplish nothing...

By the way I also don't like all these entries in the menu. But as I almost never use it anyway I did not bother opening an issue in LSP.

**Comment by Digitalone1** [comment]
If you use Gnome, you can group them together, so they won't be shown in the main app list.

![Schermata del 2020-12-27 15-14-57](https://user-images.githubusercontent.com/25790525/103172854-c6862700-4856-11eb-8570-56941a7c85fe.png)

**Comment by IdreesM0** [comment]
I was bothered by these entries too when they appeared in the menu. Its odd though since I never had them before moving to manjaro. Maybe they added them in a recent version idk. However since I use cinnamon DE, they can simply be removed from the menu applet configuration settings. I absolutely love PE! Keep up the good work bros!

**Comment by RogueScholar** [comment]
I agree that the `lsp-plugins-jack` package (which interestingly enough is the only one of the LSP Plug-ins packages to behave this way) is completely uncouth in the way it clutters up the desktop launcher menu. Luckily enough, you only need two commands to "teach it some manners" and hide those entries in a way that survives even package upgrades and the like, in the event that you actually use the JACK interface and can't just `apt purge lsp-plugins-jack` (or the like, with various and sundry package management tools) after realizing that you ended up with it only because of the meta-package and not out of any genuine need or desire for it. Those two commands are:

```bash
cp /usr/share/applications/in.lsp_plug.lsp_plugins_*.desktop ~/.local/share/applications &&
echo "NoDisplay=true" >>~/.local/share/applications/in.lsp_plug.lsp_plugins_*.desktop
```

If you happen to use the KDE Plasma 5 DE and want to see the changes instantly but don't want to wait for the next automated menu rebuild or to restart your computer, then feel free to tack on this third command as well...

```bash
kbuildsycoca5 2>/dev/null
```

...and, _VOILA_, all gone once and for all. :grinning:
