### ISSUE TITLE
Noise reduction not working

### ISSUE THREAD

**Issue by r-melo** [wwmm/easyeffects#864]
Hi, 

I have pulseefects installed in arch, and the noise reduction function is not working. The whole pane is greyed out either I mark the checkbox or not. I tried installing rnnoise and restarting pulseeffects, nothing changed. I have a constant static/hissing sound I would like to get rid of. If you know another approach, is also welcome. 

Thanks!

**Comment by wwmm** [comment]
This is happening because Arch Linux official repositories do not have the library rnnoise available. You could try to install PulseEffects using the AUR package. But there are two things to keep in mind. First you have to install rnnoise from the AUR package. And the second is that our git code has moved from Pulseaudio to PipeWire. If you have to stay on Pulseaudio you will have to use the pkgbuild in our legacy pulseaudio branch https://github.com/wwmm/pulseeffects/tree/pulseaudio-legacy. OR editing the AUR pkgbuild in a way that it uses this branch instead of the current master.

**Comment by Rundik** [comment]
> And the second is that our git code has moved from Pulseaudio to PipeWire
but why doesn't pulseeffects work with PipeWire then (I installed it after reading this comment)? Did I install it wrong? (I use arch btw)

**Comment by wwmm** [comment]
>Did I install it wrong?

It is hard to say if that is the reason. What I can say is that I am using Arch Linux and the master branch code works with pipewire and the rrnoise plugin. How did you install? Was Rnnoise installed when you compiled pulseeffects package?

**Comment by Rundik** [comment]
ok, I removed pulseeffects that was installed from the official repo and reinstalled it from the aur. Now it does sometimes work and even Rnnoise works now, but it freezes and crushes a lot

**Comment by wwmm** [comment]
Ok, now the question is if the problem is in Pipewire or in how we are interacting with it. Kill PE `pulseeffects -q` and restart it in debug mode `G_MESSAGES_DEBUG=pulseeffects pulseeffects`. This way we will see if something unusual is happening.
