### ISSUE TITLE
App icon is displayed wrong in Qt environments 

### ISSUE THREAD

**Issue by flipwise** [wwmm/easyeffects#867]
Hello,

I noticed the icon is supposed to look like this:
![image](https://user-images.githubusercontent.com/26850445/103476296-af928800-4db4-11eb-8074-8b2106d5aa7a.png)

But in Qt environments it looks like this:
![image](https://user-images.githubusercontent.com/26850445/103476305-c33dee80-4db4-11eb-961b-206e9650ac8f.png)
![image](https://user-images.githubusercontent.com/26850445/103476315-d224a100-4db4-11eb-9e66-333256601412.png)

Seems there's issues with the gradients, the shadow, aliasing and that black artifact. 

________________________
Distro and DE: Manjaro Linux KDE Plasma
Package: community/pulseeffects 4.8.3-3

**Comment by wwmm** [comment]
In the past KDE had problems with some types of SVG files. I think there was even a bug report opened there. But I do not remember the link and if it was ever solved.

**Comment by wwmm** [comment]
Nowadays we are using the icon that was created for the Kora icon theme https://github.com/bikass/kora. Try to see if the other icons from this theme are being loaded correctly in KDE.

**Comment by flipwise** [comment]
It's a general problem with Qt SVG rendering, e.g. if I open the icon with LXImage-Qt I get the same result.

Yeah I opened the previous issue #308 and then a KDE developer helped fix it.

I tried out the Kora theme now. It looks alright but the Pulse Effects SVG in it also has the same problem as the bundled one.

**Comment by capoei** [comment]
Is there suposed to be an icon in the task manager?
I am asking because there is the "shutdown on window close" option

**Comment by wwmm** [comment]
>Is there suposed to be an tray icon?

GTK4 does not support tray icons. So the answer is no. Depending on how EasyEffects is started it can keep running in the background even if you close its window. That happens by default when starting it by clicking in its desktop launcher icon. What the option you are seeing does is disabling this feature.

**Comment by capoei** [comment]
> > Is there suposed to be an tray icon?
> 
> GTK4 does not support tray icons. So the answer is no. Depending on how EasyEffects is started it can keep running in the background even if you close its window. That happens by default when starting it by clicking in its desktop launcher icon. What the option you are seeing does is disabling this feature.

here on Arch it wont run in this persistant mode with the repo package. what would be the comand line option? "easyeffects -h" wont reveal that option. the simple easyeffects comand is not persistant

**Comment by wwmm** [comment]
>here on Arch it wont run in this persistant mode with the repo package. what would be the comand line option? "easyeffects -h" wont reveal that option. the simple easyeffects comand is not persistant

Our service mode is based on a gtk feature. So you have to force it to show all the options `easyeffects --help-all`. In order to keep running in the background you EasyEffects has to be started as `easyeffects --gapplication-service`. At least on GNOME that happens by default when clicking on our icon in the applications launcher. If you enable `Start Service at Login` EasyEffects should automatically start as a service in the backgroun in your next login.

**Comment by capoei** [comment]
understood. this behaviour wont happen in KDE on Arch. will test the sugestions soon

**Comment by wwmm** [comment]
>this behaviour wont happen in KDE on Arch

Do you mean running as a service automatically when clicking on the desktop icon?  I never tested the desktop files `DBusActivatable`  feature outside of GNOME. But I think it worked on KDE too when we used gtk3. I wonder if gtk4 and KDE4 have some kind of incompatibility in this area.

**Comment by capoei** [comment]
> > this behaviour wont happen in KDE on Arch
> 
> Do you mean running as a service automatically when clicking on the desktop icon? I never tested the desktop files `DBusActivatable` feature outside of GNOME. But I think it worked on KDE too when we used gtk3. I wonder if gtk4 and KDE4 have some kind of incompatibility in this area.

when starting it from the KDE menu. it is suposed to start with "easyeffects --gapplication-service" right? the menu entry only executes "easyeffects". I now checked "Start Service at Login" and it created  a .desktop with "easyeffects --gapplication-service" in .config/autostart

**Comment by wwmm** [comment]
>the menu entry only executes "easyeffects".

That is unfortunate. I thought KDE was supposed to support this feature. If you take a look at the file `/usr/share/dbus-1/services/com.github.wwmm.easyeffects.service` you will see
```
[D-BUS Service]
Name=com.github.wwmm.easyeffects
Exec=/usr/bin/easyeffects --gapplication-service
```
When a file with this content is in the dbus folder and the desktop file associated to the apps launcher menu entry sets the property `DBusActivatable=true` the desktop environment is supposed to use that dbus service file to launch to application. More information can be seen at https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html#dbus. IT is weird this does not work in KDE.

**Comment by afontenot** [comment]
Hi, I'm the author of a relevant KDE bug: https://bugs.kde.org/show_bug.cgi?id=448234

The issue you're seeing here is that in KDE we use the Qt SVG renderer, which supports only a subset of the SVG standard. We are trying to change this, but there is no ETA currently.

Most icons work fine, but among icons that are broken, the most common problem is that they use masking or clipping paths, both of which Qt does not support.

A workaround is to use ordinary paths instead of relying on clip paths. It's not always as clean of an approach, but the result avoids the issue in Qt applications. Feel free to use the attached modifications - they should fix rendering of the pulseeffects icon in Qt.

![pulseeffects](https://user-images.githubusercontent.com/3870410/156283193-49d3ee0e-60dc-4a6a-80a9-e0eceb8a7949.svg)

Side note: there is an important difference between the behavior of clip paths and masks under Qt, for reasons unknown to me. Paths used for masking seem to become transparent, whereas clip paths become black. Neither of them are applied. For icons where using ordinary paths is not an acceptable workaround, a partial fix can often be implemented by using a mask instead of a clip path. The result will not display as expected, but a clip path at least fails gracefully by disappearing instead of leaving a black path in the image.

**Comment by wwmm** [comment]
>Feel free to use the attached modifications - they should fix rendering of the pulseeffects icon in Qt.

Thanks @afontenot. Did you test if the icon above works fine on QT environments? As I use GNOME I can't test this now.

**Comment by afontenot** [comment]
> > Feel free to use the attached modifications - they should fix rendering of the pulseeffects icon in Qt.
> 
> Thanks @afontenot. Did you test if the icon above works fine on QT environments? As I use GNOME I can't test this now.

Yes, I use KDE.

**Comment by wwmm** [comment]
Available in our master branch. I think we can finally close this issue. Thanks!
