### ISSUE TITLE
Sound goes out after launching Pulseeffects with Firefox playing

### ISSUE THREAD

**Issue by Tooniis** [wwmm/easyeffects#919]
It takes 2~5 restarts of pulseeffects to get sound back. When there's no sound the spectrum remains flat so it seems that pulseeffects doesn't receive sound from firefox.

Changing priority mode between real-time and niceness makes it work sometimes, although most of the time switching from niceness to real-time makes it get `Killed` (just says that in the terminal) instantly with firefox open, or get killed as soon as a tab with sound is opened in firefox, and switching the other way around makes it crash sometimes.

There doesn't seem to be any difference between the logs from when it works and when it doesn't
[log-broken.txt](https://github.com/wwmm/pulseeffects/files/6128740/log-broken.txt)
[log-works.txt](https://github.com/wwmm/pulseeffects/files/6128741/log-works.txt)

**Comment by wwmm** [comment]
This issue may be the same as #898. If yes the reason is still unknown and to make things worse not every hardware is affected.

At this moment I am porting PulseEffects to GTK4 and moving our effects pipeline from GStreamer to PipeWire's filters. As this issue is probably caused by a bug in PipeWire's plugins for GStreamer using PipeWire's native filters will probably fix this issue. But it is going to take a while till I finish this work...

**Comment by wwmm** [comment]
Hopefully this won't be a problem anymore in EasyEffects 6.0.0. And if it still is it will be better to open a new issue anyway
