### ISSUE TITLE
close pulseeffects service from gui

### ISSUE THREAD

**Issue by violetmage** [wwmm/easyeffects#920]
`pulseeffects -q` has no graphical equivalent

suggest `gtk_application_set_app_menu`

**Comment by wwmm** [comment]
GTK applications are not supposed to use an app menu anymore https://gitlab.gnome.org/GNOME/gtk/-/commit/79d6a77d5856b702bec3378bb2a88ecca6b7bccf. `gtk_application_set_app_menu` isn't even present in GTK4. And I am doing the port to GTK4 at this moment.

Another solution will have to be created for this.

**Comment by violetmage** [comment]
many thanks for information

am thinking, settings dialog, near "settings : reset" & "about : pulseeffects" is good place then

**Comment by violetmage** [comment]
is likely silly question:

where `quit();` is from?

https://github.com/wwmm/pulseeffects/blob/e93b685fdc802c9230b68484911444f6a1466f0c/src/application.cpp#L64-L70

**Comment by wwmm** [comment]
it is a member of the the `Application` class.

**Comment by kevincox** [comment]
I also found this super confusing. Especially since the first time I used pulseeffects I think I messed up my sound and I was frantically searching for a way to make it stop. I resorted to `killall pulseeffects` but it would be nice if there was a GUI option. I think it is fine if the main GUI needs to be opened in order to trigger it.

**Comment by wwmm** [comment]
Implemented in our gtk4 branch. As far as I can see it is working fine. But tests are welcome.
