### ISSUE TITLE
Convolver and crystallizer are not working 

### ISSUE THREAD

**Issue by tsunami95** [wwmm/easyeffects#982]
Both are greyed out. I am zita-concolver already installed. Do I need something else too? 

Also, I don't have zam-plugins. I am not sure how to install from here manually.

**Comment by wwmm** [comment]
>Do I need something else too?

These plugins are different from the others. zita-convolver has to be installed in the moment PulseEffects is compiled too. If PulseEffects is compiled in a system that did not have this library installed it is not going to work even if you install zita-convolver after.

>Also, I don't have zam-plugins. I am not sure how to install from here manually.

At least on Arch Linux the package that provides it is named `zam-plugins`. I think that most Linux distributions have a package for this plugin. the question is how they are naming it.

**Comment by tsunami95** [comment]
I did not compile it. When it installed it, zita eiter was installed as a  dependency or was preinstalled. 
Void did not have linux studio plugins either. I had manually install it.

**Comment by wwmm** [comment]
The easiest solution would be to ask the Void package maintainers to recompile PulseEffects with the zita-library installed and to also provide a package for Linux Studio Plugins.

But if that is not possible and you do not want to compile everything yourself you could try to see how hard it is to use a flatpak package in Void. This way you would not need to compile things because the flatpak package already comes with everything.

**Comment by tsunami95** [comment]
By the way, I installed linux studio plugins manually. Pulseeffects picked it up. It works. 

Is zita-library the same as zita-convolver?

I avoid flatfack. That's my lat resort.

**Comment by wwmm** [comment]
>Is zita-library the same as zita-convolver?

Maybe. There are other audio libraries whose name starts with `zita-`.

**Comment by wwmm** [comment]
As in EasyEffects 6.0.0 the convolver and the crystalizer plugins are not optional this kind of problem should not happen anymore.
